### PR TITLE
Rebase teachosm with develop

### PR DESCRIPTION
**Pull request by arunasank**
Bring the `teachosm` branch up to speed with the latest `develop`. I kept all front-end changes as is on `teachosm` and brought all the backend changes from `develop`.

I have hosted the result on https://tasks-teachosm-staging.hotosm.org.

If things look good, let us merge this!

cc/ @dakotabenjamin @xamanu

### CODE REVIEW

**Comment by arunasank** [comment]
Please don't test this yet - I messed up the rebase the second time while trying to fix merge conflicts.

**Comment by arunasank** [comment]
This is ready to be tested. The rebased code has been deployed to https://tasks-teachosm-staging.hotosm.org/

**Comment by xamanu** [comment]
I was thinking `teachosm` should be in sync with `master` not `develop`, as it is a production instance.

**Comment by arunasank** [comment]
Per chat with @xamanu, we are going to leave this branch as is, and come back to rebasing it with `master` after the 3.3 release.

**Comment by xamanu** [comment]
Let's close here and open one for `teachosm` based on `master`, once the new version has been release.

**Pull request closed without merging**
