### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by alekno** [comment]
In addition to the typo I would link to http://tasks.hotosm.org/contribute?difficulty=ALL&campaign=Disaster%20Response instead to http://tasks.hotosm.org/contribute?difficulty=ALL&text=disaster

**Comment by verdy-p** [comment]
there's another typo in the URL: the ampersand in URLs must be HTML-encoded as "&amp;" (not just "&") in HTML attributes otherwise some browsers will not enable it in strict mode.

**Comment by ethan-nelson** [comment]
@verdy-p if you don't mind throwing that in an issue since it's a bit unrelated to the pull request. the text will get lost once this gets merged.

**Comment by ethan-nelson** [comment]
@pgiraud Looks like the required "update branch" button actually merges master into the patch branch instead of develop. Sorry for the hassle--would you mind updating the branch with the latest develop branch so we can merge this pull request?

**Comment by pgiraud** [comment]
Should be OK now. @ethan-nelson please merge when CI goes green. I'm off to bed.

**Comment by ethan-nelson** [comment]
Thanks!!

**Comment by alekno** [comment]
So no discussion about my request?  I like to link to http://tasks.hotosm.org/contribute?difficulty=ALL&campaign=Disaster%20Response and not to the text search.

**Comment by ethan-nelson** [comment]
@alekno if you don't mind, could you file a new issue for that? I'd like to keep ancillary discussion separate from pull requests so it doesn't get lost. I wasn't the one who originally added that link so I don't want to say yes or no on it.

**Comment by alekno** [comment]
@ethan-nelson  I am done with it. Someone will find out sooner or later.

**Pull request merged**
