### PR TITLE
Add field for gender information in user profile

### PR DESCRIPTION
**Pull request by xamanu**
This rerolls the PR #1406 from @theprover97

### CODE REVIEW

**Comment by xamanu** [comment]
Fixes #1372

**Comment by theprover97** [comment]
Thanks @cgiovando for testing my code. Let me check for any lags and I will report it as soon as possible.

**Comment by xamanu** [comment]
@theprover97 I think I caused some confusion here. let me check before you get into extra work. Apologies.

**Comment by theprover97** [comment]
Sure. No problem.

**Comment by theprover97** [comment]
Maybe the code didn't work because I missed out on the metrics part. Sorry for that.

**Comment by cgiovando** [comment]
Hi @theprover97 - sorry for the confusion. Thanks again for the PR. I tested and the new `Gender` field is there, but there are issues with the form validation. When other fields are filled correctly, the form doesn't save the information correctly and returns random `Error: setting your contact details`

The `Gender` field should also be implemented with a drop-down menu, with fixed options for response (`Female`, `Male`, `Prefer not to Say`).

**Comment by theprover97** [comment]
Hi @cgiovando thanks for your review. I will make the required changes.

**Comment by cgiovando** [comment]
Hi @dakotabenjamin - I agree with your proposal, and would also include a brief description on why we're collecting this data - see here: https://wewillthrive.co.uk/resources/blogs/avoid-the-awkward-asking-about-gender

@TylerRadford @RebeccaFirty can you provide some text on how we're going to use this information, if we have donor requirements, etc?

**Comment by TylerRadford** [comment]
@cgiovando thanks for that helpful article. If we have space for explanatory text or mouse-over help text or similar, I would say something like this:

"HOT envisions a world where everyone can contribute to OpenStreetMap, and OpenStreetMap gender balance more closely matches that of our world in general. Help us measure our progress toward this goal by providing your gender."

**Comment by xamanu** [comment]
Thanks you all for this great input. This is now a good and strait forward plan for implementation:

> HOT envisions a world where everyone can contribute to OpenStreetMap, and OpenStreetMap gender balance more closely matches that of our world in general. Help us measure our progress toward this goal by providing your gender.
> 
> image

**Comment by ethan-nelson** [comment]
Sorry--I worded my question a bit ambiguously and wasn't sure if you want to work on the backend or have me do it. If you'd like to take a shot at it, we'll need:

1. A new column in the User table that holds the gender field: https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/user.py#L13 (it will have to be a string type for free-form response allowance)
2. A new field in the data transfer object for the user gender: https://github.com/hotosm/tasking-manager/blob/develop/server/models/dtos/user_dto.py#L31
3. Including the gender field in the update profile function for when the user saves their profile: https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/user.py#L61

That should be all the steps, but I will double check that this week. If you don't feel comfortable with the backend, I can do this work and merge it in as well!

**Comment by theprover97** [comment]
Thanks for your support @ethan-nelson . I will like to work on it, and will inform you incase I face any further problems. Thanks!!

**Comment by theprover97** [comment]
@ethan-nelson, I made changes in the required files for backend, but the response is still an error in setting contact details. Can you please tell me if I am missing some part?

**Comment by ethan-nelson** [comment]
could you post a screenshot @theprover97 or provide further information? alternatively, do you have the changes on a branch pushed to github so that i can look?

**Comment by theprover97** [comment]
I have not pushed any changes yet. Let me push them to a branch on my repo.

**Comment by theprover97** [comment]
I have made commits in the branch on my repo https://github.com/theprover97/tasking-manager . Please check them.

**Comment by xamanu** [comment]
@theprover97 Which branch? I can't find the new commits in your repo. Thanks!

**Comment by theprover97** [comment]
I have updated my repo. You can check the commits now.

**Comment by xamanu** [comment]
Thanks, @theprover97! I just checked it on latest developed and updated the branch here. It starts coming together, the UI already contains the behaviour as expected. There are some missing parts that I was able to spot:

* Database migrations are missing (these can be easily created with `python3 manage.py db revision --autogenerate`
* The text is not going through our `{{ 'translation pipeline ' | translate }}`. Please compare with the other form elements on the profile. I guess based on this we need a function to save the values, as they are going to be different in each language.

**Comment by xamanu** [comment]
This has been addressed within #1899

**Pull request closed without merging**
