### PR TITLE
Stop sending messages when tasks are validated

### PR DESCRIPTION
**Pull request by JesseWeinstein**
Fixes https://github.com/hotosm/tasking-manager/issues/635 by simply removing the entire feature for sending messages when a task is validated.

### CODE REVIEW

**Comment by bgirardot** [comment]
Hi @JesseWeinstein Thank you very much for the pull request.

We will not be removing the feature, but we will add a way to opt out of validation emails. But it is important for newer mappers to get feedback that their mapping has been validated. 

We will add a message to the automated email so folks know they can opt-out.

Since we have another way to address this issue, i am going to reluctantly close your pull request, my apologies. 

If you have any other ideas for contributions, the best thing is to open or comment on an existing issue with your plan or ideas for the fix or feature. That way you can get feedback on the approach first.

**Comment by JesseWeinstein** [comment]
That is completely fine -- I mostly wanted to make it just to move the discussion along. Is someone already working on the opt-out feature, or would it be useful for me to create a PR for that?

**Comment by bgirardot** [comment]
I think there is a pull request for the opt out right now ready to merge.

**Comment by JesseWeinstein** [comment]
I don't see any such PR in https://github.com/hotosm/tasking-manager/pulls -- do you remember what it's number might be?

**Comment by dakotabenjamin** [comment]
If you're referring to #1060 I just merged it into `develop`, and opened a PR into `master`. Once that is merged it will function as intended on the site.

**Pull request closed without merging**
