### PR TITLE
Add notification toasts and alerts for error/success messages in the management section

### PR DESCRIPTION
**Pull request by HelNershingThapa**
This pull request partially addresses issue #3424 of adding notification toasts to inform users of error/success messages in the management section of the app when interacting with APIs. The [react-hot-toast](https://react-hot-toast.com/) dependency has been added to display toasts. The toasts are displayed at the bottom left of the app for success messages in the following sub-sections: **_Projects, Organizations, Teams, Campaigns, Categories, and Licenses_**. Toasts are shown when entities are created, updated, or deleted successfully. On failure, the callout alert component will be displayed. The toast component is centralized for consistency across the app.

Changes Made:
- Added [react-hot-toast](https://react-hot-toast.com/) as a dependency to display toasts.
- Added notification toasts to the bottom left of the app for error/success messages in the management section of the app when interacting with APIs for the following sub-sections: Projects, Organizations, Teams, Campaigns, Categories, and Licenses. Toasts are displayed when entities are created, updated, or deleted. <br>
Some example toasts:
Screenshot from 2023-04-24 16-23-46Screenshot from 2023-04-24 16-23-59
Screenshot from 2023-04-24 16-24-08
Screenshot from 2023-04-24 16-24-26
- Updated tests to accommodate the changes wherever feasible. 
- Adds EntityError component that displays error messages in alerts for entity creation and updation failure.

In addition to the above changes, there were some SonarCloud duplication issues. To fix those, the following changes were made:

- Adds a new hook, useModifyMembers, to handle the logic for updating members and managers, reducing duplicate code.
- Refactors code to use a common function for handling network error responses.
- Refactors update functions for managers and members, using a common updateAffiliation() function and updating function calls and toast messages to be dynamic.
- Refactors entity updation functions for organizations, teams, campaigns, categories, and licenses to eliminate code duplication, using a reusable function called updateEntity().
- Fixes broken link when navigating to the categories list page after a category deletion.

### CODE REVIEW

**Review by Aadesh-Baral — COMMENTED** [review]
- Out of scope for this PR but lets also add a toast message while updating a user role and level in user management section, updating user info on user settings page and notification page.

- While there is an error during creating organisation another alert message is also shown alongside toast message. I feel showing 2 error messages are redundant here as both are displaying same information. Is this expected behavior?
image

- Same case if error occurs while creating campaign.
image

- Getting this error instead of toast with error message if project creation fails.
image

-  Add toast message while sending messages to all contributors of a project instead of alert as toast message is shown while sending messages to all members of a team.
image

**Comment by HelNershingThapa** [comment]
> Out of scope for this PR but lets also add a toast message while updating a user role and level in user management section, updating user info on user settings page and notification page.

Added the toast messages for the user role and mapper level update. 
> While there is an error during creating organisation another alert message is also shown alongside toast message. I feel showing 2 error messages are redundant here as both are displaying same information. Is this expected behavior?

Yes, it is the expected behavior. While implementing the toast messages, I hadn't given much thought to it. I went with the idea that the toast message is a generic message that provides feedback to the user about the success or failure of their action. In contrast, the alert message provides specific details about the error. However, I understand the concern, and we can review and decide on this implementation to determine if it can be improved.

> Getting this error instead of toast with error message if project creation fails.

haha nice catch. I discovered that the error is not being handled gracefully, resulting in the crash. While handling such errors is important, it's not within the scope of this pull request, which focuses on implementing toasts for C~~R~~UD operations for the entities in the management section. Nonetheless, I agree that we should handle these errors gracefully wherever possible, and I will create a separate issue to address this problem. 
> Add toast message while sending messages to all contributors of a project instead of alert as toast message is shown while sending messages to all members of a team.

Yes, we could add toast messages when messaging all contributors of the project. But, like you said, wouldn't that be redundant haha :P ? Up for discussion. cc @ramyaragupathy

**Review by d-rita — COMMENTED** [review]
Tested the creating, updating, and deleting of the different resources under the manage tab, i.e. projects, licences, categories, campaigns, teams, organisations. The toasts appear for the different actions undertaken which works as expected. 
However, as noted by previous reviewers, there is some redundancy with having a toast appear as well as an alert while showing the same thing, for example via project creation. 

I also noticed that after deleting a category, the user is redirected to a non-existent page instead of the categories list, i.e. is redirected to `/manage/interests` instead of `/manage/categories/`

**Comment by ramyaragupathy** [comment]
Per discussion today w/ @Aadesh-Baral @HelNershingThapa  :
* we will retain alert messages for team messaging
* use alert messages for failure scenarios under manage sections
* use toast messages for success scenarios under manager sections

**Review by Aadesh-Baral — APPROVED** [review]
LGTM

**Review by d-rita — APPROVED** [review]

**Pull request merged**
