### PR TITLE
Update docker dev setup and docs

### LINKED ISSUE #5997: Build issues with docker-compose
There's two slightly related bugs trying to build a docker container from the develop branch.

COPY failed: file not found in build context or excluded by .dockerignore: stat frontend: file does not exist
ERROR: Service 'frontend' failed to build : Build failed

If I remove frontend from .dockerignore, docker-compose still fails trying to build with:

Collecting PyYAML==6.0
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 1.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):

### LINKED ISSUE #6183: Improve docker to use alternate ports
Right now to run TM locally if requires both port 5432 and 80 to be open. If you do this on a system with both of these running already, the docker image won't work. Several other HOT projects support using alternate ports for local development.

### LINKED ISSUE #6232: Docker-compose fails to work
Neither docker-compose.override.yml and docker-compose.yml build a working image, there are a multitude of issues. This makes it difficult to self-host, or do development for developers not at HOT.

### PR DESCRIPTION
**Pull request by mahesh-naxa**
What this covers?

- Tasking manager db, backend and frontend services works from `docker compose up -d --build` without any hassles. closes #5997 
- `docker-compose.override.yml` is replaced with `docker-compose.override.sample.yml` which can be used to override any ports, volume mounts or other docker compose config. `docker-compose.override.yml` is now untracked through `.gitignore`. This should allow people to have their own setup. closes #6183 & closes #6232
- Updates to development [setup docs](https://github.com/hotosm/tasking-manager/blob/feat-dockerize/docs/developers/development-setup.md#docker).
-  Frontend or Backend service can be independently spawned. Also added [docs](https://github.com/hotosm/tasking-manager/blob/feat-dockerize/docs/developers/development-setup.md#frontend-only-deployment) for it.

What it Doesn't?

-  Existing `Dockerfile` has issues (optimization, build flow, security & optimizations) that's untouched.
-  `ghcr.io/hotosm/tasking-manager/backend:xxxx` image name is used for name sake only. No workflow or image exists.
-  Swagger support is tested by rebasing work by @kshitijrajsharma . https://github.com/hotosm/tasking-manager/tree/feature/swagger-ui-api . It works with `TM_APP_API_URL` set.

### CODE REVIEW

**Comment by robsavoye** [comment]
I get this error with this PR:

tm-migration-1  | PermissionError: [Errno 13] Permission denied: 'logs'
service "tm-migration" didn't complete successfully: exit 1

**Comment by robsavoye** [comment]
Part of my problem turned out to be related to the version of docker-compose. With the new version, this branch is much closer to working. The front end comes up, but the backend fails with this message:
tm-db-1         | 2024-03-12 04:09:27.604 UTC [181] FATAL:  role "-d" does not exist

**Comment by robsavoye** [comment]
Since I approved the PR that got swagger working, does this need to be updated to work with that ?

**Comment by robsavoye** [comment]
I get this now when testing this PR.

338.4 npm ERR! path /usr/src/app/node_modules/@sentry/cli
338.4 npm ERR! command failed
338.4 npm ERR! command sh -c -- node ./scripts/install.js
338.4 npm ERR! [sentry-cli] Downloading from https://downloads.sentry-cdn.com/sentry-cli/2.21.1/sentry-cli-Linux-x86_64
338.4 npm ERR! Error: EACCES: permission denied, mkdir '/root/.npm/sentry-cli'
338.4 
338.4 npm ERR! A complete log of this run can be found in:
338.4 npm ERR!     /root/.npm/_logs/2024-03-14T07_30_22_362Z-debug-0.log
--

**Comment by mahesh-naxa** [comment]
@robsavoye can you merge this.
I will cover issues with dockerfile (sonarcloud) in a seperate PR.

**Pull request merged**
