### PR TITLE
feat: fixed osm download destroy issue

### LINKED ISSUE #6345: [BUG] OSM download components crashes due to node version upgrade to 18
**Describe the bug**
Related: [Frontend dependency updates](https://github.com/hotosm/tasking-manager/pull/5721). 
On integrating the frontend dependency PR, The page crashes when we try to download osm data using newly integrated feature called osm download. 

**To Reproduce**
1. Go to 'project page of any project
2. Click on ' any file type to download osm data of that project '
3. See error

**Expected behavior**
The respective osm data should be downloaded. 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by varun2948**
## What type of PR is this? (check all applicable)

- [X] 🐛 Bug Fix

## Related Issue

- Fixes #6345 
- https://github.com/hotosm/tasking-manager/pull/5721

## Describe this PR
This PR fixes the crash issue on osm download component which was caused due to the react,node upgrade

## Screenshots
Issue:
image

After Fix :
image

## Review Guide

Notes for the reviewer. How to test this change?
1. Go into the Single Project Details.
2. Go Back to the projects lists.
3. Error Shows up.

## Checklist before requesting a review

- 📖 Read the Tasking Manager Contributing Guide: <https://github.com/hotosm/tasking-manager/blob/develop/docs/developers/contributing.md>
- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

### CODE REVIEW

**Comment by varun2948** [comment]
@ramyaragupathy we currently have issue on CircleCI because of the node version upgrade and need a change on the CIRCLECI config and i just consult with @mahesh-naxa  and he suggested to do multiple changes on CircleCI config for upgrading the node version on CircleCI which he would be doing. so might have to wait for him to fix this 
Cc: @royallsilwallz @manjitapandey

**Comment by mahesh-naxa** [comment]
Looks like there are two checks failing. 
1. **Build & Push Image**: This is strictly a permission issue related to git-hub package repository.
```
ERROR: denied: installation not allowed to Write organization package
Error: buildx failed with: ERROR: denied: installation not allowed to Write organization package
```
passing this down to @eternaltyro 

2. **frontend-code-test**: I think the original PR for dependency update to `node 18` didn't have circleci config updated to use the newer `node v18` . 

will update those in a seperate PR ASAP.

**Comment by mahesh-naxa** [comment]
cc: @ramyaragupathy @varun2948

**Comment by mahesh-naxa** [comment]
Further info https://github.com/hotosm/tasking-manager/pull/6397

**Comment by varun2948** [comment]
@ramyaragupathy @royallsilwallz @manjitapandey everything is passed except the two that DK had already mentioned will be failed anyways so it is good to go i guess.

**Review by royallsilwallz — APPROVED** [review]

**Review by manjitapandey — APPROVED** [review]

**Comment by ramyaragupathy** [comment]
> frontend-code-test: I think the original PR for dependency update to node 18 didn't have circleci config updated to use the newer node v18 .
@mahesh-naxa thanks for capturing the details clearly. Is the circle CI config update directly related to https://github.com/hotosm/tasking-manager/issues/6405?

**Comment by mahesh-naxa** [comment]
@ramyaragupathy I have updated circleci with the newer node versions, this one is specific to this PR, as this PR is generated from a fork by @varun2948. 
```
#31 ERROR: denied: installation not allowed to Write organization package
```
Its an an auth issue where packages are not allowed to be pushed to github container registry from a forked repo.
(also its safe to ignore github actions related workflows for building docker images, as they are still being worked on, and is seperate from CircleCI's jobs.)

**Pull request merged**
