### PR TITLE
Add loader to iD editor

### LINKED ISSUE #2680: Add a loading indicator while iD is loading
While iD is loading we could show a loading indicator instead of a blank area.

### PR DESCRIPTION
**Pull request by vegeta999**
Closes #2680 
Added preloader to the iD editor.
Further enhancements:
1. We can give the `transition` property a thought to avoid sudden disappearance of the loader.
2. This is similar to the loader I suggested to add to login process, so if in future we add it then these files should be edited to avoid redundancy, mentioning it here #2371 .

@willemarcel please review !

### CODE REVIEW

**Comment by xamanu** [comment]
@willemarcel has this been fixed with #2753?

**Comment by ritvikjain99** [comment]
@xamanu I'll have to do some changes in this to import component made in the PR you mentioned, I'll get it done today !

**Comment by ritvikjain99** [comment]
I have incorporated the preloader of 2753 to id editor, works fine !

**Comment by ramyaragupathy** [comment]
stale

**Pull request closed without merging**
