### PR TITLE
Fix overlapping scrollbar bug 

### LINKED ISSUE #5893: [BUG] Hidden Menus due to Overlapping Horizontal Scrollbar on Project Detail Page
**Describe the bug**
On the project detail page, a convenient shortcut menu is provided at the bottom. However, an issue arises when the number of menu items exceeds the available space, prompting the appearance of a right arrow button to access additional menus. Unfortunately, clicking this arrow button triggers the appearance of a horizontal scrollbar, which covers the menus that should be visible.

**To Reproduce**
1. Navigate to the project detail page.
2. Scroll down to the bottom of the page where the shortcut menus are located.
3. Observe that the available space may be insufficient to display all menu items.
4. Notice the appearance of a right arrow button to access hidden menus.
5. Click on the right arrow button.

**Expected behavior**
Upon clicking the right arrow button, the menus should not be hidden by the scrollbar.

**Screenshots**
ezgif com-video-to-gif(3)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox

### PR DESCRIPTION
**Pull request by Finay**
My previous edit had an error. I updated the styling to the CamelCase version that should work. 

Closes #5893

### CODE REVIEW

**Review by HelNershingThapa — CHANGES_REQUESTED** [review]
Hi @Finay, thanks for your pull request! I appreciate your contribution to the project. However, I have concerns about the changes you made. It appears that your modification disables horizontal scrolling over the container, which could impact user experience. Please review your changes and see if you can retain the original scrolling behavior while incorporating your improvements.

**Comment by petya-kangalova** [comment]
@Finay  thank you very much for you willingness to contribute to the Tasking Manager repo.  We are excited to have you here! Would you be able to make amendments to your PR as @HelNershingThapa  suggested by early next week? We will then review and move ahead with merging/approving.

**Comment by Finay** [comment]
Hi, I looked into it and realized making the scrollbar thinner was an option. This gave a lot more room to access the links and keeps the scrollbar. I hope this works.

**Comment by HelNershingThapa** [comment]
@Finay Thanks for your effort, but we ultimately want to hide the scrollbar while supporting horizontal scrolling. Could you please revise your solution accordingly? Thanks!

**Comment by Finay** [comment]
I see, in which case [my previous edit](https://github.com/hotosm/tasking-manager/pull/5898/commits/dad49cf87565ffa7a813051fcbfd2afe450838f8) successfully removed the scroll bar while maintaining horizontal scrolling using the arrows.

**Comment by HelNershingThapa** [comment]
Yes, it did. However, it inadvertently disabled the desired horizontal scrolling behavior. Specifically, Shift + mouse wheel scroll, which also scrolls the container, was affected.

**Comment by HelNershingThapa** [comment]
Hi @Finay! It's been some time since there has been an update on this pull request. Could you please provide an update on the progress?

**Comment by Finay** [comment]
I don't know how to fix it the way you want with my current abilities. I'm sorry but I doubt I'll be able to help.

**Comment by HelNershingThapa** [comment]
Thank you for your response and honesty about your current abilities. I appreciate your efforts and the time you've already invested in this pull request. It's completely understandable that certain technical challenges may arise.

Thank you once again for your contribution. It's valued and respected.

**Comment by ramyaragupathy** [comment]
@HelNershingThapa will be handling this in a different PR

**Pull request closed without merging**
