### PR TITLE
Fix some backend endpoints for #2047 

### PR DESCRIPTION
**Pull request by fitoria**
Fix annotations endpoint return codes
Fixes return values on project comments endpoint

### CODE REVIEW

**Comment by willemarcel** [comment]
@fitoria It's missing to apply the fix to `/api/v2/projects/{project_id}/activities/`

**Comment by willemarcel** [comment]
The annotation and comments endpoint worked well!

**Comment by xamanu** [comment]
@willemarcel, can you please check on the frontend tests here. And is there anything missing on the backend side - or were you able to add it already?

**Comment by willemarcel** [comment]
@ramyaragupathy when you have some time, could you review it too and fix the missing items?

**Comment by xamanu** [comment]
Hey @joaovitor3, many thanks for taking this on in the other branch/PR. Is this being PR being superseeded by https://github.com/hotosm/tasking-manager/pull/2333? Then I would close here and we make sure your's gets in soon.

**Comment by joaovitor3** [comment]
I applied all the changes made by @fittoria in my branch, so I think it's ok to close this PR.

**Pull request closed without merging**
