### PR TITLE
Fixes issue with angularjs and service loads

### PR DESCRIPTION
**Pull request by fitoria**
Fixes error angular.js:15567 Error: [$injector:unpr] Unknown provider: mappingIssueServiceProvider <- mappingIssueService <- projectController

### CODE REVIEW

**Comment by xamanu** [comment]
I wasn't able to reproduce the error. But perhaps others run into this one, too.

**Comment by fitoria** [comment]
Steps to reproduce on develop

- Go to: /project/<project_id>
 it will be like: 

I'm running it on my environment locally, even tried to remove and reinstall node packages.

image

**Comment by xamanu** [comment]
Sorry, i can't reproduce. Do you still face this issue @fitoria ?

**Comment by xamanu** [comment]
Closing due to inactivity. Please reopen, if problem still occurs.

**Pull request closed without merging**
