### PR TITLE
Add project due date

### LINKED ISSUE #3132: Update fields according to Organised Editing Guidelines
This issue is part of the GSoC '20 project, described with more details in this [issue](https://github.com/hotosm/tasking-manager/issues/1373).

Some fields need to be added to the Tasking Manager to fit the [Organised Editing Guidelines](https://wiki.osmfoundation.org/wiki/Organised_Editing_Guidelines). There will be a checklist with all fields to be added or updated. When these fields are added or updated each item from the checklist will be ticked.

The list of fields is present in the list below:
- Organisation
    - [ ] Description
- Project
    - [ ] Due date
    - For the next two fields, maybe an External Sources section could be created in the project edit page  
        - [ ] Any non-standard tools and data sources used, and their usage conditions
        - [ ] Links where the community can access any non-standard tools or data sources
    - For the next two fields, maybe a Validation / Metrics section could be created in the project edit page
        - [ ] Quality Assurance
        - [ ] Metrics
- User
  - [ ] Allow people to select if they want to be identified

### PR DESCRIPTION
**Pull request by joaovitor3**
Closes #3132 

This Pull Request is part of the [issue of adding and updating fields according to Organised Editing Guidelines](https://github.com/hotosm/tasking-manager/issues/3132)

Add project `due_date` field in frontend.

### CODE REVIEW

**Comment by willemarcel** [comment]
@joaovitor3 try also to format the input field with the same height of the text input fields.

**Comment by joaovitor3** [comment]
Thanks for the review!
I will update the PR with these changes

**Comment by joaovitor3** [comment]
@willemarcel, Just updated the PR with the changes requested.

**Review by xamanu — COMMENTED** [review]
This looks good to me.

**Comment by joaovitor3** [comment]
Just rebased the branch, could you review it please?

**Pull request merged**
