### PR TITLE
Multiple fixes to python local tests

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
This PR includes implementations and test modifications with the purpose of running tests within a local setup. Each of the changes are documented and explained on issue #1491 

**Note.** The assigned reviewer **must** verify this PR using their own setup of Tasking Manager or with docker.

```python -m unittest discover tests/server/```

### CODE REVIEW

**Comment by xamanu** [comment]
Thanks @JorgeMartinezG! I went over code and tested it. I worked well with the Docker setup, However for it to run the tests properly I had to fix in the `config.py ` the configuration path in line 10. I added a commit to it and pushed here. Feel free to squash commit messages on merge.

**Comment by JorgeMartinezG** [comment]
@xamanu history has been rebased in order to keep a single commit.

**Comment by ramyaragupathy** [comment]
Per chat w/ @JorgeMartinezG - this might be due to version mismatch in postgis in both our machines. I want to verify the version information from our server and then set up my test environment accordingly. Working w/ @arunasank to get this info from our server boxes.

**Comment by ramyaragupathy** [comment]
Ran this w/ docker setup to replicate server env. Noting a couple of issues - 
- one related to env variables and how it defaults to specific values that interrupts with the DB connection. Ticketing this separately after confirming w/ @xamanu and @JorgeMartinezG 
- second the DB upgrade did not get through well, that is it never ended even after an hour or so.
Again need to double check on a different env

**Comment by ramyaragupathy** [comment]
> Tested and works fine. Ran into similar issues with the postgis version, as @ramyaragupathy, but I think these should not stop this from going in.

Agree @xamanu - As such I don't see any issues in the code flow and any docker related issues I will branch out discussion in a new ticket. We're good to hit 🍏

**Pull request merged**
