### PR TITLE
Change email sending to only message verified users

### LINKED ISSUE #3498: Check if email is verified before sending messages
Per chat w/ @willemarcel and user requests, it is necessary to check if email is verified before sending any message notifications to the user

### PR DESCRIPTION
**Pull request by teymour-aldridge**
Not sure if this covers it (more places might need to be updated).

This should fix #3498.

### CODE REVIEW

**Comment by teymour-aldridge** [comment]
Hi!
Does anyone have time to review this patch?

**Comment by willemarcel** [comment]
Hi @teymour-aldridge ! I'll be reviewing it in the next few days. Thanks for you collaboration!

**Review by willemarcel — APPROVED** [review]
@teymour-aldridge sorry for the delay! Perfect change. Thank you very much!

**Comment by teymour-aldridge** [comment]
No problem!

**Pull request merged**
