### PR TITLE
Project stats endpoint related

### PR DESCRIPTION
**Pull request by ramyaragupathy**
### /api/v1/stats/project/{project_id}

_[Sample payload](https://gist.github.com/ramyaragupathy/3e0b535170a97ddc4a3df04c83001f93)_

- [x] Total Mappers
- [x] Total Tasks
- [x] List all Changeset Comments
- [x] Percent of bad Imagery
- [x] Total Comments
- [x] Entities to Map
- [x] Due Date for project completion
- [x] Project Author/created by
- [x] Project Priority
- [x] mapperLevelEnforced
- [x] validatorLevelEnforced
- [x] Average mapping  time
- [x] Average validation time
- [x] Total mapping time
- [x] Total validation time
- [x] Total time spent on the project

### /api/v1/stats/project/{project_id}/activity

_[Sample Payload](https://gist.github.com/ramyaragupathy/4d91b1b64606e885ed2e1e2376d52ba1)_

- [x] Include a task id in activity stub

### /api/v1/stats/project/{project_id}/contributions

_[Sample Payload](https://gist.github.com/ramyaragupathy/f50e37ceaac49e0e23574bc5250635c0)_

For each user add:
- [x] Time spent mapping
- [x] Time spent validating
- [x] Total Time spent

### CODE REVIEW

**Comment by xamanu** [comment]
@ramyaragupathy this causes a conflict while rebasing on `develop`. Can you rebase please?

**Comment by ramyaragupathy** [comment]
Done @xamanu

**Comment by xamanu** [comment]
@ramyaragupathy this seems to have some conflicts with the other stats PRs that are already in develop.

**Comment by ramyaragupathy** [comment]
@xamanu - after resolving the merge conflicts and testing  the change locally, found that [project activity endpoint](https://tasks.hotosm.org/api-docs/swagger-ui/index.html?url=https://tasks.hotosm.org/api/docs#!/stats/get_api_v1_stats_project_project_id_activity) fails with 

```
{
  "error": "User GET - unhandled error: 'result' object has no attribute 'id'"
}
```

Updated the query to fetch task history ids. However I am not sure which pull request introduced this change to the `develop` branch. All my changes works fine.

**Comment by xamanu** [comment]
Perfect. Works now. Thanks!

**Pull request merged**
