### PR TITLE
Update Dockerfile 

### PR DESCRIPTION
**Pull request by xamanu**
Update Dockerfile:

* to Debian stable (Stretch)
* some smaller typo changes for better readability
* Consolidate port to `5000`
* Prepare for development setup use of the container
* Add `.dockerignore`
* Use `/usr/src/app` instead of `/src`

### CODE REVIEW

**Comment by arunasank** [comment]
@xamanu, thanks for this PR! With the move to Cloudformation, we'll not be needing this file anymore for our deploys. Do you think we should still be keeping the file around?

**Comment by xamanu** [comment]
It is still going to be nice to provide a Dockerfile of the Tasking Manager for an easy testing and deployment. Maybe we want to move it into the `devops` folder, once we stop using it directly.

**Comment by xamanu** [comment]
By today, the python images based on Debian Jessie are not building anymore. This means that people building the Tasking Manager on Docker will not be able to do so.

Raising the priority here to critical.

**Comment by xamanu** [comment]
Changed port back to `8000`, thus not to introduce any breaking changes

**Comment by ethan-nelson** [comment]
trying to determine why #1394 builds while this one does not

**Comment by xamanu** [comment]
Because #1394 was rebased on `develop` after #1413 went it. This one hasn't been rebased, but was now and builds.

**Comment by xamanu** [comment]
I'm going to reroll this PR.

**Pull request closed without merging**
