### PR TITLE
Activity & Stats page enhancements

### LINKED ISSUE #1360: ready2go: project activity sorting and filtering, with task links
> Note: this feature has been implemented, but not yet submitted as a PR

* Allow sorting of project activity by date
* Allow filtering of project activity by action and username
* Allow filtering by latest action per task
* Include link to task

activity_all

activity_invalidated_latest

### LINKED ISSUE #1384: ready2go: cross-project All Activity page
> Note: this feature has been implemented, but not yet submitted as a PR

* Add new All Activity page showing activity across projects (like #1360 offers for a single project)
* Allow filtering of activity by project name
* Restricted to validators, project managers, and admins
* New page is accessible via top-nav dropdown menu

all_activity

### PR DESCRIPTION
**Pull request by nrotstan**
* Closes #1360, Closes #1384 

* Add additional headline stats for the major task statuses in the
Stats section

* Add new Status Overview table showing the latest status of each task
in the project with sorting and filtering capability

* Add new Status Overview table showing the latest status of each task
in the project with sorting and filtering capability

* Enhance Last Activity table to include sorting and filtering
capability

* Support cross-projects view of Activity & Stats for all published
projects by way of a new "All Activity" option in top-nav dropdown menu

* Support CSV export of summary stats and status overview

* Fix various stats-collection issues and inconsistencies

* Change task invalidation to preserve mapper and invalidator rather than clearing them (note that this only applies to invalidations going forward and does not retroactively set values on existing invalidated tasks)

### CODE REVIEW

**Comment by xamanu** [comment]
This is very cool! Just checked it and found that there is the data about mapper and validator missing on invalidated tasks that have been invalidated before the this PR got applied (the top one was afterwards):

image

**Comment by nrotstan** [comment]
Right, I tried to allude to that in the last bullet point of the PR description, but I may not have been very clear.

It would be possible to create a migration that looks in the task history to determine who the latest mapper and validator were for tasks in an invalidated status, and set that data on those tasks so that the mapper and validator show up properly in the new Status Overview table. I just wasn't sure how long those tasks tend to remain in an invalidated status, as once they are addressed they will no longer be problematic (and invalidations going forward are fine, as you saw).

**Comment by xamanu** [comment]
I think it would be great to have this migration, as on volunteer projects, we don't have always the "invalidated" state being tackled as fast as it should. Having the new tasks status table will help project managers also to improve the data and manage the volunteers of projects that started in the past.

**Comment by nrotstan** [comment]
@xamanu Migration added.

**Comment by xamanu** [comment]
Thanks, @nrotstan. I just checked after rebasing against latest `develop` and adjusting the revision (latest head) for the alembic migrations. When running the migration I get the following error:

```
INFO  [alembic.runtime.migration] Running upgrade 0d47c10c8a66 -> 6ae2a7d54b50, empty message
Traceback (most recent call last):
  File "manage.py", line 59, in <module>
    manager.run()
  File "/usr/local/lib/python3.7/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.7/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.7/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_migrate/__init__.py", line 247, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.7/dist-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/dist-packages/alembic/script/base.py", line 421, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python3.7/dist-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/dist-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 99, in <module>
    run_migrations_online()
  File "migrations/env.py", line 92, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.7/dist-packages/alembic/runtime/environment.py", line 817, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.7/dist-packages/alembic/runtime/migration.py", line 329, in run_migrations
    step.migration_fn(**kw)
  File "/home/user/Code/HOT/tasking-manager/migrations/versions/6ae2a7d54b50_.py", line 33, in upgrade
    mapped_by = state_change_user_id(conn, task, "MAPPED")
  File "/home/user/Code/HOT/tasking-manager/migrations/versions/6ae2a7d54b50_.py", line 23, in state_change_user_id
    return conn.execute(query).fetchone()['user_id']
TypeError: <flask_script.commands.Command object at 0x7f3281bc62b0>: 'NoneType' object is not subscriptable
```

**Comment by nrotstan** [comment]
@xamanu I rebased and squashed, and fixed the migration to be more resilient and skip a task if the task history is missing or not as expected for that task.

**Comment by Vaomatua** [comment]
Will the improved Activity & Stats page show the number of tiles in a given project?

**Comment by xamanu** [comment]
Rerolled this on latest `develop` and database migrations, with the goal to get it into the TM before the feature freeze end of this week. Unfortunately when using it with real data I get a:

```
psycopg2.OperationalError: index row size 4816 exceeds maximum 2712 for index "idx_action_action_text_composite"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
```

**Comment by xamanu** [comment]
Rerolling this in a [separate branch](https://github.com/hotosm/tasking-manager/tree/feature/stats-and-activity-tables) on latest develop and with the goal to integrate better the backend. Leaving this open until a new PR can be created.

**Comment by tawirth** [comment]
Hi All - I see that my original issue is not implemented yet (from a previous issue but I was directed to this one). This would be to show a link to the tasks that have been recently mapped/validated in the "Activity and Stats" page - exactly like it now shows when someone adds a comment.  Seeing how this hasn't happened, a work around could be to automatically add a comment to every completed/validated task such as the project/task number or the the username of the person marking it completed/validated.  That way, we can quickly identify new mappers right after they start mapping to offer guidance and improve their mapping, rather than have them continue making mistakes that validators have to clean up.  If this is more appropriate to start a new issue, please advise. Thank You!

**Comment by willemarcel** [comment]
> This would be to show a link to the tasks that have been recently mapped/validated

We have this behaviour on TM4, check: https://tm4.hotosm.org/projects/6/tasks

**Comment by tawirth** [comment]
> 
> 
> > This would be to show a link to the tasks that have been recently mapped/validated
Yes that would work. When will TM4 be online?

> @tawirth We have this behaviour on TM4, check: https://tm4.hotosm.org/projects/6/tasks

**Pull request closed without merging**
