### PR TITLE
Include abbreviated response for teams and orgs endpoints

### LINKED ISSUE #3177: Disable members listing on the teams and organisations
To improve performance the following changes could be made in

- Disable members, projects in `/api/v2/organisations/`
- Disable member  in` /api/v2/teams`

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
Closes #3177 . Included a request parameter **abbreviated**. When set to True, hides information according to the given endpoint.

**/v2/organisations/:** Hides managers for each organization.
**/v2/organisations/<id>:** Hides managers, teams and projects associated to the organization.
**/v2/teams/:** Hides team members.
**/v2/teams/<id>:** Hides team members, team projects and organization projects.

### CODE REVIEW

**Comment by willemarcel** [comment]
In chat with @ramyaragupathy, we thought about renaming the query param to `omitManagerList` on the organisations endpoints and to `omitMemberList` on the teams, in order to make it more expressive. What do you think?

**Comment by JorgeMartinezG** [comment]
you mean only to /v2/teams/ and /v2/organisations? For these cases, I agree.

**Comment by willemarcel** [comment]
> you mean only to /v2/teams/ and /v2/organisations? For these cases, I agree.

yes, rename only on those endpoints

**Comment by JorgeMartinezG** [comment]
@willemarcel @ramyaragupathy implemented changes and remove the project list in OrganisationsRestAPI

**Pull request merged**
