### PR TITLE
Show 404 error on using in-valid message id.

### PR DESCRIPTION
**Pull request by uwaiszaki**
The Pr handles
1-> Invalid message id.
2-> Any other error loading the message. And
3-> Add error status in getMessage service.

### CODE REVIEW

**Comment by xamanu** [comment]
Thanks for this PR! I'm wondering whether we wanted to show a `404` here, or whether it would be more convenient to move people to login and redirect them afterwards to the url they were trying to hit at. In case it is not their account's message, I would present an `403`. What to you think?

**Comment by uwaiszaki** [comment]
@xamanu The redirecting part is already working if they are not logged in. In case they are logged in
, I think for using an invalid message id we should show "not found" instead of showing "not allowed or blocked".

**Comment by uwaiszaki** [comment]
@xamanu @JorgeMartinezG I have implemented the requested changes. Please give ur reviews

**Comment by JorgeMartinezG** [comment]
Thank you again for this contribution @uwaiszaki. I found this approach correct. @xamanu do you have additional opinions?

**Comment by uwaiszaki** [comment]
@xamanu It's working fine with my setup. Can u please check it again.

**Comment by uwaiszaki** [comment]
tmpull1400

**Pull request merged**
