### PR TITLE
Get production instances back up to 3 min

### PR DESCRIPTION
**Pull request by dakotabenjamin**
* Infrastructure: Increase the number of production instances back up to 3 min/12 max. (cherry picked from #1657)

### CODE REVIEW

**Comment by xamanu** [comment]
Let's use this hotfix release to fix the issues on the invalidation list (https://github.com/hotosm/tasking-manager/issues/1685) and the disappearing projects (https://github.com/hotosm/tasking-manager/issues/1687).

**Comment by ramyaragupathy** [comment]
We've lost 36 projects in total between Jun 6 - Jun 10. From talking to different project managers and admins - A majority of these projects seems to have been deleted by some action initiated outside the team of actual project owners (project author + people associated with the project).  _[Complete list of projects deleted](https://docs.google.com/spreadsheets/d/1TSptLmzulyYQ0YyGfCZP3x1vlzk2WcL03ogorYyKL2A/edit#gid=0)_

**Immediate Fix:**
- Limit project delete activity to the current project owner and TM Admins

**Long term solutions:**
- Maintain detailed DB transaction logs 
- Maintain and enable quick access to server logs
- Maintain project history on our DB similar to task history

**Comment by xamanu** [comment]
A note: In addition we should check how to bring back the deleted projects.

**Comment by ramyaragupathy** [comment]
Just checked our server logs with support from @dakotabenjamin - Couldn't find any entry related to the affected projects

**Comment by xamanu** [comment]
This became bigger than expected and it was worked on in a different branch and PRs, see the linked issues.

Lets tackle here the initial purpose of getting the production instance back up to 3 min. @dakotabenjamin can you please rebase and check on the conflicts? Thanks.

**Pull request closed without merging**
