### PR TITLE
Add more homepage stats

### PR DESCRIPTION
**Pull request by sunidhiraheja**
This PR focuses on the list of stats proposed in #1147 for the homepage section.

> Homepage
> - [x] Mappers online
> - [x] Tasks mapped
> - [ ] Tasks validated
> - [x] Total mappers
> - [ ] Total number of users who validate
> - [ ] Total area mapped and validated
> - [ ] Average task completion time
> - [ ] Number of projects by organization
> - [ ] Enable querying by date

- Added tasks validated
- Added total number of users who validate
- Added number of projects by organization

### CODE REVIEW

**Comment by sunidhiraheja** [comment]
1. What should the structure of the DTO look like for number of projects by organization?
Right now, I'm just adding more keys in the DTO for each metric.

2. How should I calculate the area of a `Geometry('MULTIPOLYGON', srid=4326)` type?

**Comment by ethan-nelson** [comment]
Is the goal to list the number of projects per organization tag? We could do `organizations = ListType(ModelType(OrganizationStatsDTO))` in the stats DTO, where `OrganizationStatsDTO` is another DTO with one component `projectscreated = IntegerType()` feeding the number of projects. This would allow us to eventually include other stats broken down by organization (if desired).

**Comment by ethan-nelson** [comment]
For the area, I'm still playing around with things locally when I can and I haven't been able to replicate the error where it's just printing the function/class. Perhaps others can chime in.

**Comment by smit1678** [comment]
> Is the goal to list the number of projects per organization tag? We could do organizations = ListType(ModelType(OrganizationStatsDTO)) in the stats DTO, where OrganizationStatsDTO is another DTO with one component projectscreated = IntegerType() feeding the number of projects. This would allow us to eventually include other stats broken down by organization (if desired).

@ethan-nelson Yes, the goal is to list the number of projects per organization tag but then also look to expand upon that later. Having the other stats broken down by organization would be 👍

**Comment by ethan-nelson** [comment]
I am on travel but will have this reviewed Monday evening!

**Comment by ramyaragupathy** [comment]
- [x] Mappers online
 - [x] Tasks mapped
 - [x] Tasks validated
 - [x] Total mappers
 - [x] Total number of users who validate
 - [x] Number of projects by organization
 - [ ] Total area mapped and validated
 - [ ] Average task completion time
 - [ ] Enable querying by date
--------
Following fields are retrurned for home page stats. Are we looking to include area, average task completion time & query by date as well in this PR?
```
    "mappersOnline": 104,
    "tasksMapped": 1650343,
    "tasksValidated": 816412,
    "totalMappers": 137720,
    "totalValidators": 8590,
    "organizations": [
        {
            "tag": "Abt Associates",
            "projectsCreated": 1
        },
        {
            "tag": "akros",
            "projectsCreated": 7
        }
....
```

**Comment by ramyaragupathy** [comment]
Per slack convo since the memory issues are resolved and the rest of the changes looks good, suggest let's keep the following items in a separate PR:
 - [ ] Total area mapped and validated
 - [ ] Average task completion time
 - [ ] Enable querying by date

**Comment by ethan-nelson** [comment]
Thank you for your contributions @sunidhiraheja ! 

I went ahead and removed the commented out code, but it is still available if you refer to the commit. I'm also pasting it here just for archival purposes:

```
        # lock_times = db.session.query(TaskHistory.action_text)\
        #     .filter(Task.task_status.in_((TaskStatus.MAPPED.value, TaskStatus.VALIDATED.value)))\
        #     .filter(TaskHistory.action.in_(("LOCKED_FOR_MAPPING", "LOCKED_FOR_VALIDATION")))\
        #     .filter(Task.id == TaskHistory.task_id)\
        #     .all()
        # task_count = Task.query.filter(Task.task_status.in_((TaskStatus.MAPPED.value, TaskStatus.VALIDATED.value)))\
        #     .count()
        # total_time_spent = datetime.datetime.fromtimestamp(0)
        # for t in lock_times:
        #     duration = dateutil.parser.parse(t[0])
        #     total_time_spent += datetime.timedelta(hours=duration.hour,
        #                                            minutes=duration.minute,
        #                                            seconds=duration.second,
        #                                            microseconds=duration.microsecond)
        # dto.avg_completion_time = total_time_spent.timestamp() / task_count
```

**Pull request merged**
