### PR TITLE
Fixes to the scripts and docs on development setup with docker

### PR DESCRIPTION
**Pull request by bshankar**
- [x] 📝 Documentation
- [x] 🤖 Build or CI

## Describe this PR

1. `tm-frontend` doesn't build with `npm install`. Use `yarn` instead in the docker build script.
2. Provide a default environment to compose using `--env-file tasking-manager.env`. Otherwise the backend doesn't run.
3. The redirect URI shouldn't have a `/` at the end.

## Review Guide

Run `docker compose --env-file tasking-manager.env up -d` and open `127.0.0.1:3000` in a browser and login.

### CODE REVIEW

**Review by mahesh-naxa — APPROVED** [review]
Thanks for pointing out `/` in the redirect url.

**Comment by mahesh-naxa** [comment]
@bshankar let me get back to you soon, on failing of `backend-functional-tests`, it just could be the CI or Test issue. i don't believe it originated from this PR.

**Comment by bshankar** [comment]
> @bshankar let me get back to you soon, on failing of `backend-functional-tests`, it just could be the CI or Test issue. i don't believe it originated from this PR.

Thank you @mahesh-naxa.

I checked the [test logs](https://circleci.com/api/v1.1/project/github/hotosm/tasking-manager/23120/output/113/0?file=true&allocation-id=667babe26fc2947d7bbc8a1f-0-build%2FABCDEFGH). I believe its because of a 403 response from nominatim.openstreetmap.org and unrelated to this PR.

**Comment by mahesh-naxa** [comment]
> > @bshankar let me get back to you soon, on failing of `backend-functional-tests`, it just could be the CI or Test issue. i don't believe it originated from this PR.
> 
> Thank you @mahesh-naxa.
> 
> I checked the [test logs](https://circleci.com/api/v1.1/project/github/hotosm/tasking-manager/23120/output/113/0?file=true&allocation-id=667babe26fc2947d7bbc8a1f-0-build%2FABCDEFGH). I believe its because of a 403 response from nominatim.openstreetmap.org and unrelated to this PR.

Yeah seems like nominatim.opensteetmap.org have some restriction enforced as mentioned here: https://operations.osmfoundation.org/policies/nominatim/

This PR LGTM.

**Comment by ramyaragupathy** [comment]
@bshankar - can you please resolve the conflicts so that we merge it? Sorry about the delay, missed noticing this earlier

cc @dakotabenjamin @mahesh-naxa

**Comment by ramyaragupathy** [comment]
All the changes from this PR were merged through https://github.com/hotosm/tasking-manager/pull/6479 - we're closing here

cc @bshankar

**Pull request closed without merging**
