### PR TITLE
User validator role request feature

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
This PR closes issue #1608. This feature consists of 4 endpoints.

1. POST api/v1/validator. To create a database record with information from the user validator form request http://bit.ly/HOTValidators
```
{
	"reason": "I want to be a validator",
	"reviewed_howto": true,
	"read_learnosm": false,
	"read_code_conduct": true,
	"agreed_interactions": true,
	"agreed_osmdata": false
}
```

2. PUT api/v1/validator **admins only**:To update information from admin response
```
{
	"role_request_id": 5,
	"response_reason": "Good to go",
	"status": "ACCEPT" #DENY
}
```

3. GET api/v1/validator/id - To get status of validator role request form.
4. DELETE api/v1/validator/id - To delete a validator role request form.

### CODE REVIEW

**Comment by xamanu** [comment]
Rerolled on latest `develop` and alembic db version.

**Comment by JorgeMartinezG** [comment]
Implemented requested changes and rebased with latest develop including migrations 👍

**Comment by xamanu** [comment]
Needs to be revisisted after the frontend flow regarding teams and organizations.

**Comment by xamanu** [comment]
With teams and organisations this will work differently. Closing here.

**Pull request closed without merging**
