### PR TITLE
Validation and welcome email template text fix up

### PR DESCRIPTION
**Pull request by bgirardot**
The original text was someone confusing, this change makes it clear it is an automated message and there might be more feedback coming. And improves the welcome letter text.

### CODE REVIEW

**Comment by bgirardot** [comment]
@ethan-nelson This is a really simple fix to improve the text and formatting. I tested it locally and it worked as expected. if you could merge it into develop at your convenience please

**Comment by pgiraud** [comment]
@bgirardot what happens if you don't put any `br` tags and replace them with empty lines?

**Comment by bgirardot** [comment]
I think just double spacing does not work and they all run together into one line.

**Comment by bgirardot** [comment]
@pgiraud , if you want to merge it into develop that would be good too. You are welcome to merge in anything to develop any time.

I know ethan is going to be unavailable next week so could I ask you to help with merging feature branches off of forks into develop this coming week?

**Pull request merged**
