### PR TITLE
Restrict editor programs for mapping and validation stages

### PR DESCRIPTION
**Pull request by xamanu**
Rerolling the PR #1421 of @zlavergne on a local branch (to ease up collaboration) and rebased on latest `develop` resolving some minor conflicts.

> Restrict editor programs for mapping and validation stages
> 
> >**This PR includes a db migration**
> 
> Related Issue: #893
> 
> * Added list of editors in the `Settings` menu of a project-edit page where a project manager can select permitted editors for each editing stage 
> Screen Shot 2019-03-21 at 10 37 50 AM
> 
> * Updated the editor dropdown for to populate only with the permitted editors
> Screen Shot 2019-03-25 at 12 28 35 PM

### CODE REVIEW

**Comment by xamanu** [comment]
Thanks for this PR, @zlavergne! Unfortunately I get an error on migrations already.

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 824268a7a675 -> 215392b11b0e, empty message
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "idx_project_info composite" already exists
```

The `idx_project_info` relation seems to be around [some time](https://github.com/hotosm/tasking-manager/blob/master/migrations/versions/8aa8f8d6a0c3_.py).

**Comment by zlavergne** [comment]
@xamanu Just pushed a fix for the alembic versions. Thanks for catching it!

**Comment by xamanu** [comment]
I tested today this PR, but as I rerolled it I was not able to give it an approved review. It works fine and code looks good to me. @ethan-nelson may I ask you for your review before we merge that in? Thank you!

**Comment by zlavergne** [comment]
@ethan-nelson thanks for the review. 

I'm not sure how [this](https://github.com/hotosm/tasking-manager/blob/a70db5b22145e11e6ab332ec25e2a5fe66cfa33a/migrations/versions/d01c4ceddeb4_.py#L21-L22) got lost in the PR but I put it back in there.

**Comment by xamanu** [comment]
I would like to have a final review and thumbs up from either @ethan-nelson or @ramyaragupathy to merge this in. Thanks!

**Comment by ethan-nelson** [comment]
I will take a look tomorrow!

**Comment by xamanu** [comment]
@JorgeMartinezG encountered some errors yesterday when running this PR from a [fresh database](https://github.com/hotosm/tasking-manager/blob/develop/docs/setup-development.md#create-a-fresh-database):

```sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column projects.mapping_editors does not exist```

This was caused by old migrations that were using the new database structure as given, while the migration was not at that level, yet. @ramyaragupathy and I proposed a fix for that in #1547

**Comment by xamanu** [comment]
Great, thanks. @ethan-nelson please merge, if ready.

**Pull request merged**
