### PR TITLE
Minor changes to the test database

### PR DESCRIPTION
**Pull request by xamanu**

### CODE REVIEW

**Comment by arunasank** [comment]
Testing this out currently. 🏃‍♀️

**Comment by willemarcel** [comment]
@xamanu maybe it would be better if we import that dump and export it with the ` --no-owner` option on the `pg_dump` command, so it will not require to set a user or superuser to restore the dump correctly.

**Comment by willemarcel** [comment]
@xamanu @arunasank I pushed the change I mentioned in the last comment to https://github.com/hotosm/tasking-manager/pull/1513

**Comment by xamanu** [comment]
Cool. Closing here.

**Pull request closed without merging**
