### PR TITLE
Cleanup dockerfiles, remove duplicates, upgrade PDM

### PR DESCRIPTION
**Pull request by spwoodcock**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [x] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue

Fixes https://github.com/hotosm/tasking-manager/issues/6552

## Describe this PR

- Removes dup / redundant dockerfiles.
- Upgrades PDM and debugpy to latest.
- Removes hardcoded `--workers` flag for Gunicorn (can be set by `WEB_CONCURRENCY` env var instead).
- Re-locks dependencies after PDM version upgrade using `inherit_metadata` strategy (required PDM > 2.15).

## Review Guide

Notes for the reviewer. How to test this change?

## Checklist before requesting a review

- 📖 Read the Tasking Manager Contributing Guide: <https://github.com/hotosm/tasking-manager/blob/develop/docs/developers/contributing.md>
- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.
- 🔠 Does this PR introduce or change any environment variables? If so, make sure to specify this change in the description.

### CODE REVIEW

**Review by mahesh-naxa — APPROVED** [review]

**Comment by mahesh-naxa** [comment]
@dakotabenjamin i just verified this, can be merged.

**Comment by dakotabenjamin** [comment]
Errors after merging, which weren't caught because they are in server instantiation: 
```
+ sudo apt-get -q -y install libgeos-3.9.0 libgeos-dev
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libgeos-3.9.0
E: Couldn't find any package by glob 'libgeos-3.9.0'
E: Couldn't find any package by regex 'libgeos-3.9.0'
+ sudo apt-get -q -y install libproj19 libproj-dev
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libproj19
```

In addition, a slew of errors compiling sklearn during pip install.

**Comment by spwoodcock** [comment]
Any way we can test the Cloudformation (I assume) stuff locally?

It's a bit baffling how the libgeos install would have broken when this PR updates dockerfiles 😯

The second issue around the numpy version can be fixed by pinning the numpy version explicitly (if sklearn requires this)

**Comment by mahesh-naxa** [comment]
@spwoodcock We can use https://www.localstack.cloud/ to run the EC2 instance with the defined user-data scripts locally, but i am not sure if it supports the AMI we are using. Let me check. 
Otherwise i will spin up a EC2 in the AWS to validate everything.

**Pull request merged**
