### PR TITLE
Task diff update

### PR DESCRIPTION
**Pull request by ethan-nelson**
Please see #1153 for full background

This PR implements an "abbreviated" project API endpoint that does not contain geometry for the individual tasks and updates to the frontend to handle this. This behavior is only used for routine refreshing (the ~10 second idling refresh when a user is viewing the project screen without any interaction).

For routine refreshing, this is sufficient to change the states of tasks on a user's screen as they change state in the database. The core exception to this is when tasks are split, which is handled on the frontend by checking the length of the task layer currently loaded versus that sent by the server; if they are not equal, more tasks exist on the server (precisely 3 if a square is split) and it falls back to the original refresh behavior.

For all other refreshing, i.e. when a user performs an action on a task, the original refresh behavior is retained for that user at that point. This is a pretty conservative approach as it's not probably necessary, but I rather minimize the number of things changed at once. We can always phase in other places where we add this optimization.

Note this is complementary to possibly other methods of streaming updates between the client and the server, assuming those can fall back to this if that method is not enabled.

Beyond whether it works or not (I have tested this locally with multiple users doing different actions including splitting), I'm looking for feedback on the frontend code and how it can/whether it should be refactored.

### CODE REVIEW

**Comment by ethan-nelson** [comment]
Update: I did refactor some of the frontend code after I had slept overnight. The changes are now much more minimal. Now, we substitute the function for the 10 second refresh with a new one that tries to do the abbreviated update, and if there's any issue, that function falls back on calling the original. Hopefully this makes it much more straightforward.

**Comment by ethan-nelson** [comment]
This is ready for review if someone wants to assign themselves @xamanu @ramyaragupathy @willemarcel

**Comment by xamanu** [comment]
I would like to review it. There seems to be a conflict with the latest version of the `develop` branch. Can you please rebase and check, @ethan-nelson? Thanks.

**Comment by ethan-nelson** [comment]
Done

**Comment by xamanu** [comment]
Rerolled and moved this PR to a local branch in #1514

**Pull request closed without merging**
