### PR TITLE
Project Creationn: Error Message alignment

### PR DESCRIPTION
**Pull request by Thrazadin**
Resolved the Error Message alignment issue for self intersecting shapes by adding in-line css styling to the span tags which provide the error message.

### CODE REVIEW

**Comment by ramyaragupathy** [comment]
image
👍 @Thrazadin - notification is aligned good

**Comment by ethan-nelson** [comment]
Thanks @ramyaragupathy for reviewing.

**Comment by ethan-nelson** [comment]
Thank you @Thrazadin for your help with this!

**Comment by Thrazadin** [comment]
You're welcome @ethan-nelson!

**Pull request merged**
