### PR TITLE
Add walkthrough, fix typos in migration script

### PR DESCRIPTION
**Pull request by ethan-nelson**
Based on #1183 there were some bugs in the migration script. Additionally, the general process was kind of vague. This fixes the bugs and also adds more text to help a user go through the migration process. This PR is filed in line with changes to the wiki page https://github.com/hotosm/tasking-manager/wiki/Migrating-from-TM2-to-TM3.

Thank you to @wildintellect for @kleper for feedback on this process!

### CODE REVIEW

**Comment by ethan-nelson** [comment]
I have a potential testing database, so standby for results from that.

**Comment by xamanu** [comment]
@ethan-nelson can you provide me the db for reproducing the error? I'd be happy to test it.

**Comment by ethan-nelson** [comment]
This needs a little more work. There are issues in instructions for defining the schemas versus tables

**Comment by xamanu** [comment]
Brought in with #2064

**Pull request closed without merging**
