### PR TITLE
Countries most contributed endpoint

### LINKED ISSUE #2207: List number of tasks mapped and validated per country per user
We need to create a backend endpoint which returns for a given user, the number of tasks mapped and validated. The result must be grouped per country and ordered by the total amount in descending order.

For instance. When hitting `GET api/v2/users/<string:username>/countries-most-mapped/`, the server should return:

```
"countries": [
  {
    "name": "null island",
    "centroid": "0, 0",
    "mapped": 100,
    "validated": 200,
     "total": 300
  }, ...
]
```

Is is required for the user profile page: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652191

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
Closes #2207 . Removed the centroid from the server response

### CODE REVIEW

**Comment by willemarcel** [comment]
@JorgeMartinezG I tested and it worked well. On `/api/v2/users/{username}/statistics/` we have:

```
{
  "totalTimeSpent": 493687,
  "timeSpentMapping": 483846,
  "timeSpentValidating": 9841,
  "projectsMapped": 4,
  "countriesMapped": [
    "Brazil",
    "Cuba",
    "South Africa",
    "Uruguay"
  ],
  "tasksMapped": 1333,
  "tasksValidated": 5
}
```

Maybe, instead of adding a new endpoint, it would be better to replace the `countriesMapped` field on that endpoint with the new data. What do you think, @ramyaragupathy and @xamanu ?

**Comment by xamanu** [comment]
Are there any performance concerns to bring them all into one endpoint? If not, I would follow @willemarcel suggstion to combine them.

**Comment by JorgeMartinezG** [comment]
Checking the code https://github.com/hotosm/tasking-manager/blob/develop/server/services/users/user_service.py#L268, the service does multiple queries to the database. In my local instance, the endpoint to return the countries and numbers, takes around 900 ms.

**Comment by JorgeMartinezG** [comment]
Rebased and included changes:
```
{
    "totalTimeSpent": 10748,
    "timeSpentMapping": 10407,
    "timeSpentValidating": 341,
    "projectsMapped": 2,
    "countriesContributed": {
        "countries": [
            {
                "name": "Colombia",
                "mapped": 1,
                "validated": 0,
                "total": 1
            },
            {
                "name": "Bolivia",
                "mapped": 1,
                "validated": 0,
                "total": 1
            }
        ],
        "total": 2
    },
    "tasksMapped": 2,
    "tasksValidated": 0
}
```

**Comment by JorgeMartinezG** [comment]
@willemarcel Do you get 200 without this commit?

**Comment by willemarcel** [comment]
> @willemarcel Do you get 200 without this commit?

no, it fails too. Do you think we could fix this issue in another PR?

**Comment by JorgeMartinezG** [comment]
please check https://github.com/hotosm/tasking-manager/pull/2234. It fails in a jest test

**Pull request merged**
