### PR TITLE
fix autocomplete for organisation and campaign in editprojectadmin

### PR DESCRIPTION
**Pull request by fiennyangeln**
#977 
@bgirardot hi! please review the changes :) thx!

### CODE REVIEW

**Comment by bgirardot** [comment]
@fiennyangeln This looks like it works great!

If it is easy only, if not I will merge it in as is because it is basically exactly right as spec'ed out now, but if it is easy could it be case insensitive?

Right now to match Red Cross or British Red Cross, I have to type "Red" with the capital R, if I just type red, it does not match anything.

If that is not a quick easy fix, no problem adn I will merge this in, thank you very very much!

**Comment by fiennyangeln** [comment]
I am currently trying to look at other solution to enable it. But it might make it slower. 

But I will first try to figure out why my environment suddenly not working today.

**Comment by fiennyangeln** [comment]
hi @bgirardot please check:)

**Comment by fiennyangeln** [comment]
@bgirardot Hi! I change this one to enable case insensitive. Please review :)

**Comment by bgirardot** [comment]
@fiennyangeln Works great! Thank you very much.

@ethan-nelson Might get a chance to review the code, I am less worried about performance on this because it is not on the main Contribute page, this gets used a lot less often.

but this works much better now, pretty important fix, I would like to get it merged in asap.

**Pull request merged**
