### PR TITLE
Handle null campaigns in PATCH

### PR DESCRIPTION
**Pull request by ramyaragupathy**
To test, try saving a project with null campaigns and this should get through

### CODE REVIEW

**Comment by willemarcel** [comment]
@ramyaragupathy I made the query more efficient. A yet better solution would be:

```
        try:
            new_ids = [c.id for c in project_dto.campaigns]
        except TypeError:
            new_ids = []
        current_ids = [c.id for c in self.campaign]
        if new_ids != current_ids:
            self.campaign = Campaign.query.filter(
                Campaign.id.in_(new_ids)
            ).all()
```

@JorgeMartinezG some opinion on this?

**Comment by willemarcel** [comment]
@ramyaragupathy We should apply the same solution to the Interests field

**Comment by JorgeMartinezG** [comment]
What about this? If you want to avoid some unneeded query when model and dto have same ids

```
self.campaign = []
if project_dto.campaign is not None:
    model_ids = [c.id for c in self.campaign]
    dto_ids = [c.id for c in project_dto.campaigns]

    # Get ids that are in dto but not in model (New campaigns).
    new_ids = [i for i in dto_ids if i not in model_ids]

    # Get ids that are in model but not in dto (Remove campaigns).
    removed_ids = [i for i in model_ids if i not in dto_ids]

    # If there is at least one item within the two lists, update.
    if len(new_ids) > 0 or len(removed_ids) > 0:
        self.campaign = [Campaign.query.get(i) for i in dto_ids]
```

**Comment by willemarcel** [comment]
@JorgeMartinezG your proposal has some problems:
- If you makes `self.campaign` empty on the beginning, `model_ids` will be empty
- If we don't make it empty and keep that `if` statement, we can not make it empty by desire of the user
- `dto.campaigns` can be none and raise `TypeError`

I added the `.sort()` to my proposal

**Comment by JorgeMartinezG** [comment]
Corrected. BTW, everything is jumped when project_dto is None, not empty.

the dto has campaigns field with a default of [], so it should deserialize to an empty list if campaigns is not provided in the endpoint.

**Review by willemarcel — APPROVED** [review]

**Pull request merged**
