### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by michael63-osm**
The previous German localization contained severe errors, probably due to lacking context for the translators. I streamlined everything on Transifex, this new file has been downloaded from there.

### CODE REVIEW

**Comment by michael63-osm** [comment]
@bgirardot  These are the fixes which we discussed recently. Any chance of this getting merged in the near future?

**Comment by bgirardot** [comment]
Hi Michael, I have to look into this more, I am not super good at transifex and the whole process.

**Comment by michael63-osm** [comment]
Hi Blake, there is not much process know-how involved here. I changed the strings on Transifex, pulled them from there, they are contained in the `de.json` file which is the contents of this pull request. It should replace the existing `de.json` file. Looking at the "files changed" tab reveals that I just changed words in many strings and made sure that the formatting of the file is preserved. So this should not break anything.

Still to keep in mind: my issue #781 that `en.json` needs to be updated and put on Transifex for the modified user interface is still valid.

**Comment by bgirardot** [comment]
@michael63-osm We worked on the translations over the weekend and now I understand the process better and where we keep the language files.

I pulled all the translations from transifex and ethan merged them in so they should include your updated DE translation.

You can review them on https://tasks-stage.hotosm.org/

Please let me know if you see any issues on the staging site.

Thank you very much for updating the DE translation, I see what you mean about how much needed improvements.

**Comment by bgirardot** [comment]
@michael63-osm Hi Michael, as I mentioned above, all of your changes should be merged in and now moved from stage to the main Tasking Manager now. If this is not the case please let me know and we can re-open this. Thank you very much for fixing the German translation.

**Pull request closed without merging**
