### PR TITLE
Update TM3 username if OSM username changed

### LINKED ISSUE #832: impossible to login after OSM username change
In OSM, it's possible to change its username (osm_id doesn't change).
It looks like TM3 doesn't handle username changes and it's impossible to login the tasking manager after a username change.
I fixed the problem in TM2: see https://github.com/hotosm/osm-tasking-manager2/pull/302

Ask me for further information.

### PR DESCRIPTION
**Pull request by ethan-nelson**
Fixes #832 and other issues in Slack chat associated with users changing their OSM username then attempting to log into TM3 again.

I tested this manually and it worked. I'll write an automated test for this soon, but please feel free to review.

### CODE REVIEW

**Comment by ethan-nelson** [comment]
Tests added (https://github.com/hotosm/tasking-manager/pull/848/commits/8d13c302358a6a46919b360d8369a0de03df7784)

**Comment by ethan-nelson** [comment]
Closing in favor of a PR off a branch on the TM repo

**Comment by pgiraud** [comment]
[off-topic]

> Closing in favor of a PR off a branch on the TM repo

What is wrong with creating a PR from a branch from your fork?
In my opinion, this a good way to go.

**Comment by bgirardot** [comment]
I agree with @pgiraud PRs based on branches from our forks.

**Comment by ethan-nelson** [comment]
@pgiraud @bgirardot the issue here was that we were testing deployment to the demo location on this change, and I believe doing so requires the branch to be on the base TM repo--but maybe that is wrong.

**Comment by pgiraud** [comment]
That’s Blake told me. That makes perfect sense.

**Pull request closed without merging**
