### PR TITLE
Mentioning user enabled in mapping comments.

### LINKED ISSUE #2573: Mention people in mapping comments
This is not working nicely. With an @ people should be able to choose from a drop-down search possible users. The usernames can also include white spaces.

### PR DESCRIPTION
**Pull request by ritvikjain99**
1. User, now can be mentioned in task comments.
2. Backend was already working fine, frontend needed implementation.
3. Most of the code is imported from component `<PostProjectComment />` whose author is @JorgeMartinezG .
4. Only problem I am facing is, backend throws error if user doesn't have `TM_EMAIL_FROM_ADDRESS` environment set.
Closes #2573 
Please review @xamanu !

### CODE REVIEW

**Comment by JorgeMartinezG** [comment]
thank you @ritvikjain99 . The env var is necessary in order to send messages to users. We need a sender which is the TM_EMAIL_FROM_ADDRESS.  If you are working locally set the TM_lOG_LEVEL to DEBUG to get the message in the logs.

For the PR, I would like to wrap everything into a single component, like `MentionUsersTextArea` and put all necessary handlers, components and html tags in there.  This would improve scalability and in the future we would just need to change that component. Also, we reduce repeated code.

Let me know your opinion

**Comment by ritvikjain99** [comment]
@JorgeMartinezG, Yes even I was thinking the same, this PR was just to draw your attention towards the enabled functionality, the functions like `formatUserNamesToLink`, `fetchUsers` are pretty generic already. As most of the code is already there, it's just kind of rearrangement of code that needs to be done, would love to work it out !
Would be really helpful if you give some suggestions !

**Comment by JorgeMartinezG** [comment]
All the exported components in this commit should be moved to the new component. Also de textarea autocomplete. The new component should receive the comment and setcomment variables. 

I would make question and comments work with the new function and then export it to the taskactivity

**Comment by ritvikjain99** [comment]
@JorgeMartinezG Here's the things I have done:
1. Created a component : 
`<MentionUserTextArea
            postUrl={<url to post comment to>}
            onCommentUpload={<function>}
            action={}
          />`.
2. Moved the messages to appropriate folder.
3. Moved the function `formatUserNamesToLink` to utils.
Functionality is working fine, also the CSS was messed up, I tried to clean it. The only problems I am encountering with CSS are:
a) The box height varies as suggestion list appears.
b) (BUG) The icon height more than the actual size of icon, leading to extra blank space:

comment

**Comment by JorgeMartinezG** [comment]
@ritvikjain99 please check this commit: https://github.com/hotosm/tasking-manager/commit/c81d7fc42e1841b2478e28975427f5e9bc58bab3 Basically I just moved the textarea needed functions and components into a big component *UserFetchTextarea*. Then, I call this one in TaskActivity and TaskSelection/action components. Right now, it needs tha value ,the onchange handler and token. I think we could read the token directly from the component.

**Comment by ritvikjain99** [comment]
@JorgeMartinezG thanks, this is really great implementation. Maybe I couldn't understand your instructions accurately. I improved some styling of comments section, I'll push changes to your branch.

**Comment by ritvikjain99** [comment]
fixed by #2629

**Pull request closed without merging**
