### PR TITLE
Switch to react frontend

### LINKED ISSUE #1805: Switch to new frontend
In order to focus on the development of the redesign and transition to the new frontend #1757 the code base should build to new frontend, the ci run it and the documentation mention it.

### PR DESCRIPTION
**Pull request by xamanu**
This PR includes #1807  and fixes #1805.

* Removed `client` directory including the old frontend based on AngularJS.
* Adjusted the server to load on the new frontend instead.
* Updated the Docker setup to use the new frontend
* Updated documentation to reflect the new frontend
* Updated deployment scripts to build and serve the new frontend (couldn't test it myself)

### CODE REVIEW

**Comment by xamanu** [comment]
This is ready for review.

**Comment by xamanu** [comment]
Thanks for the review! After final checks by @dakotabenjamin this could be merged for deployment on staging.

**Comment by dakotabenjamin** [comment]
I'm running local CircleCI builds and running into this error: 
```
====>> Install requirements
  #!/bin/bash -eo pipefail
# Install NPM packages and build frontend
cd ${CIRCLE_WORKING_DIRECTORY}/frontend
npm install
npm run build
cd ${CIRCLE_WORKING_DIRECTORY}
# Install Python dependencies
pip install virtualenv
virtualenv env
${CIRCLE_WORKING_DIRECTORY}/env/bin/pip install --upgrade pip
${CIRCLE_WORKING_DIRECTORY}/env/bin/pip install -r requirements.txt

npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated fsevents@2.0.6: Please update: there are crash fixes
npm WARN deprecated intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN tar write after end

> node-sass@4.12.0 install /home/circleci/app/frontend/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-64_binding.node
Download complete
Binary saved to /home/circleci/app/frontend/node_modules/node-sass/vendor/linux-x64-64/binding.node
Caching binary to /home/circleci/.npm/node-sass/4.12.0/linux-x64-64_binding.node

> core-js@2.6.9 postinstall /home/circleci/app/frontend/node_modules/babel-runtime/node_modules/core-js
> node scripts/postinstall || echo "ignore"


> core-js-pure@3.1.4 postinstall /home/circleci/app/frontend/node_modules/core-js-pure
> node scripts/postinstall || echo "ignore"


> node-sass@4.12.0 postinstall /home/circleci/app/frontend/node_modules/node-sass
> node scripts/build.js

Binary found at /home/circleci/app/frontend/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @typescript-eslint/eslint-plugin@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/typescript-estree@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN frontend@0.1.0 No description
npm WARN frontend@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1619 packages from 795 contributors in 34.646s
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> frontend@0.1.0 build /home/circleci/app/frontend
> react-scripts build

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'mini-css-extract-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/circleci/app/frontend/node_modules/react-scripts/config/webpack.config.js:21:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/circleci/app/frontend/node_modules/react-scripts/scripts/build.js:38:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by xamanu** [comment]
This might be related to the [this bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927059) of the nodejs & npm version in current Debian. Installing it from the node-repositories worked. Just updated the PR and verified with a local build.

**Comment by xamanu** [comment]
Rebased on latest `develop`.

**Comment by thadk** [comment]
Looks good generally but we might not want to use a mix of `npm` and `yarn` in our build scripts. There are some edge cases where they don't act quite the same way on `node_modules` and don't anticipate each other's behavior.

We can probably use whichever one is used for the `install`. I have been using `yarn install`, `yarn build` locally.

**Comment by xamanu** [comment]
After review of @dakotabenjamin and as of his suggestion, added a line to include the `NODE_PATH` for proper deployment. Ready for merge :tada:

**Comment by willemarcel** [comment]
Some problems I noticed:

[ ] - API seems to be defined to 127.0.0.1, I believe we can solve it by setting the env var `REACT_APP_STACK=STAGING`

**Comment by xamanu** [comment]
Thanks @willemarcel, will tackle them in a new PR.

**Pull request merged**
