### PR TITLE
Update Rapid to v2.3.1 from v2.2.5

### PR DESCRIPTION
**Pull request by tsmock**
There are fairly minimal changes required for this to work.

About the only thing of note is Rapid requires node 18 or later. Setting the `NODE_OPTIONS=--openssl-legacy-provider` environment variable will work around the following issue (see #6053):
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at frontend/node_modules/webpack/lib/NormalModule.js:452:10
    at frontend/node_modules/webpack/lib/NormalModule.js:323:13
    at frontend/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at frontend/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at frontend/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

This depends upon moving to node 18 (see #5908).

EDIT: We are now on node 18.

### CODE REVIEW

**Comment by varun2948** [comment]
@tsmock how can we go ahead on this PR ?

**Comment by tsmock** [comment]
@varun2948 : If you don't mind the failing frontend-code-test job, yes.

I _think_ it should have been fixed by #6397. I did just rebase, and it is still failing.

**Comment by ramyaragupathy** [comment]
Next steps here is testing on dev server. Prioritising this for next release @royallsilwallz @manjitapandey @varun2948

**Comment by manjitapandey** [comment]
Found few errors on testing:
Uploading of edits failed: An unknown crash occurs when trying to upload the edits on rapid editor. 
Steps to reproduce

- Draw few features using rapid editor. 
- Click on save to upload the features on osm. 
- See error.
image

Refresh the page to get upload page on left panel. 404 error pop-up is seen.
image

**Comment by tsmock** [comment]
@manjitapandey : That should be fixed now.

**Comment by royallsilwallz** [comment]
hey @tsmock, can you rebase to the latest develop branch and push?

**Comment by royallsilwallz** [comment]
The version upgrade will be from v2.2.5 to v2.3.1 since rapid got accidently upgraded to v2.2.5 in [this PR](https://github.com/hotosm/tasking-manager/pull/6375/files#diff-bf1fb20d2aa6db414c7a8e353fe11f8e89a8ea266d229e6411634a6227549c5dR2669) during yarn lock generation.

**Comment by ramyaragupathy** [comment]
From @manjitapandey on slack:

>  I was testing the [Rapid version upgrade PR](https://github.com/hotosm/tasking-manager/pull/6202) on [Naxa server](https://tm.naxa.com.np/explore). Everything works fine except I can't see microsoft buildings and facebook roads which are available on same area in rapid website.
> The next step we are thinking is to merge the PR on HOT dev server and test it again before the release.

**Pull request merged**
