### PR TITLE
Increase z-index of popout.

### LINKED ISSUE #2554: Id editor layout overlays TM menus
Based on feedback received from testing mapathon:

image

### PR DESCRIPTION
**Pull request by ritvikjain99**
Closes #2554 
Id editor fields have z-index: 100 !

### CODE REVIEW

**Comment by xamanu** [comment]
@willemarcel is this fixing one of the issues detected yesterday during the testing of the overlap of elements on the iD editor?

**Comment by JorgeMartinezG** [comment]
I have checked locally and works correctly.

image

@ritvikjain99 could you please rebase with latest develop branch? Maybe you would need to re-run `npm install`

**Comment by ritvikjain99** [comment]
@JorgeMartinezG at once !

**Comment by willemarcel** [comment]
we need to update also the user dropdown z-index

**Comment by ritvikjain99** [comment]
@willemarcel I'll get it done soon !

**Comment by xamanu** [comment]
Can we get over the buttons of iD, too?

image

**Comment by xamanu** [comment]
Please excuse. This was a mistake on my side. It looks great. merging now. Thanks again!

**Comment by willemarcel** [comment]
@xamanu please don't merge it now. Quincy has made some changes on the iD z-index, so maybe this change is not needed https://github.com/openstreetmap/iD/commit/14da8cb7a7e684055055c2e5e20980e70e18caa7

I would like to test the recent changes before introducing more z-index levels

**Comment by xamanu** [comment]
ok, assigned to you @willemarcel

**Comment by willemarcel** [comment]
@ritvikjain99 thank you very much! This commit on id https://github.com/openstreetmap/iD/commit/14da8cb7a7e684055055c2e5e20980e70e18caa7 solved the problem

**Pull request closed without merging**
