### PR TITLE
List contributions from a user by day

### LINKED ISSUE #1604: Add endpoint to return the number of contributions of a user by day
Return the number of tasks mapped and validated by day by a user on the last 365 days. It will allow us to do a contributions timeline similar to the one github has.

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
This PR closes #1604. Within the API, when hitting:
```
'/api/v1/user-id/<int:userid>/contributions
```
The server will return the number of contributions by day for the last 365 days. Dates without contributions will have the value of 0.

### CODE REVIEW

**Comment by willemarcel** [comment]
@JorgeMartinezG let's apply the same logic of  #1768 here? List only the dates with activity and sort from the most recent to the older

**Comment by JorgeMartinezG** [comment]
@willemarcel quick question. Should the endpoint return tasks mapped and validated separately? I mean, To return the structure like:
```
{'contributions : [
  {'date': '2018-06-08', 'mapped': 2, 'validated': 5},
  {'date': '2018-06-07', 'mapped': 1, 'validated': 5},
]}
```

or just the global count, like:
```
{'contributions : [
  {'date': '2018-06-08', 'count': 7},
  {'date': '2018-06-07', 'count': 6},
]}
```

**Comment by willemarcel** [comment]
@JorgeMartinezG We just need the general count number for the users.

**Comment by JorgeMartinezG** [comment]
@willemarcel PR is already rebased with develop. The requested changes has been included 👍

**Pull request merged**
