### PR TITLE
Block read_only user comments in project chat

### PR DESCRIPTION
**Pull request by uwaiszaki**
Fix for #1435

### CODE REVIEW

**Comment by ethan-nelson** [comment]
Hi @uwaiszaki thanks for your contribution on this! I think the approach may need to be altered a bit.

Right now, since the changes are on the frontend, someone that is blocked could use the API to add project chat. So, first, we should add a check at https://github.com/hotosm/tasking-manager/blob/develop/server/services/messaging/chat_service.py#L18 that ensures the chat member does not have a READ_ONLY role attached to their user object.

Additionally, I think it would be more straightforward on the frontend to just `ng-hide` the chat box at https://github.com/hotosm/tasking-manager/blob/develop/client/app/components/project-chat/project-chat.html#L18-L39 if a user's role is read only so that the user has a direct signal they cannot participate. That could be done by using https://github.com/hotosm/tasking-manager/wiki/Restricting-features-to-certain-users.

Let me know your thoughts. Also, if you need any guidance, I'm happy to assist as well. Cheers!

**Comment by xamanu** [comment]
A backend quick fix has been applied. Let's continue on this one here to implement it properly as started by @uwaiszaki.

**Comment by JorgeMartinezG** [comment]
Thanks @uwaiszaki for this contribution 👍 

Updating this PR, these changes disallow read_only users to view chat messages. I think the only restriction would be to post messages. 

I think one quick fix on the frontend side might be a `ng-show` directive which checks for user role:
https://github.com/hotosm/tasking-manager/blob/develop/client/app/components/project-chat/project-chat.html#L18

@xamanu @uwaiszaki let me know your opinions 🤓

**Comment by xamanu** [comment]
I think we want the interface to appear like a user can not comment -  instead of currently presenting an error message when trying to comment. But we still want to show comments to read_only users. Comments are also visible to logged out users.

**Comment by uwaiszaki** [comment]
@xamanu @JorgeMartinezG Should I just hide the comment box or showing this message is fine?
tmpull1438

**Comment by JorgeMartinezG** [comment]
I think hiding comment box and message button is OK. The issue with displaying message is that it would become necessary to translate into mulitple languages @uwaiszaki

**Comment by xamanu** [comment]
Yes, I also think to hide the text box and button is just fine. To display the error is a bit strong. Alternatively we could present a simple text, not red, without the word "Error" that gives feedback like for example "You can not comment".

**Comment by uwaiszaki** [comment]
Thanks, @JorgeMartinezG @xamanu for your reviews. I have updated the pr.
Now the comment box is disabled with a simple text message "You can not comment".

**Comment by JorgeMartinezG** [comment]
I consider this PR ready to be merged. @xamanu do you have additional comments?

**Comment by xamanu** [comment]
Rerolled this and [merged into `develop`](https://github.com/hotosm/tasking-manager/commit/52260a0287bc7b6712f8c8220982f0b2db20ca66). Thanks. Closing here.

**Pull request closed without merging**
