### PR TITLE
Assure centroid data is present before adding map layer

### PR DESCRIPTION
**Pull request by willemarcel**
solves #2158

### CODE REVIEW

**Comment by willemarcel** [comment]
@ramyaragupathy are you seeing the icon on the map? Could you check if the `aoiCentroid` field is present and filled on `/api/v2/projects/<id>/statistics/`

**Comment by ramyaragupathy** [comment]
No there is no icon on the map and I still see the console error. Also centroid is returned through stats endpoint.

**Comment by willemarcel** [comment]
@ramyaragupathy does that error happen on all projects? Could you investigate if it occurs only with projects with a big number of tasks or a complex project/tasks geometry?

**Comment by willemarcel** [comment]
@xamanu could you test this PR, so I can have an additional error/fix case?

**Comment by ramyaragupathy** [comment]
> @ramyaragupathy does that error happen on all projects? Could you investigate if it occurs only with projects with a big number of tasks or a complex project/tasks geometry?

Randomly tested projects and it happens every time

**Comment by xamanu** [comment]
I had difficulties reproducing the issue. Code looks good, and with @ramyaragupathy we decided to merge it it, then we see whether others still have this problems during testing.

**Pull request merged**
