### PR TITLE
Get python tests to work

### PR DESCRIPTION
**Pull request by arunasank**
cc/ @dakotabenjamin

### CODE REVIEW

**Comment by arunasank** [comment]
This seems to be an issue with the file permissions on the test files. The files should not be having executable permissions. Trying to fix the file mode.

**Comment by arunasank** [comment]
Got the tests running, and they pass, but see these errors:

```
..........................................[2019-05-03 16:23:23,892] ERROR in utils: Task: Invalid MultiPolygon - the "coordinates" member must be an arrayof Polygon coordinate arrays
.[2019-05-03 16:23:23,899] ERROR in utils: Task: Expected property not found: 'zoom'
.[2019-05-03 16:23:23,905] ERROR in utils: Task: Invalid GeoJson should be a feature
.........[2019-05-03 16:23:23,954] ERROR in utils: Geojson does not contain any features
.[2019-05-03 16:23:23,955] ERROR in utils: Geojson does not contain any features
.....[2019-05-03 16:23:23,970] ERROR in utils: Area Of Interest: geometry must be a MultiPolygon
...........[2019-05-03 16:23:24,044] ERROR in authentication_service: User element not found in OSM response
...[2019-05-03 16:23:24,052] ERROR in osm_service: User element not found in OSM response
...[2019-05-03 16:23:24,054] ERROR in user_service: You must be an Admin to assign Admin role
.[2019-05-03 16:23:24,054] ERROR in user_service: Unknown role TEST accepted values are BEGINNER, INTERMEDIATE, ADVANCED
.[2019-05-03 16:23:24,055] ERROR in user_service: Unknown role TEST accepted values are ADMIN, PROJECT_MANAGER, VALIDATOR
...[2019-05-03 16:23:24,062] ERROR in mapping_service: Attempting to unlock a task owned by another user
..[2019-05-03 16:23:24,074] ERROR in mapping_service: Can only set status to MAPPED, BADIMAGERY, READY after mapping
.[2019-05-03 16:23:24,126] ERROR in mapping_service: Task in invalid state for mapping
.[2019-05-03 16:23:24,132] ERROR in mapping_service: Mapping not allowed because: USER_ALREADY_HAS_TASK_LOCKED
....[2019-05-03 16:23:24,158] ERROR in mapping_service: Status must be LOCKED_FOR_MAPPING to unlock
...[2019-05-03 16:23:24,207] ERROR in project_admin_service: LicenseId 1 not found
.[2019-05-03 16:23:24,214] ERROR in utils: Tasks: Invalid GeoJson must be FeatureCollection
...[2019-05-03 16:23:24,232] ERROR in project_admin_service: Project Info for Default Locale not provided
.[2019-05-03 16:23:24,238] ERROR in project_admin_service: short_description not provided for Default Locale
..[2019-05-03 16:23:24,255] ERROR in project_admin_service: Must have at least one allowed user on a private project
................[2019-05-03 16:23:24,283] ERROR in validator_service: Task 1 is not MAPPED, BADIMAGERY or VALIDATED
.[2019-05-03 16:23:24,289] ERROR in validator_service: Validation not allowed because: USER_NOT_VALIDATOR
..[2019-05-03 16:23:24,303] ERROR in validator_service: Task 1 is not LOCKED_FOR_VALIDATION
..[2019-05-03 16:23:24,314] ERROR in validator_service: Task 1 is not LOCKED_FOR_VALIDATION
.[2019-05-03 16:23:24,321] ERROR in validator_service: Task 1 is not LOCKED_FOR_VALIDATION
```

Are they related to a permissions issue?

**Comment by dakotabenjamin** [comment]
I got the same errors as you @arunasank 

1. It doesn't cause the tests to fail
2. It doesn't halt circleci

I think fixing those errors is outside of the scope of this PR and it can be merged. Thoughts?

```
====>> Run Python Tests
  #!/bin/bash -eo pipefail
# Run Python tests
cd $CIRCLE_WORKING_DIRECTORY
mkdir $CIRCLE_WORKING_DIRECTORY/tests/server/results
find ./tests/server -name "test*.py" -exec chmod -x {} \;
env/bin/nosetests ./tests/server --with-xunit \
  --xunit-file $CIRCLE_WORKING_DIRECTORY/tests/server/results/unitresults.xml \
  --with-coverage --cover-erase --cover-package=./server
env/bin/coverage xml -o $CIRCLE_WORKING_DIRECTORY/tests/server/results/coverage.xml

..........................................[2019-05-06 13:10:53,604] ERROR in utils: Task: Invalid MultiPolygon - the "coordinates" member must be an arrayof Polygon coordinate arrays
.[2019-05-06 13:10:53,614] ERROR in utils: Task: Expected property not found: 'zoom'
.[2019-05-06 13:10:53,622] ERROR in utils: Task: Invalid GeoJson should be a feature
.........[2019-05-06 13:10:53,696] ERROR in utils: Geojson does not contain any features
.[2019-05-06 13:10:53,697] ERROR in utils: Geojson does not contain any features
.....[2019-05-06 13:10:53,717] ERROR in utils: Area Of Interest: geometry must be a MultiPolygon
...........[2019-05-06 13:10:53,823] ERROR in authentication_service: User element not found in OSM response
...[2019-05-06 13:10:53,835] ERROR in osm_service: User element not found in OSM response
...[2019-05-06 13:10:53,838] ERROR in user_service: You must be an Admin to assign Admin role
.[2019-05-06 13:10:53,838] ERROR in user_service: Unknown role TEST accepted values are BEGINNER, INTERMEDIATE, ADVANCED
.[2019-05-06 13:10:53,839] ERROR in user_service: Unknown role TEST accepted values are ADMIN, PROJECT_MANAGER, VALIDATOR
...[2019-05-06 13:10:53,850] ERROR in mapping_service: Attempting to unlock a task owned by another user
..[2019-05-06 13:10:53,868] ERROR in mapping_service: Can only set status to MAPPED, BADIMAGERY, READY after mapping
.[2019-05-06 13:10:53,915] ERROR in mapping_service: Task in invalid state for mapping
.[2019-05-06 13:10:53,926] ERROR in mapping_service: Mapping not allowed because: USER_ALREADY_HAS_TASK_LOCKED
....[2019-05-06 13:10:53,963] ERROR in mapping_service: Status must be LOCKED_FOR_MAPPING to unlock
...[2019-05-06 13:10:54,040] ERROR in project_admin_service: LicenseId 1 not found
.[2019-05-06 13:10:54,049] ERROR in utils: Tasks: Invalid GeoJson must be FeatureCollection
...[2019-05-06 13:10:54,075] ERROR in project_admin_service: Project Info for Default Locale not provided
.[2019-05-06 13:10:54,084] ERROR in project_admin_service: short_description not provided for Default Locale
..[2019-05-06 13:10:54,109] ERROR in project_admin_service: Must have at least one allowed user on a private project
................[2019-05-06 13:10:54,145] ERROR in validator_service: Task 1 is not MAPPED, BADIMAGERY or VALIDATED
.[2019-05-06 13:10:54,154] ERROR in validator_service: Validation not allowed because: USER_NOT_VALIDATOR
..[2019-05-06 13:10:54,172] ERROR in validator_service: Task 1 is not LOCKED_FOR_VALIDATION
..[2019-05-06 13:10:54,189] ERROR in validator_service: Task 1 is not LOCKED_FOR_VALIDATION
.[2019-05-06 13:10:54,198] ERROR in validator_service: Task 1 is not LOCKED_FOR_VALIDATION
.....
Name                                              Stmts   Miss  Cover
---------------------------------------------------------------------
server/__init__.py                                  131      4    97%
server/api/__init__.py                                0      0   100%
server/api/grid/__init__.py                           0      0   100%
server/api/grid/grid_apis.py                         24     15    38%
server/api/grid/split_task_apis.py                   30     21    30%
server/api/health_check_api.py                        4      1    75%
server/api/license_apis.py                           72     56    22%
server/api/mapping_apis.py                          186    153    18%
server/api/messaging/__init__.py                      0      0   100%
server/api/messaging/message_apis.py                103     77    25%
server/api/messaging/project_chat_apis.py            38     27    29%
server/api/project_admin_api.py                     145    109    25%
server/api/project_apis.py                          145    118    19%
server/api/settings_apis.py                          11      7    36%
server/api/stats_api.py                              59     45    24%
server/api/swagger_docs_api.py                       10      5    50%
server/api/tags_apis.py                              23     16    30%
server/api/users/__init__.py                          0      0   100%
server/api/users/authentication_apis.py              45     33    27%
server/api/users/user_apis.py                       160    126    21%
server/api/utils.py                                  11      2    82%
server/api/validator_apis.py                        111     92    17%
server/config.py                                     30      1    97%
server/models/__init__.py                             0      0   100%
server/models/dtos/__init__.py                        0      0   100%
server/models/dtos/grid_dto.py                       11      0   100%
server/models/dtos/licenses_dto.py                   13      2    85%
server/models/dtos/mapping_dto.py                    55      0   100%
server/models/dtos/message_dto.py                    34      4    88%
server/models/dtos/project_dto.py                   171     33    81%
server/models/dtos/settings_dto.py                   10      0   100%
server/models/dtos/stats_dto.py                      73     22    70%
server/models/dtos/tags_dto.py                        5      0   100%
server/models/dtos/user_dto.py                       90     18    80%
server/models/dtos/validator_dto.py                  62     11    82%
server/models/postgis/__init__.py                     0      0   100%
server/models/postgis/licenses.py                    53     32    40%
server/models/postgis/message.py                     88     44    50%
server/models/postgis/priority_area.py               25     12    52%
server/models/postgis/project.py                    368    274    26%
server/models/postgis/project_chat.py                39     21    46%
server/models/postgis/project_info.py                67     40    40%
server/models/postgis/statuses.py                    49      0   100%
server/models/postgis/tags.py                        35     22    37%
server/models/postgis/task.py                       401    164    59%
server/models/postgis/user.py                       181    127    30%
server/models/postgis/utils.py                       62      8    87%
server/services/__init__.py                           0      0   100%
server/services/grid/__init__.py                      0      0   100%
server/services/grid/grid_service.py                 99      5    95%
server/services/grid/split_service.py               127    102    20%
server/services/license_service.py                   30     14    53%
server/services/mapping_service.py                  169     92    46%
server/services/messaging/__init__.py                 0      0   100%
server/services/messaging/chat_service.py            23      8    65%
server/services/messaging/message_service.py        203    136    33%
server/services/messaging/smtp_service.py            66     39    41%
server/services/messaging/template_service.py        14      5    64%
server/services/project_admin_service.py            139     45    68%
server/services/project_search_service.py           123     89    28%
server/services/project_service.py                  112     52    54%
server/services/settings_service.py                  25     17    32%
server/services/stats_service.py                    190    136    28%
server/services/tags_service.py                       7      2    71%
server/services/users/__init__.py                     0      0   100%
server/services/users/authentication_service.py      99     39    61%
server/services/users/osm_service.py                 29      5    83%
server/services/users/user_service.py               222     95    57%
server/services/validator_service.py                158     92    42%
server/web/__init__.py                                4      0   100%
server/web/controller.py                             14      6    57%
---------------------------------------------------------------------
TOTAL                                              5083   2721    46%
----------------------------------------------------------------------
Ran 126 tests in 0.959s

OK
```

**Comment by arunasank** [comment]
I felt a little uncomfortable merging a PR that I thought was introducing errors, even though the tests pass. However I do see these errors on `develop` also though, so let's merge and tackle separately: https://circleci.com/gh/hotosm/tasking-manager/1920?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Pull request merged**
