### PR TITLE
[WIP] Version 3.0.4 Release

### PR DESCRIPTION
**Pull request by dakotabenjamin**
Marked as WIP because I want to fully summarize changes but there are a lot! Most of the changes are from Hacktoberfest Contributions so let's make sure to attribute properly as well. 

This PR marks a feature freeze. Do not merge any PRs in to develop until after this release has been merged into `master`. The current plan is to merge by the end of next week.

### CODE REVIEW

**Comment by ethan-nelson** [comment]
Wow, a _lot_ of changes. Thank you to the following contributors, especially those who have contributed to the TM for the first time! :1st_place_medal: :confetti_ball: 

@dkocich @nrotstan @smit1678 @Thrazadin @Akshit312 @marlenealv @jillhkm @lesserj @jonyeezs @ernoma @Hulios @PierrePIRONIN @hunt3ri @AndreasHae @hugovk @dakotabenjamin @ramyaragupathy @ethan-nelson 

Changes included:

* Overhaul task history display and fix minor regressions
* Preserve task history when splitting a task
* Fix bug with auto-unlocking tasks after one auto-unlock
* Allow users to comment on a task without locking it
* Add an API endpoint to get users by OSM ID instead of username
* Include linter for frontend files
* Fix issue where users were redirected to the login page after logging in
* Fix awkward error message display when uploading invalid geometry
* Updating some translations and add full Finnish translation
* Add foundation of "expert mode"
* Improve display of buttons to mark a task completely mapped, unlock, split, etc.
* Render markdown in task description as well as the contribute card
* Improve backend tests

Please review these changes on https://tasks-stage.hotosm.org. We are aiming to receive feedback by Wednesday October 24th to iterate on any changes and merge on that Friday or so.

**Comment by Vaomatua** [comment]
Not sure if these items have been requested but these are my suggestions based on creating tasks and contributing to other tasks. 1) Move the legend to a graphic off of the map, 2) Allow a reply to a message, 3) Allow the User Contributions to be sortable 4) remove the pop-up window for profile etc. to go away rather than persist after choosing option like Project dashboard.  
Thanks for the tool, it makes a difference.

**Comment by michael63-osm** [comment]
+ The rearrangement of the buttons on the mapping tab is really helpful and should encourage users to push the right one.
+ Preserving the history after splitting is great too because when validating you want to know what was going on here previously
- I am still waiting for one feature from TM2: That the 'last activity' on the history page does not only show that a task was mapped but also provides a link to that particular task. When you are validating during a mapathon you want to catch errors of new contributors as early as possible. If I can see which task one has just been working on this is much easier to accomplish.
- The validation tab should have a scroll bar for the list of contributors. If it is long then you have to scroll down the whole page thus losing the map view. You cannot see which squares these people down the list have been working on. And it is not always possible to work around this by sorting the list.

**Comment by dakotabenjamin** [comment]
@smit1678 or @ethan-nelson can you review again with the new changes?

**Comment by smit1678** [comment]
Good from my end. The fixes to the icons in the mapping actions looks great. 👍

**Comment by ethan-nelson** [comment]
Thank you again to all the contributors for this update!

**Comment by dakotabenjamin** [comment]
Thanks @ethan-nelson and @smit1678! This will be merged at 9PM Eastern tonight.

**Pull request merged**
