### PR TITLE
Use flask global object to store auth details for lifetime of request.

### PR DESCRIPTION
**Pull request by hunt3ri**
Hi @ethan-nelson on a seperate project I realised my assumptions about the scope of variables during the lifetime of a request were incorrect, meaning variables were persisting across multiple requests.

This PR moves the storage of authentication details into the flask.g global object that ensures they have a lifetime of only one request.  This is how flask recommends you store these sort of temp request specific data.  More info is here http://flask.pocoo.org/docs/0.12/api/#application-globals

This change may improve the login loop issue in #1031 , although I think that may be more of a JS problem.

I also extended the time of checking for new messages to 30 seconds, as that request is generating a lot of noise in the console.

### CODE REVIEW

**Comment by ethan-nelson** [comment]
Hey Iain, thanks for the PR! It's great you were able to find this (I haven't dug into Flask auth much) and is a neat addition. (Ditto on thoughts that JS is responsible for the loop.)

Just FYI I am in the middle of moving, so I won't be able to review this or the other PR until later in the week. Apologies for that delay--though others are welcome to review if available!

**Comment by hunt3ri** [comment]
Hey @ethan-nelson no problem, I think this will definitely improve reliability of login.  Happy for anyone else to review, but I'm sure it can wait a few days.  Good luck with your move!!

**Comment by ethan-nelson** [comment]
Hey Iain,

I had some time to test this, but ran into a problem:

```
Task GET API - unhandled error: '_AppCtxGlobals' object has no attribute 'is_pm_only_resource'
```

I think it may be stemming from the util.py changes, but I'm still trying to digest that file so I can't say for sure :).

**Comment by hunt3ri** [comment]
Thanks @ethan-nelson, it definitely will be.  I thought I'd caught all issues, however, clearly not.  Can you provide the API you were using and the stack trace to pinpoint the bug

**Comment by ethan-nelson** [comment]
I can get that to you tonight. It occurred when trying to select a task on a project that was already loaded, so the GET /api/v1/project/{project_id}/task/{task_id} endpoint.

**Comment by hunt3ri** [comment]
Cool thanks, my suspicion is that variable isn't initialised on unauthenticated routes, I think the original version defaulted the var to False.  Just need to add a bit of handling for that scenario.

**Comment by willemarcel** [comment]
It was already implemented with other solution.

**Pull request closed without merging**
