### PR TITLE
Add `AWS Logo` to footer

### LINKED ISSUE #6402: Integrating AWS logo within footer section
Coming from HOT partnerships team, there is a need to integrate a [logo](https://aws.amazon.com/co-marketing/) within TM pages. I am thinking we could place the logo in our footer section.

image

@nicolelaine - let us know what you think?

cc @royallsilwallz @manjitapandey @dakotabenjamin @eternaltyro

### PR DESCRIPTION
**Pull request by royallsilwallz**
## What type of PR is this?

- [x] 🍕 Feature

## Related Issue

- Resolves #6402 

## Describe this PR

Add `AWS Logo` to the footer section.

## Screenshots

image

### CODE REVIEW

**Comment by nicolelaine** [comment]
Logo placement looks good, thanks so much!

**Review by varun2948 — APPROVED** [review]

**Comment by ramyaragupathy** [comment]
@varun2948 @royallsilwallz - could we also make this configurable, so that it is not a must for other TM instances that 's hosted on different cloud services? We need not rush towards a solution to bring it for the current release. May be we can use a separate PR for another release to make this configurable. Let me know your thoughts.

cc @nicolelaine @dakotabenjamin @manjitapandey

**Comment by royallsilwallz** [comment]
Yeah we can do that if required !

**Comment by ramyaragupathy** [comment]
merging it for now, we can think about configuration options for a later release.

**Pull request merged**
