### PR TITLE
List tasks for the signed in user

### PR DESCRIPTION
**Pull request by ramyaragupathy**
Include:
* [x] Project Status filter
* [x] Paginate results

### CODE REVIEW

**Comment by willemarcel** [comment]
image

I've added some new filters and adjusted the frontend to make the correct queries and use pagination.

@xamanu could you squash @ramyaragupathy commits and merge it?

**Comment by willemarcel** [comment]
There are some errors on the endpoint yet, but we can solve this with other pull request. See https://github.com/hotosm/tasking-manager/issues/2111

**Comment by willemarcel** [comment]
The CI build is failing due to some error on PIP...

**Comment by ramyaragupathy** [comment]
🍏 this time

**Pull request merged**
