### PR TITLE
Add RapiD to list of editors

### PR DESCRIPTION
**Pull request by zlavergne**
Adding RapiD editor for the upcoming Map With AI launch. 

**Note:** ~This will be ready to merge once the instance is live (early this week)~ READY TO MERGE!

### CODE REVIEW

**Comment by zlavergne** [comment]
@xamanu done and done

**Comment by JorgeMartinezG** [comment]
@zlavergne checking this PR, do you think that this editor should be included by default as mapping and validation editor on project model?

https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/project.py#L78

**Comment by zlavergne** [comment]
@JorgeMartinezG During our soft launch, we want RapiD to be opt-in so we can more easily watch projects and handle QA/QC.  

Thanks for clarifying!

**Comment by xamanu** [comment]
This has been deployed on the playground instance last Friday.

**Comment by xamanu** [comment]
This has been tested in the experimental tasks-assisted instance. And will be implemented with an integrated RapiD for TM4.

**Pull request closed without merging**
