### PR TITLE
Version 3.3.0 Release

### PR DESCRIPTION
**Pull request by xamanu**
#### Features:
- #916, #1361, #1423, #1515 - Add inbox filtering, sorting, delete multiple
- #1390 - Add delete message feature in individual message page
- #893, #1421, #1487 - Restrict editor programs for mapping and validation stages
- #1364 - Split tasks with arbitrary geometry
- #1365, #1497 - Encourage user to provide email.
- #602, #1481 - Make organisation and mapping type in project metadata panel required
- #987, #1559 - Introduce option to require validators to be intermediate or advanced mappers
- #796, #1483 - Message users on level upgrade
- #1153, #1368, #1514 - Factor smaller project page refresh
- #1188, #1410 - Add loading message in project page 
- #1524, #1525 - Increase time interval of has-new-messages requests to 1 min
- #1344, #1348 - Provide more numbers about projects and users in internal api
- #1508 - Define cascade relation for project chat
- #1398, #1448, #1551 - Upgrades for backend and frontend dependencies
- #1452 - Include postgres port as configuration parameter
- #1327, #1332 - Replace Elastic Beanstalk with Cloudformation setup
- #1453, #1513 - Add database dump for local testing
- #1470, #1502 - Add script to cleanup projects with invalid geometries and low mapping rates
- #1480, #1498 - Improve Docker setup and create makefile for automated setup and testing environment
- #1494 - Extend gitignore
- #1436, #1557, #1559 - Cleanup deprecated Dockerfiles, unsused shippable library, and removed Elastic Beanstalk configuration

#### Bugfixes:
- #924, #1538 - Keep task selection when changes applied
- #1529, #1564 - Fix broken overpass view by providing AOI
- #1522, #1528 - Bring back the activity overview
- #1552, #1556 - Repair invalidation of tasks marked with "bad imagery"
- #1400, #1389 - Block access to pages for non-existing messages
- #1505, #1507 - Reset bad imagery count on task reset
- #1517 - Fix bugs on TaskInvalidationHistory.record_invalidation and projectMapService 
- #1547, #1548 - Fix several issues with database migrations
- #1519, #1539 - Multiple fixes to python tests
- #1451 - Include a few missing profile translate strings

#### Documentation
 - #1509 - Move documentation from the wiki into the code base docs directory
 - #1540 - Add Entity Relationship Diagram of the TM database
 - #1542 - Update and extend documentation on contribution guidelines
 - #1345 - Add install scripts for Debian 9, 10 and Ubuntu 18.04

#### Contributors
Many thanks to:
- @arunasank
- @dakotabenjamin
- @ethan-nelson
- @fitoria
- @JorgeMartinezG
- @nrotstan
- @ramyaragupathy
- @uwaiszaki
- @willemarcel
- @xamanu

### CODE REVIEW

**Comment by arunasank** [comment]
When do we plan to push this out?

**Comment by xamanu** [comment]
After one week of user testing.

**Comment by ethan-nelson** [comment]
Worked through testing the features locally--bugfixes next

**Comment by xamanu** [comment]
Dear @hotosm/software-testing group,

We are ready and excited for the next release of the Tasking Manager (version 3.3). Before we publish this and install it on the HOT-TM  (tasks.hotosm.org) we would like to ask you to have a look at the new version and check whether everything is working fine.

For this we have installed the release candidate on the “staging instance” of the Tasking Manager (tasks-stage.hotosm.org). You can login as usual, but be aware that all changes you are doing on this installation, are not going to be present in the main Tasking Manager. Feel free to play around with everything, make sure everything works you usually do, and particularly have an eye on the changes and improvements we introduced:

*… for all users*

1. The **message inbox** got extended with many new filtering and sorting options. Please review and try to receive messages, that will contain more filtering options than the ones that are already in the system. You should also be able to delete messages from the page you are reading the message.
2. We present a warning symbol now next to the user name, when there is no email address given. This way we want to **encourage users to add their email addresses** to the TM and they will be able to receive email notifications.
3. The activity stream in project’s **Activities and Stats** was broken and should now work as intended.
4. After an action on a single task was performed (like marking it valid, etc.) the **selection to the tasks should be maintained** instead of reset.
5. After marking a tasks with "bad imagery", now the action to invalidate the task is allowed.
6. We applied some changes to the **refreshing of a single project page** and the **notification with new messages**, please have a look whether everything works smooth.

*… for project managers*

1. Project creators and managers can now **select certain editors for mapping and validation steps** from the project’s settings page. Only these should be editor options when clicking the button to map or validate.
2. The project **fields for organisations and mapping type** should now be mandatory. 
3. And we added another option in the project’s permission page, that allows to **restrict validation to intermediate and advanced users**.
4. You should now be able to **split tasks that are having all kind of geometry**.
5. The **overpass view of contributions by users** was broken and should now be working again.

In case you find any problems, feel free to reach out to us on Slack (#tasking-manager) or give feedback in here.

**Comment by ethan-nelson** [comment]
Re `#924, #1538 - Keep task selection when changes applied`, after validating a task, the task is shown as selected but the actual task info on the left side is still gone. Instead, the `Find a task for validation through one of the options below.` shows. I think the intended behavior was to retain on the left window the task history, the check out a task, and the comment box.

#1564 is absolutely beautiful--love it!

Other than that, I've tried my best to test these changes locally and on the staging instance, and they have all worked!

**Comment by xamanu** [comment]
One of our beloved testers reported one issue to me:

> The warning about no mail address exists.  When I open my profile I receive this notice as well, despite my email address is filled in.

I checked it - to reproduce: 

* Remove the email address from your account.
* Logout and login again - and there is the warning next to the username.
* Add the email address (maintain window open) and click on the confirmation link (new window/tab).
* Go back to the window you put in the email address and click somewhere - the warning still appears.

Is this anything we can easily fix? Or is it related to several updating problems that have been commented in the chat (e.g. when changing the role a logout-login is sometimes necessary, etc.) and it should be a new issue for the next release?

**Comment by nrotstan** [comment]
Regarding the stale top-nav email-address indicator, I've just submitted PR #1593 that refreshes the account service's user data when data for the logged-in user is refetched from the server. That makes user data in the top nav properly reflect the latest without requiring the user to perform a browser refresh.

**Comment by JorgeMartinezG** [comment]
Related to TaskHistory, I have just sent  https://github.com/hotosm/tasking-manager/pull/1594. Feel free to comment if additional changes are necessary

**Comment by xamanu** [comment]
Thanks for the two fixes, @nrotstan and @JorgeMartinezG! Checked and deployed them on the testing instance.

**Comment by russdeffner** [comment]
Regarding messages: It seems the ones that originate from the Q/C panel are not associated with a project, although they should be... 
messaging

**Comment by russdeffner** [comment]
Regarding 4&5: It seems Un-mark only sets it back to the last state, not 'clear marks'. 
To reproduce: I mark a task as Bad Imagery, then 'invalidate', if I now click un-mark, it returns to Bad imagery, not 'ready for mapping'/clear. And continuing to click un-mark will just go back and forth between bad imagery and invalidated states; i.e. no way to 'reset' an individual task to 'clear'/ready to map state.

**Comment by russdeffner** [comment]
Regarding all users 2: when I, as admin/project manager go to another user's profile (i.e. to make them validator, etc) I get/see the warning about their email. Not sure if that's good or not, but wasn't expecting that.

**Comment by russdeffner** [comment]
Maybe found an unintentional change as nothing is mentioned about the individual Project Managers' Project Dashboard - but mine should have 500-600 between drafts, active and archive but is showing 0 in all three categories.

**Comment by russdeffner** [comment]
Regarding PM 3: This still isn't what I thought we had discussed. It works, but still doesn't allow for a PM to allow Advanced and/or Intermediate mappers to validate without the Validation role. I want to be able to say 'no validation role but only intermediate/advanced can validate' as it is, it only really allows the addition of eliminating Beginners with the Validator role, which really shouldn't happen in the first place and will be taken care of with better on-boarding process.

**Comment by ramyaragupathy** [comment]
@russdeffner - Per [this matrix here](https://github.com/hotosm/tasking-manager/pull/1313#issuecomment-488555874) this code allows `no validation role but only intermediate/advanced can validate'`. Can you please help with setting this matrix better for various roles + mapping level?

**Comment by russdeffner** [comment]
@ramyaragupathy I went through the scenarios again and not sure why I had so much trouble before, but the matrix is fine and I think is working in the various scenarios. One thing that did confuse me is there is no displayed metadata for 'intermediate & advanced' so if you are a beginner with/without the role you will get message 'you don't have the role', even if the metadata says it's not required and/or you do have the role. But that can be solved with a simple re-wording of the message 'you don't meet requirements' or similar. Getting the additional metadata displayed on the project description should come eventually, but maybe looks/fits differently with redesign.

**Comment by ramyaragupathy** [comment]
@russdeffner  - roles & levels would undergo a change based on our team & orgs implementation. I suggest let's handle this along with the redesign.

Can you also share a screenshot from `Network` tab of your browser's console when you access your dashboard page? I'd like to see the `Response` for `my-projects (api/v1/admin)` endpoint for your authorization. This will help us narrow down the error quickly. Sharing my dashboard response screenshot for reference:

image

**Comment by xamanu** [comment]
Thanks @russdeffner for the extensive testing. I would like to give feedback to each of the points:

* Unmarking tasks: @JorgeMartinezG has provided a PR that unmarks back to nothing when the state it goes back to, would be `bad imagery` or `mapped`: https://github.com/hotosm/tasking-manager/pull/1623
* Not all messages are associated to a project. This should only be the case for past messages. And is probably not a big problem. We might want to fix this on the way. But I suggest not to see this as a blocker for the release.
* Allow validation only to intermediate and advanced mappers: Seems to work as expected.
* Project dashboard: We were not able to reproduce it locally or on staging with our users. Thanks @ramyaragupathy for digging into this. Hopefully with the screenshots we get more insight to fix this.

**Comment by russdeffner** [comment]
dashboard

Let me know if you need more/something else

**Comment by ramyaragupathy** [comment]
Per chat w/ @russdeffner and @mataharimhairi - Russ's dashboard fetch fails with a timeout error. Mhairi's page loads well. May be it's just the amount of data (466 projects) - but the same works fine on production.  Possibly the staging setup (configured to handle less traffic than production?) is causing this.  I'd say let's go ahead and this should work fine on a production setup

**Comment by xamanu** [comment]
Thank you all for contributing, testing and bugfixing. This is ready to be released. I'm coordinating with @arunasank for the deployments.

**Comment by xamanu** [comment]
The deployments will include a downtime of the HOT TM (tasks.hotosm.org) for 2 hours. We are proposing to schedule it for tomorrow, 30 of May at 7:30am UTC.

**Pull request merged**
