### PR TITLE
Default projects to intermediate difficulty

### LINKED ISSUE #1081: Default project difficulty to "intermediate"
Project managers need to manually set projects good for beginners to beginner projects. We have a lot of projects that are not beginner projects marked as beginner.

### PR DESCRIPTION
**Pull request by ethan-nelson**
Fixes #1081

### CODE REVIEW

**Comment by bgirardot** [comment]
@ethan-nelson Thank you very much for this. I am going to sit on this for a bit longer to make sure all the stake holders are aware of the change and @russdeffner and I can generate some guidance on what makes a "Beginner" project. Basically, we need to do this but we have to better support the PMs before we do it.

**Comment by ethan-nelson** [comment]
@russdeffner do you have any insights into this, or @bgirardot ? Is this idea desired by the AWG?

**Comment by russdeffner** [comment]
I think now that we have a fairly 'standard' on-boarding for new PMs it's less necessary, but still think it's a good idea - i.e. would rather see beginner projects 'mislabeled' as intermediate than an advanced projects mislabeled as beginner. Also, project difficulty should be more readily understood as it is part of the training.

**Comment by ethan-nelson** [comment]
Hi Russ, thanks for the feedback. Thinking about other TM users, this could be a bit clumsy for someone setting up a fresh instance and wondering why people can't immediately edit a brand new project without much intervention. So I'm going to go ahead and table this (it's a trivial change if we later decide to go forward--though note that a database migration will also be required beyond this change).

**Comment by ethan-nelson** [comment]
Ok chatting with Russ a bit more on Slack, the idea here is it would be okay to default the classification of projects to intermediate, but not _restrict_ the projects to intermediate contributors. I will add the database migration (migration being only setting the new default) and open a new PR.

**Pull request closed without merging**
