### PR TITLE
Use consistent heading tag

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by pgiraud** [comment]
Crap. This was merged into `master`. I'm sorry this is so un-natural for me to create PR's against an other branch than `master`.

**Comment by pgiraud** [comment]
Should we revert this and change the pull request so that it applies to `develop`?

**Comment by ethan-nelson** [comment]
Yes--sorry, completely forgot about our development model on this. Chatted with David and that's a good plan.

**Comment by ethan-nelson** [comment]
Just to document, I went ahead and reverted the original commit to master, then I committed new changes to develop. I checked with David and he was fine with that.

**Pull request merged**
