### PR TITLE
ampersand and ng-href fix

### PR DESCRIPTION
**Pull request by alekno**
Answer to Encoding for embedded URLs #904

### CODE REVIEW

**Comment by smit1678** [comment]
@alekno Thanks! I've tagged @pgiraud to review briefly. But can you fix the conflicts before @pgiraud does the final review?

**Comment by alekno** [comment]
@smit1678 @bgirardot 
I will close this pull request next couple hours. I think you can do change these few characters yourself.

**Comment by pgiraud** [comment]
@alekno sorry I didn't give you any feedback earlier.

First of all it would be great if the commits in your pull request was more clear. There shouldn't be any "merge branch ..." or "Update home.html" commits. You can try to do a git rebase to avoid those commits.

Then, it should have been great to separate the `&` change and the `ng-href` removal in 2 different commits since it's better to address different issues in different commits. By the way, can you please elaborate why you removed the `ng-href`? I think I know, but I just want to be sure.

By the way, your commit message `ampersand and ng-href fix` is not very explicit.

Finally, I found some resources which tell that the `&` encoding is not required anymore in HTML5.

> The ampersand (&) may be left unescaped

Sorry. I know I'm a bit picky.

**Comment by alekno** [comment]
Read the angular documentation for what ng-href is used.
No I don't do any more silly git operations on this PR. My commits were done as requested to fix git conflicts. All this for only few characters. So no more of this, I am done. I am also picky. This PR is an follow up to a merge that shouldn't have been done, in first case ( #874 ). 
For HTML5 you need to revaluate your sources.
I hope you have seen the changes I made. PR closed!

**Comment by pgiraud** [comment]
> For HTML5 you need to revaluate your sources.

https://www.w3.org/TR/html5-diff/#syntax-misc
https://stackoverflow.com/questions/19441750/do-ampersands-still-need-to-be-encoded-in-urls-in-html5?noredirect=1&lq=1

And also, please take some time to learn how collaboration works (especially with git/github).

I would have been happy to approve this PR. But I just can't. It doesn't follow the contributing rules (soon to be published).

Unfortunately the commit sequence is messy in my opinion. Fixing conflicts shouldn't mean adding 4 commits. For your information, it's possible to change your commits within your pull request.

> Read the angular documentation for what ng-href is used.

Thanks. I know how to read documentation. And I promise I did. But since there's no explanation here why you removed it, I just wanted to be sure why you did. The current pull request first goal was to address the encoding of ampersands in the links. Not removing `ng-href` for a reason that hasn't been explained before. So I prefer to ask. And also I ask you to rework on you commits in order to keep commit history tidy.

Finally, we want to keep the commit history clear for current or future developers. Please help us. Please accept the critics. I hope they are constructive. I don't want to be harsh. I'm also here to write better code and to better contribute.

**Comment by alekno** [comment]
In HTML5 it is in "discussion". Wake me up in 10 years, let us see when it has made it up to starndard. The ng-href is only helpful, when you put some curly braces code into the href.
And no, I am not a Git user. I am also not willing to read an imaginary documentation on how to "label" commits to HOTOSM.
Worst of all was, that I was forced to do this PR in first case.

**Pull request closed without merging**
