### PR TITLE
Order by and sort options for search project endpoint

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
This Pull request includes the additional request parameters _orderBy_ and _orderByType_ in project search endpoint.

Accepted options were included within _project_dto.py_ file

### CODE REVIEW

**Comment by thadk** [comment]
This API is mostly working well but order-by on the `id` seems to have this issue:

Request: 
```
GET /api/v1/project/search?orderBy=id HTTP/1.1
Host: 127.0.0.1:5000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Origin: http://127.0.0.1:3000
Connection: keep-alive
Referer: http://127.0.0.1:3000/contribute?orderBy=id
Pragma: no-cache
Cache-Control: no-cache
```

Response:
```HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Type: application/json
Content-Length: 1448
Access-Control-Allow-Origin: http://127.0.0.1:3000
Vary: Origin
Server: Werkzeug/0.12.2 Python/3.7.4
Date: Sat, 31 Aug 2019 00:00:11 GMT
{"error": "Project GET - unhandled error: (psycopg2.ProgrammingError) column \"task_history.id\" must appear in the GROUP BY clause or be used in an aggregate function\n
LINE 3: ...jects.status IN (1) GROUP BY projects.id ORDER BY task_histo...\n
                                                             ^\n\n[SQL: SELECT projects.id AS projects_id, projects.mapper_level AS projects_mapper_level, projects.priority AS projects_priority, projects.default_locale AS projects_default_locale, ST_AsGeoJSON(projects.centroid) AS centroid, projects.organisation_tag AS projects_organisation_tag, projects.campaign_tag AS projects_campaign_tag, projects.tasks_bad_imagery AS projects_tasks_bad_imagery, projects.tasks_mapped AS projects_tasks_mapped, projects.tasks_validated AS projects_tasks_validated, projects.status AS projects_status, projects.total_tasks AS projects_total_tasks, projects.last_updated AS projects_last_updated, projects.due_date AS projects_due_date, count(DISTINCT task_history.user_id) AS total_contributors \n
FROM projects JOIN task_history ON task_history.project_id = projects.id JOIN project_info ON projects.id = project_info.project_id \n
WHERE project_info.locale IN (%(locale_1)s, %(locale_2)s) AND projects.status IN (%(status_1)s) GROUP BY projects.id ORDER BY task_history.id]\n
[parameters: {'locale_1': 'en-US,en;q=0.5', 'locale_2': 'en', 'status_1': 1}]\n(Background on this error at: http://sqlalche.me/e/f405)"}

```

**Comment by xamanu** [comment]
Needs to be rerolled on `develop` with the new api layout. Should not be that hard for this PR.

**Comment by thadk** [comment]
Will test this tomorrow, thanks @JorgeMartinezG , not sure about the failing test, but it looks innocuous.

**Comment by xamanu** [comment]
The tests are just failing because of a missing `black server` command to code format the backend (1 file is not sticking to the standards entirely).

**Comment by JorgeMartinezG** [comment]
Branch was rebased with latest develop and fix included 🙌

**Comment by thadk** [comment]
Thanks, not sure why but still having trouble with the `id` on my database, the revised list of other options do work:
```
GET /api/v2/projects/?orderBy=id&orderByType=ASC HTTP/1.1
Host: 127.0.0.1:5000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Origin: http://127.0.0.1:3000
Connection: keep-alive
Referer: http://127.0.0.1:3000/contribute?orderBy=id&orderByType=ASC
Pragma: no-cache
```

returns
```
HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Type: application/json
Content-Length: 38
Access-Control-Allow-Origin: http://127.0.0.1:3000
Vary: Origin
Server: Werkzeug/0.12.2 Python/3.7.4
Date: Thu, 05 Sep 2019 20:26:28 GMT
{"Error": "Unable to fetch projects"}

```

**Comment by JorgeMartinezG** [comment]
@thadk I found the bug and sent the fix. Could you please try again?

**Comment by thadk** [comment]
Looks good now! Thanks for the quick fix, @JorgeMartinezG. I think it is ready for staging.

**Pull request merged**
