### PR TITLE
Notif popup

### LINKED ISSUE #2412: [BUG]: Notification popup.
__BUG__:
There are two bugs in notification panel:
1. The `bell` icon should close the popup on click if it's open, which doesn't happen.
2. The date is shown `invalid`, because the it is fed in wrong format to `<FormattedRelative />` (can be seen clearly in console !).

### PR DESCRIPTION
**Pull request by ritvikjain99**
What these changes intend to do:
[Commit 1]: Corrects the wrong datetime format fed to `<FormattedRelative />`.
[Commit 2]: The `useOnClickOutside` function initially checked if the click was outside popup, so clicking the bell was considered out-click. Which toggled the 'isOpen` state twice.

Now if the popup is opened and the bell icon is clicked, it closes !
Fixes #2412 
@willemarcel  please review !

### CODE REVIEW

**Comment by ritvikjain99** [comment]
@willemarcel the concerned issue will also create problem in mobile view just like the burger menu did, so this I suppose solves that issue as well!

**Comment by willemarcel** [comment]
@ritvikjain99 thanks for the PR. I tested here and it is not closing the bell popup when I click on a notification. Tested both in Firefox and Chromium.

**Comment by ritvikjain99** [comment]
This looks cool, just moved functions to the right file, where they should be !
Things work and look fine now!

**Comment by ritvikjain99** [comment]
Sorry for multiple pushes !

**Comment by ritvikjain99** [comment]
@willemarcel have a look, this is how it behaves with me
ezgif com-video-to-gif(1)

**Comment by willemarcel** [comment]
merged with https://github.com/hotosm/tasking-manager/pull/2485

**Pull request closed without merging**
