### PR TITLE
Allow viewing archived projects by non authenticated users

### PR DESCRIPTION
**Pull request by sunidhiraheja**
The API now allows the behavior requested in https://github.com/hotosm/tasking-manager/issues/1127

While doing the frontend part, I noticed some problems that need to be addressed before I can push the change; discussing on Slack.

### CODE REVIEW

**Comment by bgirardot** [comment]
@sunidhiraheja Can you please add more information when you say "I noticed some problems..."

Could you please list the problems otherwise otherwise reviewers and fellow contributors have no idea what you might be referencing.

Are these problems with this PR or problems in another part of the software? etc...

**Comment by sunidhiraheja** [comment]
@bgirardot Sure, sorry I missed that.
The problem I was facing was that some times, `ng-click` was firing before `ng-model` updated the corresponding value in the model, resulting in unexpected behavior.
So, I changed it to `ng-change`, which monitors the variable mapped using the corresponding `ng-model` directive and only then fires the search function.

**Comment by sunidhiraheja** [comment]
Ready for review! :)

**Comment by ethan-nelson** [comment]
Will take a look this evening--thanks!

**Pull request merged**
