### PR TITLE
show error modal if webgl not supported.

### LINKED ISSUE #4119: Check if browser has WebGL support
If a browser doesn't have permissions to use WebGL, the pages with maps will fail to load. We could check it and show a message to the users in case WebGL is not active.

### PR DESCRIPTION
**Pull request by Abhirup-99**
Fixes #4119

### CODE REVIEW

**Comment by Abhirup-99** [comment]
@willemarcel please review.

**Review by willemarcel — CHANGES_REQUESTED** [review]
It's not rendering the header for me (in a supported browser). I discovered a lib that makes a more robust check https://github.com/mapbox/mapbox-gl-supported

I think we could use it and try to render an error message instead of the map in the pages with maps.

**Comment by Abhirup-99** [comment]
> It's not rendering the header for me (in a supported browser). I discovered a lib that makes a more robust check https://github.com/mapbox/mapbox-gl-supported
> 
> I think we could use it and try to render an error message instead of the map in the pages with maps.

The modal box would show only in an unsupported browser. Would you explain the header part, I didn't get it.

**Comment by willemarcel** [comment]
@Abhirup-99  The tasking manager header, with the login button, the navigation menu, etc is not being rendered

**Comment by HelNershingThapa** [comment]
Closed with https://github.com/hotosm/tasking-manager/pull/5200 being merged in

**Pull request closed without merging**
