### PR TITLE
Add basemap options to Priority Areas form

### LINKED ISSUE #2401: Add basemap options to priority area form
The project priority area form map should have the same basemap options as the project creation map.

### PR DESCRIPTION
**Pull request by d-rita**
Fixes #2401

### CODE REVIEW

**Review by willemarcel — CHANGES_REQUESTED** [review]
When I click to switch the layers, the map data disappears from the screen

**Review by willemarcel — CHANGES_REQUESTED** [review]
The clear all button is not working. It's only resetting the data to the last saved one.

Let's style the aoi layer in orange the same way as in https://github.com/hotosm/tasking-manager/blob/develop/frontend/src/components/projectCreate/projectCreationMap.js#L110

And let's also style the priority area the same way as https://github.com/hotosm/tasking-manager/blob/develop/frontend/src/components/taskSelection/map.js#L240 (we use two layers to make that style possible)

**Comment by willemarcel** [comment]
@d-rita I pushed some improvements to the style. A critical problem I found is that it's generating duplicated geometries. I didn't have time to investigate it deeply.

**Review by willemarcel — APPROVED** [review]

**Review by d-rita — COMMENTED** [review]
The changes look good, @willemarcel

**Pull request merged**
