### PR TITLE
Revert stats implementation to previous version

### PR DESCRIPTION
**Pull request by d-rita**
This PR reverts to the previous working version of the stats retrieval and calculation of user contributions. #5425 

**Pending issue:** 
- Divergent counts on the project detail and project list views. To be fixed in this [PR](https://github.com/hotosm/tasking-manager/pull/5666)

### CODE REVIEW

**Review by Aadesh-Baral — APPROVED** [review]

**Comment by eternaltyro** [comment]
@d-rita I think this volume of change warrants a bit more context to why this change was done. At least in the commit comment; preferably in both the commit and the PR description. 

@Aadesh-Baral with changes like these, I think our review checklist should include dev best practices like commit comment, documentation, CI changes, etc. Can you also please consider those while you review changes?

**Comment by ramyaragupathy** [comment]
@eternaltyro - thanks for the nudge on best practices here. Other than the suggestions you have made, would there be any ways you recommend for handling such reverts?

**Comment by eternaltyro** [comment]
One way is to have a review checklist:

- [ ] PR associated with an issue?
- [ ] Updated CI corresponding to the changes?
- [ ] Updated Monitoring corresponding to the changes?

and so on.. We can create an internal document to finalise this.

**Comment by ramyaragupathy** [comment]
Not just the review, I am also if there is a recommended way to handle commit reverts

**Pull request merged**
