### PR TITLE
Update translations: Dutch and Chinese

### PR DESCRIPTION
**Pull request by d-rita**

### CODE REVIEW

**Comment by eternaltyro** [comment]
How do we review this?

**Comment by d-rita** [comment]
@eternaltyro translations PRs are just to update the language strings. Should have been merged then. I believe there will be a new PR for updated translations across all languages with the upcoming releases.

**Comment by eternaltyro** [comment]
@d-rita what do we do about this one?

**Comment by d-rita** [comment]
Since the plan is to update translations in a completely new PR ([reference discussion](https://github.com/hotosm/tasking-manager/pull/5822#issuecomment-1593548765)), this PR can be closed @eternaltyro

**Pull request closed without merging**
