### PR TITLE
Add {{ | translate }}

### PR DESCRIPTION
**Pull request by brownben**
Add {{ 'x' | translate }} to UI strings which did not have it.
For Issue #1234

### CODE REVIEW

**Comment by ethan-nelson** [comment]
Hi @bonalybob I will be reviewing this PR in the next two days. Thank you!

**Comment by ethan-nelson** [comment]
Thanks again for filing this @bonalybob . I've been going through the changes and things look good--we're holding off on merges until this last big set of changes is merged from develop to master--but I had one question. It looks like in many places you took HTML tags that were split across a few lines and combined them into one. Was that based on lint-er output or something else?

**Comment by bonalybob** [comment]
I think the code has been reformatted by a linter

**Comment by ethan-nelson** [comment]
Thank you @brownben for your help!

**Comment by ethan-nelson** [comment]
Oops, didn't mean to close--only comment

**Pull request merged**
