### PR TITLE
Fix chartjs warnings

### PR DESCRIPTION
**Pull request by tsmock**
See https://github.com/hotosm/tasking-manager/pull/5721#discussion_r1193684581 for additional context.

Big things:
* Keep current behavior as much as possible
* ISO 8601 YYYY-MM-DD for chart X axis labels
* Tooltips shouldn't show hour/minute/second
 * I ended up expanding the tooltips a bit ("Thursday, July 6, 2023" instead of "2023-07-06").

### CODE REVIEW

**Review by HelNershingThapa — CHANGES_REQUESTED** [review]
Ran into the following error when testing the changes locally:

```js
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://github.com/date-fns/date-fns/blob/master/docs/upgradeGuide.md#string-arguments 
    at ChartComponent (http://127.0.0.1:3000/static/js/1.chunk.js:14846:5)
    at ProjectTimeline (http://127.0.0.1:3000/static/js/timeline.chunk.js:46:5)
    at div
    at ReactPlaceholder (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:86503:15)
    at Suspense
    at div
    at div
    at ProjectDetail (http://127.0.0.1:3000/static/js/project.chunk.js:1446:95)
    at ReactPlaceholder (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:86503:15)
    at ProjectDetailPage (http://127.0.0.1:3000/static/js/project.chunk.js:8740:73)
    at RenderedRoute (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:91142:5)
    at Outlet (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:91629:26)
    at QueryParamProviderInner (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:110482:5)
    at ReactRouter6Adapter (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:110417:5)
    at QueryParamProvider (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:110502:5)
    at div
    at Root
    at RenderedRoute (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:91142:5)
    at RenderErrorBoundary (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:91089:5)
    at DataRoutes (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:91537:5)
    at Router (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:91650:15)
    at RouterProvider (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:91477:5)
    at Suspense
    at main
    at div
    at ErrorBoundary (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:28312:5)
    at App (http://127.0.0.1:3000/static/js/main.chunk.js:12092:70)
    at IntlProvider (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:85848:43)
    at ConnectedIntl (http://127.0.0.1:3000/static/js/main.chunk.js:44019:58)
    at ConnectFunction (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:87316:121)
    at PersistGate (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:104139:5)
    at Provider (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:87043:5)
```

```js
Error
    at toDate (index.js:48:1)
    at formatISO (index.js:45:1)
    at TimeSeriesScale.callback (tasksStatsChart.js:40:1)
    at callback (helpers.segment.mjs:47:1)
    at TimeSeriesScale._tickFormatFunction (chart.mjs:10562:1)
    at TimeSeriesScale.generateTickLabels (chart.mjs:10568:1)
    at TimeSeriesScale._convertTicksToLabels (chart.mjs:3154:1)
    at TimeSeriesScale.update (chart.mjs:2918:1)
    at fitBoxes (chart.mjs:4517:1)
    at Object.update (chart.mjs:4655:1)
    at Chart._updateLayout (chart.mjs:5771:1)
    at Chart.update (chart.mjs:5704:1)
    at new Chart (chart.mjs:5476:1)
    at renderChart (chart.tsx:42:1)
    at chart.tsx:98:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
```

```js
index.js:47 Uncaught RangeError: Invalid time value
    at formatISO (index.js:47:1)
    at TimeSeriesScale.callback (tasksStatsChart.js:40:1)
    at callback (helpers.segment.mjs:47:1)
    at TimeSeriesScale._tickFormatFunction (chart.mjs:10562:1)
    at TimeSeriesScale.generateTickLabels (chart.mjs:10568:1)
    at TimeSeriesScale._convertTicksToLabels (chart.mjs:3154:1)
    at TimeSeriesScale.update (chart.mjs:2918:1)
    at fitBoxes (chart.mjs:4517:1)
    at Object.update (chart.mjs:4655:1)
    at Chart._updateLayout (chart.mjs:5771:1)
    at Chart.update (chart.mjs:5704:1)
    at new Chart (chart.mjs:5476:1)
    at renderChart (chart.tsx:42:1)
    at chart.tsx:98:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
```

**Comment by tsmock** [comment]
That is funny. It wasn't giving me that warning when I was working on it. And it is also erroring out for me too. Which makes me think I forgot to run `yarn install` or something.

Anyway, I'll see if I can fix this today.

**Comment by tsmock** [comment]
It should be fixed now. When I was working on this, chartjs was sending the tick value instead of the tick label to the calllback, and something changed somewhere so that the tick label was sent instead of the tick value. So instead of something like `"Jun 1"` being sent to the callback, I was getting `1685599200000`. So I _must have_ been using an outdated/borked version of a dependency somewhere.

**Comment by HelNershingThapa** [comment]
Getting the following error now:

```js
./node_modules/chart.js/dist/chart.js 559:18
Module parse failed: Unexpected token (559:18)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| };
| class DatasetController {
>   static defaults = {};
|   static datasetElementType = null;
|   static dataElementType = null;
```

**Comment by tsmock** [comment]
It looks like I had some stuff from #5908. Its probably the chartjs update that did that. I'll back that out and check and see if it works properly.

**Comment by tsmock** [comment]
It should be fine now (tested with `rm -rf node_modules && yarn install --check-files && yarn build && yarn start`).

**Review by HelNershingThapa — APPROVED** [review]
Thank you for fixing those warnings. I like how the tooltip format has been modified; it provides a more user-friendly touch. Although I personally preferred the display of months instead of YYYY-MM-DD, I appreciate the changes nonetheless.

**Comment by HelNershingThapa** [comment]
CircleCI is consistently failing ([9 times](https://app.circleci.com/pipelines/github/hotosm/tasking-manager?branch=fixup%2Fchartjs-warnings)) because of a failing test case with `src/views/tests/project.test.js (13.625 s)
  ● Project Detail Page › should render component details`, so I've been holding this off from being merged.

**Comment by tsmock** [comment]
FML. It worked both in the IDE and on the command line for me. I'll try multiple runs and see if it appears so I can debug it. :(

**Comment by HelNershingThapa** [comment]
I completely understand your frustration. This is the same test case issue we've been battling for a while now. In the past, CircleCI builds would typically pass, but unfortunately, this time, it didn't. 
 
Debugging this issue has been a headache for me as well. I think I'll take a shot at fixing warnings in `src/views/tests/project.test.js` in the hope that they magically start passing.

**Comment by tsmock** [comment]
If you are looking at fixing the forwardRef warnings, see 0de7dd20b2220000f0d2b0cd0d48e0c49c8ed7ec and (maybe) cd758ca2ab284e5f3c7ee704fc771a28df6d4e91.

**Comment by HelNershingThapa** [comment]
I had no intention of repairing those. I was aware that you had handled it on the larger PR, so I was looking for other warnings in 930545c . My attempt was futile; I split off from this PR and incorporated #5979 in [another branch](https://github.com/hotosm/tasking-manager/tree/fixup/chartjs-warnings-test), but the failing test still didn't pass.

**Comment by willemarcel** [comment]
@HelNershingThapa @ramyaragupathy When I commented out [this line](https://github.com/hotosm/tasking-manager/blob/d77c69ce80872d5ce49e05a114791e7174298271/frontend/src/views/tests/project.test.js#L222), the time spent running the test decreased from 599 to 119ms. So Maybe it could be a good solution, as you're testing if the user can see the project or not.

**Comment by HelNershingThapa** [comment]
Indeed @willemarcel, commenting out that particular line does improve the test execution time significantly and allows the test case to pass. It makes sense since the line checks the visibility of a comment in the "questions and comments" section.

After implementing this workaround, CircleCI encountered another similar issue. Another test case is now failing due to the same "timeout exceeded" problem (more info [here](https://app.circleci.com/pipelines/github/hotosm/tasking-manager/10467/workflows/8923a6a9-5438-4fb4-9ebb-e8b1b893064d/jobs/18397)) 🤯.

**Comment by willemarcel** [comment]
@HelNershingThapa this await doesn't look correct: https://github.com/hotosm/tasking-manager/blob/develop/frontend/src/components/teamsAndOrgs/tests/tasksStats.test.js#L28

**Comment by HelNershingThapa** [comment]
@willemarcel looks like so; it's using `expect` without an assertion. Thank you for catching that! I'll revise it and remove the `expect` function to see if it resolves the problem.

**Comment by HelNershingThapa** [comment]
The test in CircleCI still didn't pass after the removal of the 'expect' [here](https://app.circleci.com/pipelines/github/hotosm/tasking-manager/10477/workflows/e4bc5276-8619-41f6-bb84-be60583e3cba/jobs/18445). It seems there might be another issue causing the problem.

**Comment by tsmock** [comment]
I'd rather not drop parts of tests to make them faster. I've been trying to get profiling working with jest so that we can (hopefully) fix the slow paths instead of removing them from tests. I'm having to [eject](https://create-react-app.dev/docs/available-scripts/#npm-run-eject) react-scripts to do that, and convert to a module (I updated dependencies from react-scripts on chore/update-react-scripts branch after ejection, which had problems with non-modules).

I don't _think_ we currently want to completely remove `react-scripts` via ejection, but I could be wrong about that. If so, let me know, and I'll push those changes via a different PR.

**Comment by HelNershingThapa** [comment]
I completely agree with not dropping parts of the test case and I genuinely appreciate your support in finding a solution to the slow paths in the tests. It's reassuring to know you're looking into it.

Regarding your mention of ejecting, I believe it may introduce complexity while removing the abstraction that `react-scripts` provides. I think it would be wise to avoid ejecting from `react-scripts` unless it's absolutely necessary.

**Comment by willemarcel** [comment]
@HelNershingThapa I could reduce around 30% of the test time by removing the group role checks, but I see that the first test always takes 5x more time than the following ones, even if we just have a simple check on it. I would suggest increasing the timeout then.

Another thing that gave a good result in the time was to move the first render up to the describe section, but I don't know if it's a good practice.

**Comment by HelNershingThapa** [comment]
It's quite intriguing why something that passes quickly when executed individually encounters timeouts during comprehensive test runs. 

> I see that the first test always takes 5x more time than the following ones

It's likely due to warm-up overhead. Rearranging test order, such as making the second test the first, can indeed expose this effect, resulting in increased execution time for the test now taking the lead position.

> ...move the first render up to the describe section...

Wouldn't that introduce potential risks because it hinders test isolation?

**Comment by tsmock** [comment]
At one point in time, I experimented with using `jest.useFakeTimers()`, but something (I _think_ MSW) caused stuff to fail pretty much instantly. See https://github.com/mswjs/msw/issues/1390 . With that said, it was on a different branch with different dependency updates.

Anyway, I'll give some results from a profiling run (there has _got_ to be some better tools for that).

Significant amounts of time were spent in `lodash/_arrayLikeKeys` in the `taskSelection.test.js` class via `menubarRole.js` from `@testing-library/dom`. Overall, it looks like the calls to `_arrayLikeKeys` was ~49% of the total CPU calls (from Webstorm's `Top Calls` V8 CPU profiling pane). `jest-runtime` is the parent for all `_arrayLikeKeys` calls, and `@testing-library/dom` is the parent for those `jest-runtime` calls via an embedded `aria-query` library.

Looking at performance issues in the jest repository, I came across https://github.com/jestjs/jest/issues/11956, which indicates that `node --expose-gc --no-compilation-cache` _may_ fix the issue, at the cost of increasing overall test time. Unless it is due to the cost of `byRole` (see https://github.com/testing-library/dom-testing-library/issues/698 ), but that doesn't jive with the failing test (in CI) for `should render component details`.

As an additional detail, one of the tickets from dom-testing-library mentioned that jsdom is slow, so it might be worthwhile to check and see if we still need to run our tests using jsdom. @willemarcel added the `--env=jsdom` in f7f7e34f9af94704439b480f2ff00ef11d27d81f, if that helps jog memories as to why we have it.

**Comment by tsmock** [comment]
I just ran a bunch of tests on the develop branch and this branch.

The `develop` branch tests were run on a mac (100% pass rate) and on a linux box (~50% pass rate). The pass rate for the `chartjs` branch was a bit worse on the linux box (~33%).

The most common tests to "fail" were in src/views/tests/taskSelection.test.js (~66%), but I _suspect_ that the failing tests are generally flaky. I'm going to run a while loop  overnight, but I _suspect_ that all of the tests that failed in the `chartjs` branch will also fail in the `develop` branch, just at lower rates.

**Comment by tsmock** [comment]
Logs from running for several days (linux)
[develop-tasks.logs.tar.gz](https://github.com/hotosm/tasking-manager/files/13579619/develop-tasks.logs.tar.gz)
[chartjs-tasks.logs.tar.gz](https://github.com/hotosm/tasking-manager/files/13579624/chartjs-tasks.logs.tar.gz)

**Comment by tsmock** [comment]
I've looked for failing test files from the logs in the previous comment. Both of the linux runs were on the same box, run at the same time. I'll note that there are some cancellations counted in all environments (ctrl+c) due to OOM issues.

<details>
<summary>Failing test files</summary>

| File | chartjs (linux, 394 runs) | develop (linux, 385 runs) | develop (mac, 1029 runs) |
| ------------- |:-------------:|:----:|:----:|
| src/components/banner/tests/topBanner.test.js                     | 1 |   |   |
| src/components/contributions/tests/myProjectsDropdown.test.js     |   |   | 1 |
| src/components/header/tests/notificationBell.test.js              | 1 |   |   |
| src/components/homepage/tests/stats.test.js                       |   | 1 |   |
| src/components/notifications/tests/notificationBodyCard.test.js   | 1 |   |   |
| src/components/projectDetail/tests/questionsAndComments.test.js   |   |   | 2 |
| src/components/projectDetail/tests/similarProjects.test.js        |   | 1 | 1 |
| src/components/projects/tests/moreFiltersForm.test.js             |   |   | 2 |
| src/components/taskSelection/tests/contributions.test.js          | 6 | 5 |   |
| src/components/taskSelection/tests/action.test.js                 |   |   | 3 |
| src/components/taskSelection/tests/actionSidebars.test.js         |   |   | 1 |
| src/components/taskSelection/tests/contributions.test.js          |   |   | 6 |
| src/components/taskSelection/tests/index.test.js                  |   |   | 9 |
| src/components/taskSelection/tests/lockedTasks.test.js            | 2 | 1 |   |
| src/components/taskSelection/tests/resourcesTab.test.js           |   |   | 1 |
| src/components/taskSelection/tests/taskList.test.js               | 5 | 5 | 14 |
| src/components/teamsAndOrgs/tests/members.test.js                 | 1 |   |   |
| src/views/tests/management.test.js                                | 2 |   | 3 |
| src/views/tests/organisationManagement.test.js                    |   |   | 4 |
| src/views/tests/project.test.js                                   | 1 |   | 2 |
| src/views/tests/taskAction.test.js                                |   |   | 4 |
| src/views/tests/taskSelection.test.js                             | 33 | 27 | 30 |
| src/views/tests/teams.test.js                                     |   |   | 5 |
| src/views/tests/userDetail.test.js                                |   |   | 5 |
| src/views/tests/users.test.js                                     | 4 |   | 1 |
| Totals | 57 | 40 | 94 |
</details>

The absolute flakiest test file is src/views/tests/taskSelection.test.js.

**Comment by tsmock** [comment]
OK. It has taken me awhile, but I've figured out what is causing the test failures.

`React.lazy`.

In order to understand _why_ `React.lazy` is a problem, we must first understand how jest starts and times tests.
Specifically, jest will load all files required (so a file importing `foo` importing `bar` will load the file + `foo` + `bar` _before_ starting the tests). I don't know why it does the imports first, but the _effect_ of doing so is that it means that the _time_ of loading the imports is used against the tests.
By contrast, imports loaded via `React.lazy` are _loaded from disk dynamically_, and _are_ counted against the time for the test.

In other words,
1. jest loads test file
2. jest recursively resolves imports for the test file
3. jest starts tests
4. For each test
   1. Start a timer
   2. Run the test
      * If `React.lazy` is used somewhere, the additional imports required are resolved as the code executes.
   3. Stop the timer, report if the test took too long

So, how can we work around this import timing problem?
1. We can import the slow module in the test itself -- in this case, we _must_ document _why_ we have an unused import.
2. We can mock the slow module

Of the two problems, (1) is probably better, since it _should_ be more reliable (AKA: we don't have to keep mocks in sync with code).

**Comment by manjitapandey** [comment]
The graph on manage statistics page has differ from previous. The graphs previously shows adjacent individual pillars for tasks mapped and validated. However, the new one shows both mapped and validated tasks on single pillar. 

image
cc: @ramyaragupathy , @royallsilwallz

**Comment by tsmock** [comment]
It looks like this was a bug; the [original definitions](https://github.com/hotosm/tasking-manager/commit/e16552ae3ee9ce7d007401cc5312b1338dab4b95) (see #4103) for the graphs were
```javascript
    scales: {
      yAxes: [
        {
          stacked: true,
          ticks: {
            beginAtZero: true,
          },
        },
      ],
      xAxes: [
        {
          stacked: true,
        },
      ],
    },
```
If we want to keep the second style (side-by-side), we need to drop `stacked: true` from the axis definitions.

**Pull request merged**
