### PR TITLE
Project favorites API

### LINKED ISSUE #1602: Add Favorites model
Add database model to make possible to register a user favorite projects

Reference: https://projects.invisionapp.com/share/VCQTFR6YSJR#/screens/357652194

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
This PR enables an user to favorite a project on the backend side. Closes #1602 and #1603 

**How to test**
- Create a project using the API. You will receive a project_id.
- make a PUT request to /project/1/favorites to fav it.
- make again the same request to get an error stating that the project has been favorited before by the user.
- make a DELETE request to /project/1/favorites to unfavorite the project

**Note.** Tests have been included within the suite.

### CODE REVIEW

**Comment by JorgeMartinezG** [comment]
@ramyaragupathy I rebased with latest develop to put changes on top of it. I included the requested change

**Comment by ramyaragupathy** [comment]
There's also flask and black fixes that has to be made @JorgeMartinezG

**Comment by JorgeMartinezG** [comment]
@ramyaragupathy rebased branch including Black and flake checks. cc @xamanu

**Comment by xamanu** [comment]
@JorgeMartinezG still one little conflict here. Can you check?

**Comment by JorgeMartinezG** [comment]
@xamanu rebased, created new migration file on top of latest develop branch 👍

**Comment by thadk** [comment]
Am I doing something wrong?
image

**Comment by thadk** [comment]
This seems to work from my preliminary frontend. If the code looks good, lets get it merged. The only thing I would note is that the `favorite`/`favorites` spelling is American where the `organisation` spelling is British and it might be good to be consistent. @ramyaragupathy @JorgeMartinezG

**Comment by thadk** [comment]
Also the test isn't passing.

**Comment by JorgeMartinezG** [comment]
@thadk The branch has been force pushed again. It was a black check which failed

**Pull request merged**
