### PR TITLE
add task link into the message instead of the number

### PR DESCRIPTION
**Pull request by fiennyangeln**
@bgirardot Hi blake please see this update :D i have added the link

### CODE REVIEW

**Comment by smit1678** [comment]
thanks @fiennyangeln, this is related to https://github.com/hotosm/tasking-manager/pull/1051#issuecomment-373199547, correct?

**Comment by bgirardot** [comment]
@smit1678 I can test this now. but yes I am pretty sure this should be the needed adjustment to that item you linked to

**Comment by fiennyangeln** [comment]
@bgirardot hmm.. Ok i will try to reproduce the error and work on it

**Comment by bgirardot** [comment]
hi @fiennyangeln I was wondering if you had a chance to look into that error yet. I managed to run into a very similar error just now on our current development development branch:

`CRITICAL in validator_apis [/home/bg/tasking-manager/server/api/validator_apis.py:247]:
Validator Lock API - unhandled error: please run connect() first`

**Comment by ethan-nelson** [comment]
This is working great. Thanks! :+1:

**Comment by bgirardot** [comment]
@ethan-nelson This seems not to work. We are not getting the link directly to the task square in the message body.

2018-05-18_10h04_17

**Comment by bgirardot** [comment]
The validation email has this working correctly. It includes a link to the task.

**Comment by bgirardot** [comment]
This actually works correctly on stage, why would it not work on production? Has this not been merged to master yet? Ya, 5 days ago, that is probably after the dev to master merge? @dakotabenjamin @ethan-nelson sorry for my confusion.

**Pull request merged**
