### PR TITLE
[WIP] Add ability to generate auth token in user profile

### PR DESCRIPTION
**Pull request by uwaiszaki**
Backend->
1) This creates a Token API that receives a user authentication token by authorization headers.
2) If valid, generates another user authentication token. and
    returns the new authentication token.

### CODE REVIEW

**Comment by xamanu** [comment]
@uwaiszaki, sorry, our `develop` branch was rerolled. May I ask you to rebase this PR on the current `develop` branch, please. Thanks! :)

**Comment by xamanu** [comment]
This PR needs to be rebased on latest `develop`.

**Comment by JorgeMartinezG** [comment]
Hi @uwaiszaki . Thanks for contributing again. I have some questions: 

1. Could you please explain the purpose of generating a new token if the one which is read from headers is already valid?
2. Is possible to modify the API endpoint to different value like **/api/v1/auth/validate**? the reason is that **/auth/token** is reserved for token exchange between application and authorization servers when performing the authorization_code protocol for oauth2.

This one is more a comment, rather than a question:
3. I think that for APIs the server should keep consistency among data returned. With this PR, If the token is valid the format is string. When there is an error, an int value is returned. One possible option is to always return a json response. Something like:
```
Token ok --> {"status": 200, "token": "access_token"}
Not found --> {"status": 404, "error": "Token not found"}
Not valid --> {"status": 400, "error": "Invalid token"}
```

Again, thanks for this PR. Let me know your opinion! 😄

**Comment by ethan-nelson** [comment]
Please see the discussion at https://github.com/hotosm/tasking-manager/issues/1197#issuecomment-476454764 for more info--there has been a change of thinking and I don't think we want to enable this.

**Pull request closed without merging**
