### PR TITLE
Check on provided social media links in user profile

### PR DESCRIPTION
**Pull request by Nikitag0329IITkgp**
This is for issue https://github.com/hotosm/tasking-manager/issues/2710.

### CODE REVIEW

**Comment by xamanu** [comment]
I think it would be better to check the input than the output. This is causing an error when visiting the "My contributions" page: `TypeError: Cannot read property 'split' of undefined`

**Comment by ritvikjain99** [comment]
@Nikitag0329IITkgp you should add handling for the case when the value is empty that is when we want to return base URL itself and dont wanna append anything at the end !

**Comment by Nikitag0329IITkgp** [comment]
Hey, @xamanu can you have a look at it now?

**Comment by ramyaragupathy** [comment]
@Nikitag0329IITkgp - would you be able to create a separate PR here as this branch is unmanageable now with too many commits to follow?

**Pull request closed without merging**
