### PR TITLE
Add loader

### LINKED ISSUE #2167: Show loading progress for login delay
While logging in, there is a slight delay for the authentication, during which I can move around and click on the page for other actions. Ideally, I expect the page preventing further action till the login shows some result.

login-progress

### PR DESCRIPTION
**Pull request by ritvikjain99**
Initially all the loading and rendering after loading happening was visible to user.
After addition of LOADER before any loading related activity, especially LOGIN the loader is visible.
This loader can be extended to use with fetching of 'my tasks' and 'my contribution' related data.
Fixes #2167 
Before Loader:

ezgif com-video-to-gif-1

After Loader:

ezgif com-video-to-gif

### CODE REVIEW

**Comment by ritvikjain99** [comment]
@willemarcel don't know why checks are failing here, works fine on my pc !

**Comment by JorgeMartinezG** [comment]
@ritvikjain99 the errors found in circleci logs is:
```
Failed to compile.

./src/App.js
  Line 33:10:  'UsersList' is defined but never used  no-unused-vars
  Line 131:1:  'App' is a function                    no-func-assign
```

you can find more information by clickin the **Details** link here:

image

**Comment by ritvikjain99** [comment]
@JorgeMartinezG I have done the changes, please review !

**Comment by willemarcel** [comment]
@ritvikjain99 what are the advantages of using `react-preloaders` instead of React Suspense? It's adding 3 additional dependencies and more than 70 kb of data to the app. I don't see much advantage of showing loading status. But, if we decide to use it, we need something that represents a substantial better user experience than waiting the parts of the page to load.

**Comment by ritvikjain99** [comment]
@willemarcel sure I will use react-suspense for it. And as far as loading is concerned you can see in first video I posted, It makes the UX really bad if we just leave the components to load before user.
And here it's clearly not just loading but change in components. Initially first component was mounted then the other. That makes me feel that loader is really necessary here!

**Comment by ritvikjain99** [comment]
@willemarcel I have made a `<Preloader/>` component, which is ultra-light. The color of loader is consistent with our UI. Also I have suggestions for some really cool loaders which are appealing, catchy and engaging.

**Comment by willemarcel** [comment]
@ritvikjain99 I'm having trouble to rebase it with develop, could you squash your 4 commits in just one?

**Comment by ritvikjain99** [comment]
@willemarcel please review !

**Comment by ritvikjain99** [comment]
@willemarcel Thanks, I will consider your instructions keenly !

**Comment by ritvikjain99** [comment]
@willemarcel done !

**Comment by willemarcel** [comment]
@ritvikjain99 I rebased and improved the style on https://github.com/hotosm/tasking-manager/tree/loader

You replaced componentDidMount by componentWillMount, but that last one is going to be [removed from next react versions](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount).

**Comment by ritvikjain99** [comment]
@willemarcel yeah I am aware of that I was thinking to open an issue to port all class based components to functional components, and lifecycles methods to hooks, they being cleaner and easy-to-read.
Please guide what should I do next here !

**Comment by willemarcel** [comment]
> You replaced componentDidMount by componentWillMount, but that last one is going to be removed from next react versions.

I solved it and rebased develop on #2753

**Pull request closed without merging**
