### PR TITLE
Concising the states and stats on tasks

### LINKED ISSUE #1527: Incorrect completion stats
Hello,

I am working on a project which is 102% mapped whereas [a task](https://tasks.hotosm.org/project/5847?task=335#bottom) is not mapped.

image

### PR DESCRIPTION
**Pull request by xamanu**
Fixes #1527 (and follows up #1689).

This PR conceptualizes the tasks stats on projects as numbers that reflect the state, rather than any counting. Further it calculates the percentages of mapped, validated, and bad_imagery classified tasks on a project. In an migration the tasks stats on projects are getting recalculated and set.

### CODE REVIEW

**Comment by xamanu** [comment]
Oh, yes, thanks for spotting that @JorgeMartinezG! There was a confusion with the arguments. I reviewed and made it consistent. Please have a look again.

**Comment by xamanu** [comment]
Tests are failing. But locally they run through. I guess it is some temporal circle-ci trouble.

**Comment by xamanu** [comment]
Fixed the tests that were failing in circle-ci by mocking up some function.

**Comment by xamanu** [comment]
I tried again locally and it works fine. Project `5796` loads well and locking of tasks for validation is working.

**Comment by JorgeMartinezG** [comment]
I also tested locally. Found the previously written problems and now it is ok.

**Pull request merged**
