### PR TITLE
Updating contributing guidelines

### PR DESCRIPTION
**Pull request by petya-kangalova**
I have now simplified the labels list.   As discussed,  I have updated the contributing guidelines to reflect the changes and explain the different ways in which people can contribute.

The plan is to keep this page up to date with any changes/updates as we continue the collaboration with the collective.

### CODE REVIEW

**Review by Aadesh-Baral — APPROVED** [review]

**Comment by petya-kangalova** [comment]
@dakotabenjamin @Aadesh-Baral  I was going through the [contributor guidelines](https://github.com/hotosm/tasking-manager/blob/develop/docs/developers/contributing-guidelines.md) and realised that now it only refers to code contributions as opposed to all types of contributions as in this PR. How can I add this? Or are there two contributor.md files?

image

**Comment by petya-kangalova** [comment]
Discussed with DK and will need to add the changes from this PR to the  current  https://github.com/hotosm/tasking-manager/blob/develop/docs/developers/contributing-guidelines.md and ensure that non-code contributions are captured.

**Comment by petya-kangalova** [comment]
@jamattey if interested to look at the guidelines and add any comments.

**Comment by jamattey** [comment]
----
Date: 23rd October 2022.
Hello, @petya-kangalova here are a few suggestions for the contribution guidelines. 

- Translation of guidelines into other languages.
- User experience testing
- Issue submission guidelines

Submissions for technical contribution roadmaps from beginner to expert
- Introduction to git and GitHub
- Documentation on how to create a pull request in the tasking manager repo. 


> This will be edited with time. 

----

**Pull request merged**
