### PR TITLE
Add feature to mark all notifications as read

### LINKED ISSUE #5593: Add support to mark all notifications as read
**Is your feature request related to a problem? Please describe.**
I have a ton of unread notifications on my account. It's tedious to either open each notification or click on that eye-like icon to mark a notification as read. 

**Describe the solution you'd like**
I want to mark all of my notifications as read simultaneously. That would make it easier for me to keep track of newer unread notifications. Something similar to how mail platforms let you select all of your messages at once and mark them as read with the click of a button.
Mark all notifications as read

**Describe alternatives you've considered**
Mark all notifications as read when users leave the page that lists all notifications automatically, something similar to LinkedIn.

### PR DESCRIPTION
**Pull request by Aadesh-Baral**
closes #5593 

Major changes to the frontend:
- Adds a new component `ActionButtons`, that combines actions for deleting and marking multiple notifications as read.
- Adds a new component, `SelectAllNotifications`, that appears when all notifications in a page are selected and more notifications are under the active category tab. This component allows users to select all notifications under the active notification category and perform actions such as deleting and marking multiple notifications as read.
- Implemented refetching of notifications in the notification popup component when new notifications are available for the user. This change may potentially solve the issue mentioned in https://github.com/hotosm/tasking-manager/issues/5717
- Adds test cases for the newly introduced components.

### CODE REVIEW

**Comment by HelNershingThapa** [comment]
Now that users can select all notifications, we should also enable them to delete those notifications easily. Additionally, we should enhance the functionality of the notifications system by allowing users to mark notifications as read by category or through a search query. Specifically, we should add support for the following to improve usability:
- Marking multiple notifications as read
- Marking all notifications as read at once by category
- Deleting multiple notifications. This is currently supported by the `/notifications/delete-multiple/` endpoint.
- Deleting all notifications by category
- Marking notifications obtained by using a search query as read or deleting them

**Comment by Aadesh-Baral** [comment]
Currently, we have 11 different types of notifications sent to users.
```
SYSTEM: Generic system-generated message
BROADCAST: Broadcast message from a project manager
MENTION_NOTIFICATION: Notification that a user has been mentioned in a comment or chat.
VALIDATION_NOTIFICATION: Notification that the mapped task of the user has been validated
INVALIDATION_NOTIFICATION: Notification that the user's mapped task has been invalidated
REQUEST_TEAM_NOTIFICATION: Notification sent to team managers informing them that a user has requested to join the team.
INVITATION_NOTIFICATION: Notification sent to users when they are added to the team
TASK_COMMENT_NOTIFICATION: Notification that a comment has been made is sent to task contributors.
PROJECT_CHAT_NOTIFICATION: Notification of new comments on a project chat sent to users who have already commented there.
PROJECT_ACTIVITY_NOTIFICATION: Notification sent to users notifying that the project they have contributes has made a progress.
TEAM_BROADCAST: Broadcast message from a team manager to all team members.
```

I believe there should also be a discussion about the notification categories that are set at the top of the notifications page.

notification_groups


Here is what each of these categories represent:
- **Messages**: This category contains `MENTION_NOTIFICATION` , `SYSTEM`, `REQUEST_TEAM_NOTIFICATION` and `INVITATION_NOTIFICATION`.
- **Projects**: This category contains `BROADCAST`, `PROJECT_CHAT_NOTIFICATION` and `PROJECT_ACTIVITY_NOTIFICATION`.
- **Tasks**: This category contains `TASK_COMMENT_NOTIFICATION`, `VALIDATION_NOTIFICATION` and `INVALIDATION_NOTIFICATION`
- **Teams**: This category contains `REQUEST_TEAM_NOTIFICATION`, `INVITATION_NOTIFICATION` and `TEAM_BROADCAST`

The **_Messages_** category, in my opinion, is the most confusing of all because it contains very unrelated notification types and also overlaps with the **_Teams_** category.

@Ichchhie @ramyaragupathy @HelNershingThapa 

However, this could be a separate issue.

**Review by d-rita — COMMENTED** [review]
Unable to hit the delete-all and mark-as-read-all API endpoints as pointed out in this [thread](https://hotosm.slack.com/archives/C031PJXU874/p1683118742303339). cc: @Aadesh-Baral

**Comment by Aadesh-Baral** [comment]
@d-rita To hit the mark as read all  and delete all endpoints, you must have multiple page notifications. Can you verify this with multiple pages of notifications?

**Review by d-rita — COMMENTED** [review]
Tested this with multiple-page notifications. Hit the different endpoints accordingly. Works as expected functionality-wise.

**Review by ramyaragupathy — APPROVED** [review]
Works as expected

**Pull request merged**
