### PR TITLE
fix organisation tag to display only those with project list

### PR DESCRIPTION
**Pull request by fiennyangeln**
#881

### CODE REVIEW

**Comment by fiennyangeln** [comment]
Hi @bgirardot I tried fixing it and ordering it. Please try it :)

**Comment by bgirardot** [comment]
@fiennyangeln I am testing this now!

**Comment by bgirardot** [comment]
Quick feedback: So far it seems to be working great.

But we are not getting the "All" label selected on the initial load of the page:

2018-02-20_17h40_35

**Comment by bgirardot** [comment]
The label "all" is there, it just does not seem to get selected:

2018-02-20_17h42_16

**Comment by fiennyangeln** [comment]
hi @bgirardot thx for the feedback. I have tried removing the "". Hope it fixes the error :)

**Comment by bgirardot** [comment]
@fiennyangeln That seems to have broken something. I do get All now, but that is the only item that shows up in that popdown menu and I see this error in my console:

CRITICAL in tags_apis [/home/bg/tasking-manager/server/api/tags_apis.py:26]:
User GET - unhandled error: (psycopg2.ProgrammingError) syntax error at or near "''"
LINE 3: ... IS NOT NULL AND projects.organisation_tag IS NOT '' ORDER B...
                                                             ^
 [SQL: 'SELECT DISTINCT projects.organisation_tag AS projects_organisation_tag \nFROM projects \nWHERE projects.organisation_tag IS NOT NULL AND projects.organisation_tag IS NOT %(organisation_tag_1)s ORDER BY projects.organisation_tag'] [parameters: {'organisation_tag_1': ''}]

**Comment by fiennyangeln** [comment]
Hi @bgirardot i have tried to fix it. Please check it. I hope it works.

**Comment by bgirardot** [comment]
hi @fiennyangeln it no longer errors out, but it displays them with extra characters and such:

2018-02-21_18h58_15

**Comment by fiennyangeln** [comment]
Hi @bgirardot I have modified it. Please check it

**Comment by bgirardot** [comment]
@fiennyangeln This works great now!

@ethan-nelson or @pgiraud If you get a few minutes to review the code changes I will go ahead and merge them in.

functionally, it seems to work well in my testing, my main concern is if there is any impact on performance.

**Comment by bgirardot** [comment]
@fiennyangeln Whoops, I removed my previous comment, now I am not sure it is working. I can still select tags that do not have projects under them.

**Comment by bgirardot** [comment]
@fiennyangeln Yes, I get this error in the console of the server for some of the tags in the list:

CRITICAL in project_apis [/home/bg/tasking-manager/server/api/project_apis.py:300]:
Project GET - unhandled error: division by zero

When I select that tag, I get no project found and that error. 

I think there are actually no projects for the tag that causes that, at least I can not find any in the main Tasking Manager server, so there probably are none.

Again, we trying to get those out of the list of Organization tags, and it did used to work I think. I saw it remove tags from the list when I removed the tag from projects. I will keep testing.

**Comment by bgirardot** [comment]
Yes, I just do not quite understand what is going on.

I just tested this way:

I edited a project and added an organzation tag, just my name Blake
Then I went to contribute page, selected that organization from the list and it showed that project
I edited that project again, removed that organization tag, 
went back to the contribute page, shift reloaded
That organization was no longer listed, just as I would expect.

But there are a few tags in that list that have no projects and generate that division by zero error if I select them.

**Comment by fiennyangeln** [comment]
@bgirardot sorry.... too bad i cant seem to test it since my environment is not working at the moment..

**Comment by bgirardot** [comment]
@fiennyangeln Ok, ya, not sure how to help with the oauth thing. Mine is still working this morning.

I am also going to see if I can check on the actual production server to see if that same error is happening. It might be totally non related to your changes.

As I said, when I test these changes, they work, it removes campaign tags with no projects.

**Comment by fiennyangeln** [comment]
@bgirardot so the organisation tag with no project has disappear?

**Comment by bgirardot** [comment]
@fiennyangeln Yes, I can add an org tag, it shows up, take it off a project, it goes away from the list just as it should.

And.... I just tested this with the latest develop branch and that campaign tag still generates a div by zero error. 

so that makes me think it has nothing to do with your code at all.

I am back to asking @ethan-nelson or @pgiraud to review your code with an eye toward performance and general coding standards and if it looks ok to one or both of them, I will merge it in :)

**Comment by fiennyangeln** [comment]
wait.. do you say campaign tag? i suppose this change is only for organisation tag?

**Comment by bgirardot** [comment]
Did I say campaign tag? I mean Organization Tag.

For what it is worth the campaign tag needs to work the same way, but we are working on the organization tag at the moment.

**Comment by bgirardot** [comment]
Ya, my testing shows that there are 13 org tags that have no projects.

Your fix hides all of them but 5

2 of those 5 have the div by 0 error that shows up in the main branch anyway.

**Comment by fiennyangeln** [comment]
I think I might need to read the documentation of the Project model first. 

As of now, what I do is like, for every project inside the database, I get the organisation_tag attribute, remove duplicate among them, then return and show it. So I think it is supposed to work.. 

Through your error, I want to ask, is it possible for a project to have count of all tasks similar to count of the tasks' bad imagery? Or is it possible for a project to have zero tasks? If thats the case, then it might be what causes the ZeroDivisionError

**Comment by bgirardot** [comment]
@fiennyangeln As far as I know a Project should always have at least one Task. There should be no way to create a project that no tasks. That does not mean it does not happen somehow, but it should not be possible.

**Comment by fiennyangeln** [comment]
hi @bgirardot there is private attribute inside the project. is it the case that the private project is not supposed to be displayed in the page? if it is, then the organisation tag might come from those private project. what do you think?

**Comment by bgirardot** [comment]
@fiennyangeln The private project thing should not be the problem. That should just restrict who can checkout out a task (restricts it to a list of osm usernames the project manager enters by hand), but it should not make them invisible to searching.

I can give you access to a recent clone of the production database that you can connect to via the pg client if you want to explore the actual data and see if you can tell why some of these organization tags either div by 0 error, and why some, still show up even if they return no projects.

**Comment by fiennyangeln** [comment]
Ok please send the access to my email fiennyangeln@gmail.com

**Comment by fiennyangeln** [comment]
hi @bgirardot I have tried to adjust the query based on the project search. pls try. Moreover, for the project search, does it only display those with status PUBLISHED?

**Comment by bgirardot** [comment]
@fiennyangeln No, not for a project manager, we have checkboxes to include draft, archived and published on that "contribute" list
 If you log into that sample online db or even in your local test db, you should have logged in once and set yourself to a project admin so you see checkboxes on the left "include draft" "include archived"

**Comment by fiennyangeln** [comment]
I see.. thats OK then! :)

**Comment by bgirardot** [comment]
@ethan-nelson Do you know what we need to do so this passes the tests and we can review it again?

**Comment by ethan-nelson** [comment]
@bgirardot It should work if we merge develop into this PR. I believe the issue was the Dockerfile/deployment where we had to "freeze" the version instead of using the latest.

**Comment by ethan-nelson** [comment]
Due to the need to update the branch, I have opened up #1148 with the commits from this PR and a recent merge of `develop` . Further testing will take place on that PR. Thanks to @fiennyangeln for all the help on this!

**Comment by fiennyangeln** [comment]
@ethan-nelson np! sorry I get busy lately! thanks for merging the commit

**Comment by ethan-nelson** [comment]
no problem!

**Pull request closed without merging**
