### PR TITLE
 Feature/redesign ProjectCard

### PR DESCRIPTION
**Pull request by thadk**
Initial work for new React frontend around project cards for #1628. Added a featuredProjects component to home page, and will support local pagination using red left/right arrows.

(With black instead of white-based organization logos)
image

image

image

### CODE REVIEW

**Comment by willemarcel** [comment]
Hi @thadk 

I pushed some improvements to https://github.com/hotosm/tasking-manager/commit/604271cd8b58789028d5bd65aa7ccc806dcb5e32 . Don't worry about  linting. I'm planning to add `prettier`.

Some details I found:

- [ ] The tooltip didn't show when the mouse is over the progress bar, but when it's almost on the bottom border of the card.
- [ ] We need a tooltip for validated percentage and another to mapped. For me only the validated is shown.
- [ ] The due date box wasn't exhibited here, I checked the API result and the project has a due date.
- [ ] On the image below, we can see `...` below the project title. Is it a replacement to some missing information?
- [ ] 2 tests are failing.

Screenshot from 2019-07-31 19-05-22

**Comment by thadk** [comment]
> Hi @thadk
> 
> I pushed some improvements to [604271c](https://github.com/hotosm/tasking-manager/commit/604271cd8b58789028d5bd65aa7ccc806dcb5e32) . Don't worry about linting. I'm planning to add `prettier`.
> 
> Some details I found:
> 
>     * [ ]  The tooltip didn't show when the mouse is over the progress bar, but when it's almost on the bottom border of the card.
This was happening because of the new `shadow-hover` hovering background.

>     * [x]  We need a tooltip for validated percentage and another to mapped. For me only the validated is shown.
Not sure why only validation was appearing but I have moved the "Mapping %" hover to the full width div instead of the mapping div so it doesn't happen.

>     * [ ]  The due date box wasn't exhibited here, I checked the API result and the project has a due date.
I will modify my database and check this late today. Are you sure the due date is still in the future on your database? It never appears for past-due dates.

>     * [ ]  On the image below, we can see `...` below the project title. Is it a replacement to some missing information?
This was only happening with the test database items, not for the real items from the live server. Not sure what is special about them yet. 
I like the idea of truncating project titles in the CSS but maybe this is better to do in the React code? Have you seen any good libraries?

>     * [x]  2 tests are failing.
Thanks, renamed and fixed. Hope there is only 1 test for now on this branch.

**Comment by willemarcel** [comment]
> I like the idea of truncating project titles in the CSS but maybe this is better to do in the React code? Have you seen any good libraries?

I have never used a library to do it. Don't care too much about it, we can communicate with the project managers to use a max title length or refine the implementation on the future.

**Comment by thadk** [comment]
@willemarcel I think I have resolved each of your concerns!

**Comment by willemarcel** [comment]
Merged with https://github.com/hotosm/tasking-manager/pull/1817

**Pull request closed without merging**
