### PR TITLE
Service Desk link addition to Navigation 

### PR DESCRIPTION
**Pull request by ramyaragupathy**
From #5017 - made frontend changes to let access Jira Service desk through Tasking Manager. This link can be used to report any issues that the users encounter with the application.

@d-rita - here is a snapshot from my local testing

image

The  external link always is appended to the base link. Can you please help figure out what more changes are needed to make this work?

### CODE REVIEW

**Comment by d-rita** [comment]
The Link component is mostly used to route within the application. So, for external links, we go with the anchor tag, `<a />`. That way, the service desk link will not be appended to the site URL before redirecting. 

Additionally, the changes added so far only affect the popup menu. 
popup

To affect the navbar displayed on larger screens, we'd have to apply the same changes to this [part](https://github.com/hotosm/tasking-manager/blob/fb77daece5e0741f6eab12c8f54fb3cae8685cc0/frontend/src/components/header/index.js#L163).

**Comment by zlavergne** [comment]
Just a nitpick, since this is an external link in a navbar, could we add an icon to denote it's external. Like this: https://fontawesome.com/v5/icons/external-link-alt?s=solid

**Comment by HelNershingThapa** [comment]
An anchor tag has been added for the support link. Like @zlavergne suggested, an external link icon has also been added.
support-big

Popup:
support-small

**Comment by dakotabenjamin** [comment]
Is this still WIP?

**Comment by HelNershingThapa** [comment]
@dakotabenjamin it's done

**Pull request merged**
