### PR TITLE
Restrict editor programs

### PR DESCRIPTION
**Pull request by zlavergne**
Restrict editor programs for mapping and validation stages

>**This PR includes a db migration**

Related Issue: #893

* Added list of editors in the `Settings` menu of a project-edit page where a project manager can select permitted editors for each editing stage
Screen Shot 2019-03-21 at 10 37 50 AM

* Updated the editor dropdown for to populate only with the permitted editors
Screen Shot 2019-03-25 at 12 28 35 PM

### CODE REVIEW

**Comment by xamanu** [comment]
Thanks, @zlavergne for this PR! Can you please rebase this on the latest `develop`. Sorry this changed just today.

**Comment by zlavergne** [comment]
@xamanu Rebased

**Comment by zlavergne** [comment]
Rebased with latest from `develop`

**Comment by xamanu** [comment]
@zlavergne May you please rebase again. Now latest `develop` shall be stable. Thanks.

**Comment by xamanu** [comment]
Closing in favour of a rerolled the PR #1487 on the local repository.

**Pull request closed without merging**
