### PR TITLE
Apply Github recommended security patches

### PR DESCRIPTION
**Pull request by hunt3ri**
Took a look at the issue with security vulnerabilities flagged by GitHub

* PyYAML is a dependency of flask-swagger.  So I upgraded flask-swagger, which brought in v5.1 of PyYAML.  (I tested locally and docs still work).
* UrlLib3 is a dependency of the transifex-client.  Upgrading to latest had the bonus of updating both urlib3 and requests.  

I am unable to test transifex client locally, but looking at the releases page on github [transifex releases](https://github.com/transifex/transifex-client/releases) I'm not seeing any evidence of breaking changes so I think applying will be low risk, and probably better to fix forward in any case.

Thanks

### CODE REVIEW

**Comment by xamanu** [comment]
Thank you very much @hunt3ri for this PR. I will test it later today.

**Comment by xamanu** [comment]
Are we ready to get rid of `newrelic`? (@dakotabenjamin and @arunasank)

**Comment by hunt3ri** [comment]
@xamanu yes I thought I'd deleted newrelic too, but pip freeze just puts everything in alaphabetical order 😄

**Comment by dakotabenjamin** [comment]
Note that our AWS deployment use `requirements.aws.txt`

**Comment by hunt3ri** [comment]
Hi @dakotabenjamin I think that's because the awsebcli depends on an ancient version of requests.  I can put in seperate PR to update to the latest awsebcli, which will hopefully use a newer version of requests by now.

Pretty sure that will be compatibile with existing deploy shell scripts.

**Comment by xamanu** [comment]
Rebased on `develop` for further testing.

**Comment by xamanu** [comment]
In [this branch](https://github.com/hotosm/tasking-manager/commits/aws-requirements) I started updating the `requirements.aws.txt`.

**Comment by xamanu** [comment]
Just for the record: @hunt3ri and @dakotabenjamin The building error is simply caused by node version 10 in the circle-ci config file: #1427

**Comment by hunt3ri** [comment]
Thanks for the quick merge @xamanu and for updating awsebcli, nice work 👍

**Pull request merged**
