### PR TITLE
Configurable devevelopment port & documentation updates

### PR DESCRIPTION
**Pull request by spwoodcock**
### Problem

- The docker compose setup for development uses Traefik on port 80.
- On many machines port 80 is not an option: either in use, or not available in rootless mode.
- The container names are also a mix of conventions: two being automatically generated, two being manually specified.
- The development setup guide is also missing a few things to get started easily.

### Solution

- Added a `TM_DEV_PORT` variable to the dotenv options, so the port can be configured.
- Updated all containers to have consistent names. I prepended `tm-` to prevent conflict with other tools that may have containers named `backend` and `frontend`.
- Updated the development setup guide:
  - Info on running via docker.
  - How to set up OSM OAuth creds.

### Context

- @robsavoye was having some issues setting up Tasking Manager for testing.
- I realised there isn't actually a guide for running the entire stack in Docker during development, which I assume some people would want to do.

----------------------------------------

**2024-02-02 15:35 Update/Edit**:
- I removed info about using pep582, as this was blocked by the python steering comity (😢)
- I noticed an unpinned pdm version during functional tests in CI. I pinned to the same as others in the repo. 
- Clarified info about running backend api only.

### CODE REVIEW

**Comment by robsavoye** [comment]
There are two different docs on using docker with TM, but since docker wasn't working, I could update and merge the two docs.

**Comment by spwoodcock** [comment]
Where is the second doc? I couldn't find it.

I found a guide for installing TM via docker for deployment, but no complete guide for running via docker during development.

**Comment by robsavoye** [comment]
one is in docs-old, the other in in an old PR from Outreachy last year. I'm trying to get rid of docs-old by updating the docs, and moving them all to docs. Once I can get docker to work, I can merge and update a single doc.

**Comment by robsavoye** [comment]
The old one I was planning to merge in is here: https://github.com/hotosm/tasking-manager/pull/5621. You're welcome to update a doc on docker usage for TM. :-)

**Comment by spwoodcock** [comment]
Looks fine to me - that one is for deployment specifically though.

I know they are similar, but we need a doc for how to deploy, and a doc for how to develop using docker.

**Comment by robsavoye** [comment]
For a doc on docker, I was thinking about a simple howto user guide. Basically an interested contributor should be able to clone the TM git repo, run docker-compose, and try TM in a self-hosted environment. I do this all the time when evaluating other projects, and if it doesn't work out of the box, that ends the evaluation most of the time.

**Comment by spwoodcock** [comment]
To do that I think we should just update the `example.env` to use defaults for the docker based setup. 

Then change the port binded to traefik by default to any >1024.

After that a user could simply:

```bash
git clone https://github.com/hotosm/tasking-manager

cp example.env tasking-manager.env

docker compose up -d
```

**Comment by robsavoye** [comment]
I like making it really easy for people to download and evaluate TM locally using docker.

**Comment by spwoodcock** [comment]
I will make another PR updating as above & adding some info to the docs then 👍

**Pull request merged**
