### PR TITLE
Rearrange buttons for mapping tab

### PR DESCRIPTION
**Pull request by ramyaragupathy**
Per discussion in #1181 - there's already a [PR to add icons](https://github.com/hotosm/tasking-manager/pull/1206). This PR is for modifying the buttons layout.

image

### CODE REVIEW

**Comment by ramyaragupathy** [comment]
Still testing the functionality of the buttons locally. Will request a review once the local testing is complete.

**Comment by ramyaragupathy** [comment]
Good for review.

**Comment by smit1678** [comment]
Nice @ramyaragupathy. One quick response to the image. I saw that you added two comment boxes. Should we just keep one to keep it simple for the user? Or did you have some other thinking there? 

tasking-manager 2018-10-10 10-42-10

**Comment by ramyaragupathy** [comment]
Agree that it is simple to keep one comment box. My thinking was to have one comment box next to each action buttons. I understand it is confusing and not useful for the end-user experience. Removing it.

**Comment by ramyaragupathy** [comment]
Screenshot after the merge
image

**Comment by Blake-Loveland** [comment]
What do you think about making the Mark Completely mapped button the same color as a mapped task to help reinforce that color meaning?

**Comment by smit1678** [comment]
To add to the discussion here, I think for now we should stick with the two types of button colors that we have across the site: brown or orange. If we introduce another color, I feel like this might just look more confusing. My suggestion is that if we think orange sticks out too much, we go with brown so all the mapping actions have equal weight.

**Pull request merged**
