### PR TITLE
Document frontend rebuilding instructions for Docker-Compose setup

### PR DESCRIPTION
**Pull request by theprover97**
Added a line of code to help in building of Tasking-Manager after use of docker-compose.

### CODE REVIEW

**Comment by theprover97** [comment]
Sure @xamanu , fixing the Dockerfile would indeed be better. Thanks.

**Comment by xamanu** [comment]
Referencing a PR for the Docker improvements #1480

**Comment by JorgeMartinezG** [comment]
@theprover97 The Dockerfile already merged in develop branch includes the built client already within the image. Please, let me know if you encounter new issues. Thanks for this contribution 👍

**Comment by theprover97** [comment]
Thanks for your contribution @JorgeMartinezG . I am currently running the Tasking-Manager on Ubuntu 18.10, but it stops at step 4 due to unresolved debian security issue. On running it on lesser versions, it throws an error at step 7 stating cannot connect to github.com due to connection time out. How can we resolve this?

**Comment by JorgeMartinezG** [comment]
@theprover97 one possible workaround is to change the `git clone` command to `COPY . .`. Could you please create an issue with your computer/docker version?

**Comment by theprover97** [comment]
Could you please tell me how to use the COPY . command? I am not getting it.

**Comment by theprover97** [comment]
The same errors are showing up in the latest Ubuntu release of 19.04 (Error at step 4 itself) in bilding the tasking manager using docker-compose. Should we open an issue for this?

**Comment by JorgeMartinezG** [comment]
@theprover97 to update:
- `COPY` commands copies data from your host computer into the docker image. 
- Related to the docker build error, you can modify step 4 by changing the remote to use https protocol over git, like `https://github.com/hotosm/tasking-manager.git`.
- Yes, feel free to create a new issue with your computer setup

**Comment by theprover97** [comment]
@JorgeMartinezG , I have opened an Issue for the same #1545 . Thanks!!

**Comment by xamanu** [comment]
I think this is obsolete with the introduction of the `Makefile` and the related documentation #1498

**Pull request closed without merging**
