### PR TITLE
Release to master

### PR DESCRIPTION
**Pull request by smit1678**
This PR updates the `master` branch to deploy a new release to HOT production.

Todo: list changes/updates here

@bgirardot @dakotabenjamin @ethan-nelson Will follow up on slack to coordinate final testing.

### CODE REVIEW

**Comment by ethan-nelson** [comment]
Changelog:
* Removed duplicate results from search when using non-English locale
* Updated existing translations
* Added new languages available for translation
* Described opt-out process in email text (functionality added in previous release)
* Allowed users to see archived tasks
* Added a `mark all tasks mapped` feature for project managers
* Fixed online user and completion statistics
* Included user invalidation count in API
* Corrected link to Missing Maps profiles
* Added link anchors to learning page
* Labeled priority on project cards in search
* Minor GPX file fix

**Comment by ethan-nelson** [comment]
I tested mostly everything I could...email text and stats were difficult to test alone, but when I at least `marked all tasks mapped` for one project, it was at 100% mapped when there were bad imagery tasks existing, which is what we wanted.

**Comment by ethan-nelson** [comment]
Blake or someone, if you want to try validating https://tasks-stage.hotosm.org/project/529?task=3 I can make sure the message is right (I don't see why it shouldn't be).

**Comment by bgirardot** [comment]
@ethan-nelson I just validated that task.

**Comment by ethan-nelson** [comment]
@bgirardot got the updated message, thanks!

**Comment by smit1678** [comment]
> Changelog:

@ethan-nelson awesome, thank you for assembling the changelog 👍

**Pull request merged**
