### PR TITLE
Error on create or edit in campaigns and categories

### PR DESCRIPTION
**Pull request by NoemiNahomy**
closes [#2631](https://github.com/hotosm/tasking-manager/issues/2630)
please review @xamanu

### CODE REVIEW

**Comment by JorgeMartinezG** [comment]
Thank you @NoemiNahomy . Could you please modify also for **backend/api/projects/resources.py**?  Then, please squash into a single commit

**Comment by NoemiNahomy** [comment]
@JorgeMartinezG If I can, I check it.

**Comment by NoemiNahomy** [comment]
@JorgeMartinezG  changes made, please review

**Comment by JorgeMartinezG** [comment]
good to go. Thank you!

**Pull request merged**
