### PR TITLE
Add linter (ESLint) for JS files

### PR DESCRIPTION
**Pull request by dkocich**
Related to https://github.com/hotosm/tasking-manager/issues/1038

This adds Gulp task to log errors found by the linter. Linter settings can be adjusted before merging but I would leave fixing linter suggestions to separate PRs. It can be added to CI later too.

Current ESLint log is here:
```
C:\git\tasking-manager\client>gulp eslint
[13:32:01] Using gulpfile C:\git\tasking-manager\client\gulpfile.js
[13:32:02] Starting 'eslint'...
The rule `angular/service-name` will be split up to different rules in the next version. Please read the docs for more information
[13:33:32]
C:\git\tasking-manager\client\gulpfile.js
   76:58  error  Missing semicolon  semi
  125:32  error  Missing semicolon  semi
  132:32  error  Missing semicolon  semi

C:\git\tasking-manager\client\app\taskingmanager.app.js
  10:57   error  You should use the $inject syntax for DI                          angular/di
  16:74   error  You should use the $inject syntax for DI                          angular/di
  20:34   error  You should use the angular.fromJson method instead of JSON.parse  angular/json-functions
  34:115  error  You should use the $inject syntax for DI                          angular/di

C:\git\tasking-manager\client\app\taskingmanager.config.js
  1:44   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
  2:936  error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style

C:\git\tasking-manager\client\app\about\about.controller.js
   8:5   error  The aboutController controller should follow this pattern: /[A-Z].*Controller$/  angular/controller-name
  56:10  error  Missing semicolon                                                                semi

C:\git\tasking-manager\client\app\components\fileread.directive.js
  34:10  error  Missing semicolon  semi

C:\git\tasking-manager\client\app\home\home.controller.js
   8:5   error  The homeController controller should follow this pattern: /[A-Z].*Controller$/               angular/controller-name
  12:5   error  You should use the $inject syntax for DI                                                     angular/di
  31:17  error  You should use the "log" method of the AngularJS Service $log instead of the console object  angular/log

C:\git\tasking-manager\client\app\login\auth.controller.js
   8:5  error  The authController controller should follow this pattern: /[A-Z].*Controller$/  angular/controller-name
  12:5  error  You should use the $inject syntax for DI                                        angular/di

C:\git\tasking-manager\client\app\login\login.controller.js
   8:5  error  The loginController controller should follow this pattern: /[A-Z].*Controller$/  angular/controller-name
  12:5  error  You should use the $inject syntax for DI                                         angular/di

C:\git\tasking-manager\client\app\contribute\contribute.controller.js
    8:5   error  The contributeController controller should follow this pattern: /[A-Z].*Controller$/  angular/controller-name
   12:5   error  You should use the $inject syntax for DI                                              angular/di
  150:67  error  Missing semicolon                                                                     semi

C:\git\tasking-manager\client\app\profile\profile.controller.js
   8:5   error  The profileController controller should follow this pattern: /[A-Z].*Controller$/  angular/controller-name
  12:5   error  You should use the $inject syntax for DI                                           angular/di
  69:15  error  Missing semicolon                                                                  semi

C:\git\tasking-manager\client\app\profile\validate-email.controller.js
  12:5  error  You should use the $inject syntax for DI  angular/di

C:\git\tasking-manager\client\app\project\project-dashboard.controller.js
  12:5   error  You should use the $inject syntax for DI  angular/di
  40:51  error  Missing semicolon                         semi

C:\git\tasking-manager\client\app\project\project.controller.js
     9:5   error  The projectController controller should follow this pattern: /[A-Z].*Controller$/                     angular/controller-name
    13:5   error  You should use the $inject syntax for DI                                                              angular/di
   142:11  error  Missing semicolon                                                                                     semi
   165:10  error  Missing semicolon                                                                                     semi
   169:10  error  Missing semicolon                                                                                     semi
   178:10  error  Missing semicolon                                                                                     semi
   193:10  error  Missing semicolon                                                                                     semi
   446:22  error  Missing semicolon                                                                                     semi
   662:74  error  Missing semicolon                                                                                     semi
  1229:22  error  Missing semicolon                                                                                     semi
  1240:22  error  Missing semicolon                                                                                     semi
  1251:35  error  You should not use directly the "undefined" keyword. Prefer angular.isUndefined or angular.isDefined  angular/definedundefined
  1275:18  error  Missing semicolon                                                                                     semi
  1459:61  error  Missing semicolon                                                                                     semi

C:\git\tasking-manager\client\app\message\inbox.controller.js
   8:5  error  The inboxController controller should follow this pattern: /[A-Z].*Controller$/  angular/controller-name
  12:5  error  You should use the $inject syntax for DI                                         angular/di

C:\git\tasking-manager\client\app\message\message.controller.js
   8:5  error  The messageController controller should follow this pattern: /[A-Z].*Controller$/  angular/controller-name
  12:5  error  You should use the $inject syntax for DI                                           angular/di

C:\git\tasking-manager\client\app\services\account.service.js
   7:5   error  You should prefer the factory() method instead of service()  angular/no-service-method
  11:5   error  You should use the $inject syntax for DI                     angular/di
  44:18  error  Missing semicolon                                            semi
  76:15  error  Missing semicolon                                            semi

C:\git\tasking-manager\client\app\services\auth.service.js
   7:5   error  You should prefer the factory() method instead of service()         angular/no-service-method
  11:5   error  You should use the $inject syntax for DI                            angular/di
  68:59  error  You should use the angular.toJson method instead of JSON.stringify  angular/json-functions

C:\git\tasking-manager\client\app\services\draw.service.js
  10:5  error  You should prefer the factory() method instead of service()  angular/no-service-method
  14:5  error  You should use the $inject syntax for DI                     angular/di

C:\git\tasking-manager\client\app\services\editor.service.js
    7:5   error  You should prefer the factory() method instead of service()              angular/no-service-method
   11:5   error  You should use the $inject syntax for DI                                 angular/di
  100:55  error  Missing semicolon                                                        semi
  102:31  error  Missing semicolon                                                        semi
  119:26  error  You should use the $window service instead of the default window object  angular/window-service

C:\git\tasking-manager\client\app\services\geospatial.service.js
    7:5   error  You should prefer the factory() method instead of service()  angular/no-service-method
  182:18  error  You should use the angular.isArray method                    angular/typecheck-array
  193:32  error  Missing semicolon                                            semi

C:\git\tasking-manager\client\app\services\httpInterceptor.service.js
  14:5  error  You should use the $inject syntax for DI  angular/di

C:\git\tasking-manager\client\app\services\language.service.js
  7:5  error  You should prefer the factory() method instead of service()  angular/no-service-method

C:\git\tasking-manager\client\app\services\license.service.js
   7:5  error  You should prefer the factory() method instead of service()  angular/no-service-method
  11:5  error  You should use the $inject syntax for DI                     angular/di

C:\git\tasking-manager\client\app\services\map.service.js
    4:5    error  You should prefer the factory() method instead of service()  angular/no-service-method
   12:5    error  You should use the $inject syntax for DI                     angular/di
   82:156  error  Missing semicolon                                            semi
   85:153  error  Missing semicolon                                            semi
  197:15   error  Missing semicolon                                            semi

C:\git\tasking-manager\client\app\services\message.service.js
   7:5  error  You should prefer the factory() method instead of service()  angular/no-service-method
  11:5  error  You should use the $inject syntax for DI                     angular/di

C:\git\tasking-manager\client\app\services\project.service.js
    4:5   error  You should prefer the factory() method instead of service()       angular/no-service-method
   14:5   error  You should use the $inject syntax for DI                          angular/di
  153:30  error  You should use the angular.fromJson method instead of JSON.parse  angular/json-functions
  245:69  error  Missing semicolon                                                 semi
  269:67  error  Missing semicolon                                                 semi
  455:15  error  Missing semicolon                                                 semi
  478:15  error  Missing semicolon                                                 semi
  500:15  error  Missing semicolon                                                 semi

C:\git\tasking-manager\client\app\services\projectMap.service.js
    7:5    error  You should prefer the factory() method instead of service()  angular/no-service-method
   11:5    error  You should use the $inject syntax for DI                     angular/di
  121:53   error  Missing semicolon                                            semi
  299:109  error  Missing semicolon                                            semi

C:\git\tasking-manager\client\app\services\search.service.js
   7:5   error  You should prefer the factory() method instead of service()  angular/no-service-method
  11:5   error  You should use the $inject syntax for DI                     angular/di
  43:15  error  Missing semicolon                                            semi
  69:15  error  Missing semicolon                                            semi

C:\git\tasking-manager\client\app\services\settings.service.js
   7:5   error  You should prefer the factory() method instead of service()  angular/no-service-method
  11:5   error  You should use the $inject syntax for DI                     angular/di
  39:15  error  Missing semicolon                                            semi

C:\git\tasking-manager\client\app\services\stats.service.js
   7:5   error  You should prefer the factory() method instead of service()                                  angular/no-service-method
  11:5   error  You should use the $inject syntax for DI                                                     angular/di
  96:13  error  You should use the "log" method of the AngularJS Service $log instead of the console object  angular/log

C:\git\tasking-manager\client\app\services\style.service.js
  10:5   error  You should prefer the factory() method instead of service()  angular/no-service-method
  38:54  error  Missing semicolon                                            semi
  81:52  error  Missing semicolon                                            semi
  84:47  error  Missing semicolon                                            semi
  87:50  error  Missing semicolon                                            semi
  90:51  error  Missing semicolon                                            semi

C:\git\tasking-manager\client\app\services\tag.service.js
   7:5  error  You should prefer the factory() method instead of service()  angular/no-service-method
  11:5  error  You should use the $inject syntax for DI                     angular/di

C:\git\tasking-manager\client\app\services\task.service.js
   7:5  error  You should prefer the factory() method instead of service()  angular/no-service-method
  11:5  error  You should use the $inject syntax for DI                     angular/di

C:\git\tasking-manager\client\app\services\user.service.js
    7:5   error  You should prefer the factory() method instead of service()  angular/no-service-method
   11:5   error  You should use the $inject syntax for DI                     angular/di
   46:15  error  Missing semicolon                                            semi
   69:15  error  Missing semicolon                                            semi
   93:15  error  Missing semicolon                                            semi
  117:15  error  Missing semicolon                                            semi
  140:15  error  Missing semicolon                                            semi
  184:15  error  Missing semicolon                                            semi
  206:15  error  Missing semicolon                                            semi
  229:15  error  Missing semicolon                                            semi

C:\git\tasking-manager\client\app\services\userPreferences.service.js
   8:5   error  You should prefer the factory() method instead of service()         angular/no-service-method
  12:5   error  You should use the $inject syntax for DI                            angular/di
  33:33  error  You should use the angular.fromJson method instead of JSON.parse    angular/json-functions
  36:70  error  You should use the angular.toJson method instead of JSON.stringify  angular/json-functions
  53:49  error  Missing semicolon                                                   semi
  62:66  error  You should use the angular.toJson method instead of JSON.stringify  angular/json-functions

C:\git\tasking-manager\client\app\admin\dashboard\dashboard.controller.js
   8:5  error  The dashboardController controller should follow this pattern: /[A-Z].*Controller$/  angular/controller-name
  12:5  error  You should use the $inject syntax for DI                                             angular/di

C:\git\tasking-manager\client\app\admin\create-project\create-project.controller.js
   12:5   error  You should use the $inject syntax for DI  angular/di
  256:51  error  Missing semicolon                         semi
  257:15  error  Missing semicolon                         semi
  275:10  error  Missing semicolon                         semi
  375:54  error  Missing semicolon                         semi
  490:63  error  Missing semicolon                         semi

C:\git\tasking-manager\client\app\admin\licenses\license-edit.controller.js
  12:5  error  You should use the $inject syntax for DI  angular/di

C:\git\tasking-manager\client\app\admin\licenses\licenses.controller.js
   8:5   error  The licensesController controller should follow this pattern: /[A-Z].*Controller$/  angular/controller-name
  12:5   error  You should use the $inject syntax for DI                                            angular/di
  34:10  error  Missing semicolon                                                                   semi

C:\git\tasking-manager\client\app\admin\users\users.controller.js
   8:5  error  The usersController controller should follow this pattern: /[A-Z].*Controller$/  angular/controller-name
  12:5  error  You should use the $inject syntax for DI                                         angular/di

C:\git\tasking-manager\client\app\components\account-nav\account-nav.directive.js
  33:5  error  You should use the $inject syntax for DI  angular/di

C:\git\tasking-manager\client\app\components\add-layer\add-layer.directive.js
  35:5   error  You should use the $inject syntax for DI  angular/di
  63:10  error  Missing semicolon                         semi

C:\git\tasking-manager\client\app\admin\edit-project\edit-project.controller.js
   12:5   error  You should use the $inject syntax for DI                                                              angular/di
  369:15  error  Missing semicolon                                                                                     semi
  398:15  error  Missing semicolon                                                                                     semi
  426:15  error  Missing semicolon                                                                                     semi
  513:25  error  You should not use directly the "undefined" keyword. Prefer angular.isUndefined or angular.isDefined  angular/definedundefined
  516:25  error  You should not use directly the "undefined" keyword. Prefer angular.isUndefined or angular.isDefined  angular/definedundefined
  519:25  error  You should not use directly the "undefined" keyword. Prefer angular.isUndefined or angular.isDefined  angular/definedundefined
  522:25  error  You should not use directly the "undefined" keyword. Prefer angular.isUndefined or angular.isDefined  angular/definedundefined

C:\git\tasking-manager\client\app\components\language\language-switch.directive.js
  32:5   error  You should use the $inject syntax for DI  angular/di
  80:10  error  Missing semicolon                         semi

C:\git\tasking-manager\client\app\components\popup\map-popup.directive.js
  36:5  error  You should use the $inject syntax for DI  angular/di

C:\git\tasking-manager\client\app\components\project-chat\project-chat.directive.js
   37:5   error  You should use the $inject syntax for DI  angular/di
   81:11  error  Missing semicolon                         semi
  179:10  error  Missing semicolon                         semi

C:\git\tasking-manager\client\app\components\show-project-aois\show-project-aois.directive.js
   36:5   error  You should use the $inject syntax for DI  angular/di
   40:44  error  Missing semicolon                         semi
  111:15  error  Missing semicolon                         semi

✖ 156 problems (156 errors, 0 warnings)
  68 errors, 0 warnings potentially fixable with the `--fix` option.

[13:33:33] Finished 'eslint' after 1.52 min
```

### CODE REVIEW

**Comment by ethan-nelson** [comment]
Hi David, thank you for this! We're slowly working flake8 into the backend, so it'll be great to have eslint on the frontend. And this ran great after installing the new packages with npm.

One question I have: is there a particular reason you chose windows for the linebreak style? I turned up 9228 problems on my linux machine. Would it be possible to not specify an OS on that?

Thanks again!

**Comment by dkocich** [comment]
there was no reason to use it - it is changed now; I also added recommended settings by ESLint and the current log is here https://gist.github.com/dkocich/c24732a17c9d6a6b7ac1460394fbf678

**Comment by ethan-nelson** [comment]
Sorry I haven't gotten back to you yet, @dkocich--things got busy. I will take a look again this weekend. Thank you!

**Comment by ethan-nelson** [comment]
A bit overdue, but thank you @dkocich !

**Pull request merged**
