### PR TITLE
Apply subqueries to reduce response time in projects last activities …

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
…endpoint

Response time reduced from 10s to ~500 ms

### CODE REVIEW

**Review by willemarcel — CHANGES_REQUESTED** [review]
@JorgeMartinezG it's not returning data of all the tasks. Testing with a local project, the develop branch returns 170 tasks. This PR returns 101.

**Comment by willemarcel** [comment]
@JorgeMartinezG I identified the issue. This new query is returning only data from tasks that had some activity. It would not be a problem, but we need to know when there are new tasks on the project (caused by task split) in order to update the map. The method we use on the frontend to decide when to fetch the tasks geojson endpoint is: do it when the number of tasks returned by the activities' endpoint changes in relation to the previous one.

**Comment by JorgeMartinezG** [comment]
Thanks for reviewing wille. I'm checking and what is happening is that we do not capture the tasks that do not have changes since they do not appear in the task history table. The fix would be to get the ids first and then left outer join with task history

**Review by willemarcel — APPROVED** [review]
Perfect! Super improvement!

**Pull request merged**
