### PR TITLE
Update personal information form validation logic

### LINKED ISSUE #5264: [BUG] Cleared form values won't save
**Describe the bug**
On the settings page, under the 'Personal information' section, the cleared values won't be saved when form values are removed and submitted.

**To Reproduce**
1. Go to the [Settings page](https://tasks.hotosm.org/settings).
2. Clear unrequired text input field(s).
3. Click the 'Save' button.
4. Refresh the page.
5. Find that your changes have not been saved.

**Expected behavior**
Values of the fields must be updated on clear.

**Additional context**
Cleared values are not being sent as payload to the API endpoint.

### PR DESCRIPTION
**Pull request by HelNershingThapa**
This PR does the following:
- Closes #5264 
- Sets 'Name' field as required
- Sets 'Email' as required and requires the input to match a regex pattern

### CODE REVIEW

**Comment by Patrik-Br** [comment]
Tested part "Closes https://github.com/hotosm/tasking-manager/issues/5264" Need fix.

If I input anything into the City, Username on HOT Slack, Twitter, Facebook or LinkedIn, save and then remove it, it won't let me save it. So they won't let me save those fields empty (exactly the behavior that is better explained in the BUG report itself).

**Comment by martien-176** [comment]
What/how should i test here?

**Comment by Patrik-Br** [comment]
Works in live version 👍 perfect.

**Comment by martien-176** [comment]
As to #5264.

Followed test procedure mentioned there.

Result: works as expected, cleared fields stay empty.

**Pull request merged**
