### PR TITLE
Remove requests dependencies from requirements.txt

### PR DESCRIPTION
**Pull request by willemarcel**
Those are [dependencies from requests](https://github.com/psf/requests/blob/master/setup.py#L44-L48) and are automatically installed when we run `pip install`.

How to test:

- uninstall manually those dependencies;
- run pip install -r requirements.txt;
- check on the console that it was installed again;
- run the server and check that everything works normally

### CODE REVIEW

**Comment by ramyaragupathy** [comment]
Per chat [here](https://github.com/hotosm/tasking-manager/pull/3203) -we decided to retain all those dependencies that are part of the dependency tree. If we are removing specifically dependencies that are part of `requests` dependency tree, then we introduce an inconsistency when we retain other libraries which are not indirectly included while installing other packages.

I would suggest to always run a [`pipdeptree`](https://pypi.org/project/pipdeptree/) check before making any modifications to the requirements file.

cc @JorgeMartinezG 

Current dependency tree

```
APScheduler==3.6.3
  - pytz [required: Any, installed: 2020.1]
  - setuptools [required: >=0.7, installed: 47.1.0]
  - six [required: >=1.4.0, installed: 1.15.0]
  - tzlocal [required: >=1.2, installed: 2.1]
    - pytz [required: Any, installed: 2020.1]
attrs==20.2.0
black==20.8b1
  - appdirs [required: Any, installed: 1.4.4]
  - click [required: >=7.1.2, installed: 7.1.2]
  - mypy-extensions [required: >=0.4.3, installed: 0.4.3]
  - pathspec [required: >=0.6,<1, installed: 0.8.0]
  - regex [required: >=2020.1.8, installed: 2020.10.23]
  - toml [required: >=0.10.1, installed: 0.10.1]
  - typed-ast [required: >=1.4.0, installed: 1.4.1]
  - typing-extensions [required: >=3.7.4, installed: 3.7.4.3]
bleach==3.2.1
  - packaging [required: Any, installed: 20.4]
    - pyparsing [required: >=2.0.2, installed: 2.4.7]
    - six [required: Any, installed: 1.15.0]
  - six [required: >=1.9.0, installed: 1.15.0]
  - webencodings [required: Any, installed: 0.5.1]
blinker==1.4
cachetools==4.1.1
coverage==5.3
entrypoints==0.3
flake8==3.8.4
  - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
  - pycodestyle [required: >=2.6.0a1,<2.7.0, installed: 2.6.0]
  - pyflakes [required: >=2.2.0,<2.3.0, installed: 2.2.0]
Flask-Cors==3.0.9
  - Flask [required: >=0.9, installed: 1.1.2]
    - click [required: >=5.1, installed: 7.1.2]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.11.2]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.1]
  - Six [required: Any, installed: 1.15.0]
Flask-HTTPAuth==4.1.0
  - Flask [required: Any, installed: 1.1.2]
    - click [required: >=5.1, installed: 7.1.2]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.11.2]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.1]
Flask-Migrate==2.5.3
  - alembic [required: >=0.7, installed: 1.4.3]
    - Mako [required: Any, installed: 1.1.3]
      - MarkupSafe [required: >=0.9.2, installed: 1.1.1]
    - python-dateutil [required: Any, installed: 2.8.1]
      - six [required: >=1.5, installed: 1.15.0]
    - python-editor [required: >=0.3, installed: 1.0.4]
    - SQLAlchemy [required: >=1.1.0, installed: 1.3.20]
  - Flask [required: >=0.9, installed: 1.1.2]
    - click [required: >=5.1, installed: 7.1.2]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.11.2]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.1]
  - Flask-SQLAlchemy [required: >=1.0, installed: 2.4.4]
    - Flask [required: >=0.10, installed: 1.1.2]
      - click [required: >=5.1, installed: 7.1.2]
      - itsdangerous [required: >=0.24, installed: 1.1.0]
      - Jinja2 [required: >=2.10.1, installed: 2.11.2]
        - MarkupSafe [required: >=0.23, installed: 1.1.1]
      - Werkzeug [required: >=0.15, installed: 0.16.1]
    - SQLAlchemy [required: >=0.8.0, installed: 1.3.20]
Flask-OAuthlib==0.9.4
  - Flask [required: Any, installed: 1.1.2]
    - click [required: >=5.1, installed: 7.1.2]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.11.2]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.1]
  - oauthlib [required: >=1.1.2, installed: 2.0.2]
  - requests-oauthlib [required: >=0.6.2, installed: 1.0.0]
    - oauthlib [required: >=0.6.2, installed: 2.0.2]
    - requests [required: >=2.0.0, installed: 2.24.0]
      - certifi [required: >=2017.4.17, installed: 2020.6.20]
      - chardet [required: >=3.0.2,<4, installed: 3.0.4]
      - idna [required: >=2.5,<3, installed: 2.10]
      - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.10]
Flask-RESTful==0.3.8
  - aniso8601 [required: >=0.82, installed: 8.0.0]
  - Flask [required: >=0.8, installed: 1.1.2]
    - click [required: >=5.1, installed: 7.1.2]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.11.2]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.1]
  - pytz [required: Any, installed: 2020.1]
  - six [required: >=1.3.0, installed: 1.15.0]
Flask-Script==2.0.6
  - Flask [required: Any, installed: 1.1.2]
    - click [required: >=5.1, installed: 7.1.2]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.11.2]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.1]
flask-swagger==0.2.14
  - Flask [required: >=0.10, installed: 1.1.2]
    - click [required: >=5.1, installed: 7.1.2]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10.1, installed: 2.11.2]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.15, installed: 0.16.1]
  - PyYAML [required: >=5.1, installed: 5.3.1]
GeoAlchemy2==0.8.4
  - SQLAlchemy [required: >=0.8, installed: 1.3.20]
geojson==1.3.4
gevent==20.9.0
  - greenlet [required: >=0.4.17, installed: 0.4.17]
  - setuptools [required: Any, installed: 47.1.0]
  - zope.event [required: Any, installed: 4.5.0]
    - setuptools [required: Any, installed: 47.1.0]
  - zope.interface [required: Any, installed: 5.1.2]
    - setuptools [required: Any, installed: 47.1.0]
glob2==0.7
gunicorn==20.0.4
  - setuptools [required: >=3.0, installed: 47.1.0]
Markdown==3.2.2
newrelic==5.22.0.151
nose==1.3.7
pipdeptree==1.0.0
  - pip [required: >=6.0.0, installed: 20.1.1]
psycopg2==2.8.6
pyproj==2.6.1.post1
python-dotenv==0.14.0
python-slugify==4.0.1
  - text-unidecode [required: >=1.3, installed: 1.3]
schematics==2.1.0
sentry-sdk==0.19.1
  - certifi [required: Any, installed: 2020.6.20]
  - urllib3 [required: >=1.10.0, installed: 1.25.10]
Shapely==1.7.1
Unidecode==1.1.1
```

**Comment by ramyaragupathy** [comment]
I believe it is good to include all direct and indirect dependencies in the requirements file, but open to other view points. @JorgeMartinezG @willemarcel - I also notice we miss including one or two indirect dependencies (as indicated in the dependency tree) in the requirements file. What's your thought about modifying our dependency list to include all?

**Comment by ramyaragupathy** [comment]
We are missing about 11 indirect dependencies:

```
tzlocal [required: >=1.2, installed: 2.1]
mypy-extensions [required: >=0.4.3, installed: 0.4.3]
pathspec [required: >=0.6,<1, installed: 0.8.0]
regex [required: >=2020.1.8, installed: 2020.10.23]
typed-ast [required: >=1.4.0, installed: 1.4.1]
typing-extensions [required: >=3.7.4, installed: 3.7.4.3]
packaging [required: Any, installed: 20.4]
blinker==1.4
zope.event [required: Any, installed: 4.5.0]
zope.interface [required: Any, installed: 5.1.2]
setuptools [required: >=3.0, installed: 47.1.0]
```

**Comment by willemarcel** [comment]
> I also notice we miss including one or two indirect dependencies (as indicated in the dependency tree) in the requirements file. What's your thought about modifying our dependency list to include all?

I don't see a reason to include indirect dependencies. You noticed we are missing 11 indirect dependencies. If it was really needed, I think the system would not be working well.

Another example: requests needs `idna>=2.5,<3`, if we are installing idna directly, how do you manage we are not installing an incompatible version? Let's say idna 3.0 is released, dependabot will open a PR to update it. Will you check everything that depends on idna to see if that version is compatible? How frequently are we checking the new dependencies of requests and all other libraries to include them on requirements?

pip manage all those issues for us, and including indirect dependencies doesn't help in anything, but it is a potential source of problems.

**Comment by willemarcel** [comment]
@ramyaragupathy @JorgeMartinezG  A real example of the problem I pointed previously:
- requests 2.24 needs [urllib3 < 1.26](https://github.com/psf/requests/blob/0797c61fd541f92f66e409dbf9515ca287af28d2/setup.py#L47) 
- Yesterday urllib3 v1.26 was released and a PR was created: https://github.com/hotosm/tasking-manager/pull/3858
- Today requests 2.25 was released and look at this:
image

If we had upgraded urllib3 before the requests upgrade, we could have an inconsistency.

**Comment by ramyaragupathy** [comment]
Not relevant anymore

**Pull request closed without merging**
