### PR TITLE
Adds sorting for projects and projects by owner

### PR DESCRIPTION
**Pull request by fitoria**
Fixes some views for #1601

### CODE REVIEW

**Comment by xamanu** [comment]
Please reroll, @fitoria. Thanks.

**Comment by xamanu** [comment]
@thadk can you please check, whether this has all you need for the "my projects" page?

**Comment by thadk** [comment]
@xamanu @willemarcel Just to be clear, does the main view of My Project page only show projects that either You Favorited, You Contributed to, or You Created?
image

It seems like I have an implementation to get the set of projects favorited (/api/v2/projects/${projectId}/favorite/) and now this gives me a way to get the set of projects created (/api/v2/projects/?createdByMe=true) but I still need a way to get the set of projects that I contributed to (can I use the task API?). Then I think I need to "union" the three sets together on the front end, unless we can/want to do all three in this PR.

**Comment by willemarcel** [comment]
@thadk I think the all options should show everything, but if it's too heavy to load the data from the 3 requests, we could remove the `ALL` option.

You can get the projects a user contributed to (the main function of that view) on `/api/v2/projects/queries/{username}/touched/` (it seems it's failing)

`/api/v2/projects/queries/myself/owner/` returns the projects the current user created.

**Comment by thadk** [comment]
It seems like we might want to search/sort the projects "touched" on the backend using the `/project/` api, as that could be many (hundreds?) projects for some users. Also the front-end filter would not include the full-text search data.

**Comment by thadk** [comment]
@fitoria For the "all" and "contributed" buttons shown above, we decided in the daily call that we need ?contributedToByMe=true as an OR query in addition to ?createdByMe=true (so we can request both at the same time and see a list of both types of projects.) We need to be a little careful with performance because this API is used for everyone using the site so please only use new JOINs if these two special parameters are requested, or re-use JOINs where it is possible. The `/api/v2/projects/queries/{username}/touched/` API might give you a hint as to how to do it efficiently.

Wille said that the `/api/v2/users/queries/favorites/` endpoint should already include the needed fields for project cards, so no action is needed yet on that. I will continue working on the frontend.

**Comment by thadk** [comment]
I think this is ready for review to merge again. We can do the backend for the other tabs in another PR. This will be important for testers to navigate to their own maps.

**Comment by thadk** [comment]
Creates the link for editing project you've created behind "Project Page", to this view https://github.com/hotosm/tasking-manager/pull/2034
Currently it shows this link to all projects, but if we sent information about whether you have management capabilities for that project on your account, it could change/hide the Edit Project link.

**Comment by thadk** [comment]
Also this does not show Draft projects yet, maybe that should be added as another filter in the next followup for this PR.
`CreatedByMe` (done), `CreatedByMeArchived`, `CreatedByMeDraft` (?), `FavoritedByMe`, and `ContributedToByMe`

**Pull request merged**
