### PR TITLE
Users contributions from project frontend

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
This PR includes the user contributions for each project.
pDs6YKDKRF

### CODE REVIEW

**Comment by willemarcel** [comment]
@xamanu @JorgeMartinezG Improvements I've made:
- allow to select the tasks by status and update the action button depending on the status
- activate the instructions tab if the current user has not contributed to the project yet
- some style changes on the contributions tab

Would you like to take a look before merging?

**Comment by JorgeMartinezG** [comment]
@willemarcel I have some opinions:

1. When user has a value within mapped or validated higher than 99 happens an overflow within the div. Like this:
image 
We could decrease the font size or increase the width on the div. The issue would be for mapping level going down because of a similar overflow.

2. To highlight tasks, IMO we could optimize a bit: The backend could be modified to return mapped and validated taskids separated. Then, the frontend renders for each user, a handler that receives the id of the array and the option (mapped, validated or total) to get the TaskIds. The function just returns the required ids and updates the map. In this way we do not need a new state variable and the loop to filter among the whole TaskIds array for a given user.

Let me know your opinions

**Comment by willemarcel** [comment]
> When user has a value within mapped or validated higher than 99 happens an overflow within the div. Like this:

@JorgeMartinezG  good catch! I'll test some solutions

> To highlight tasks, IMO we could optimize a bit: The backend could be modified to return mapped and validated taskids separated. Then, the frontend renders for each user, a handler that receives the id of the array and the option (mapped, validated or total) to get the TaskIds. The function just returns the required ids and updates the map. In this way we do not need a new state variable and the loop to filter among the whole TaskIds array for a given user.

Yes, it would be a good improvement... Another problem that I see right now is that we are showing the number of mapped tasks, but we are highlighting only the ones that are yet on the MAPPED state. I choose this way because the goal here is to allow a validator to validate all the tasks. I was thinking if we should change the text to `x ready for validation`. I see that the mapped number is counting tasks locked for mapping and set as bad imagery.

So applying the solution you proposed, I suggest to have an array for tasks that are on the MAPPED state, another that are on VALIDATED state and another to all tasks the user has contributed.

**Comment by willemarcel** [comment]
@JorgeMartinezG I pushed some improvements on responsiveness

**Comment by JorgeMartinezG** [comment]
@willemarcel Good to go.

**Pull request merged**
