### PR TITLE
Version 3.2.0 Release (redux)

### PR DESCRIPTION
**Pull request by dakotabenjamin**
This is a PR to make sure the commit histories are aligned between the two branches. See #1420 for release notes.

### CODE REVIEW

**Comment by xamanu** [comment]
Please wait with this PR and the 3.2.0 release for this `critical` issue to get in: #1438!

**Comment by xamanu** [comment]
A urgent fix has been applied. This is good to go.

**Comment by xamanu** [comment]
@dakotabenjamin, I suggest to update the changelog a bit:

## Important note

**Please note: This release introduces changes in the configuration. Please make sure you adjusted and tested properly.**

Some of the environment variables have changed. Make sure you adjust them before rolling this release out:

* `TM_ENV` has become deprecated, instead administrators have to specify the `TM_APP_BASE_URL` for the url any instance is running on.
* Make sure you specify your sender email address for all notifications from your Tasking Manager with `TM_EMAIL_FROM_ADDRESS`
* Verify `TM_LOG_DIR` matches the correct place of your log files.

*For more detailed information on the use of all existing environment variables have a look at the `example.env` in the main directory*

## Changelog

* Add docker-compose file for quick and easy builds
* New API endpoint for viewing users' invalidated tasks
* Style improvements
* Translation improvements
* Update documentation
* Fix menu not closing automatically
* Consolidates configuration file for easy local development setup and deployment
* Prevent blocked user from commenting

**Comment by dakotabenjamin** [comment]
:+1: @xamanu there appear to be some merge conflicts. Should I perform an update on the branch using the GitHub UI?

**Comment by xamanu** [comment]
The branch needed to be updated on `master` again.

**Pull request merged**
